import InformationTheory.Probability.TwoSidedExtension.Core
import InformationTheory.Probability.TwoSidedExtension.Backward
import InformationTheory.Probability.TwoSidedExtension.BackwardIntegral
import InformationTheory.Probability.TwoSidedExtension.CondExpMeasurePreserving

/-!
# 2-sided stationary extension `μ_ℤ` (SMB Phase D — sub-plan)

For a stationary process `(Ω, T, μ, X)` with `X : Ω → α` (Fintype), this module
builds the canonical 2-sided extension `μ_ℤ : Measure (ℤ → α)` such that:

* the natural ℕ-projection of `μ_ℤ` agrees with the law of `(X ∘ T^[i])_{i ≥ 0}`,
* the shift `σ : (ℤ → α) → (ℤ → α)`, `σ x i := x (i + 1)`, is `μ_ℤ`-preserving,
* `μ_ℤ` is ergodic whenever `(Ω, T, μ)` is.

The extension is needed because the SMB lower bound (`liminf blockLogAvg ≥
entropyRate`) hinges on the *backward* Levy convergence applied to the
σ-algebra generated by the negative-time coordinates, which is *not* available
on the one-sided (`ℕ`-indexed) side.

See `docs/shannon/smb-two-sided-extension-plan.md` for the full plan, route
choice (Hahn–Kolmogorov on cylinder semiring), and per-phase risks.

## Structure

The plan is split into eight phases A–H. This file is the carrier for Phase B
through Phase G, with Phase A being the skeleton. Phase H (the actual SMB
`liminf` discharge) lives in a follow-up file `SMBLiminfDischarge.lean`.

* **Phase A** — skeleton, namespace, imports.
* **Phase B** — `shiftedMarginal`, the family of finite-dimensional marginals
  obtained from the one-sided stationary distribution by translating any finite
  index set into `ℕ`. *(this file: filled.)*
* **Phase C** — projective consistency `IsProjectiveMeasureFamily` + the
  `tendsto_zero` σ-additivity input. *(this file: skeleton with `sorry`.)*
* **Phase D** — Carathéodory extension `μZ` via `AddContent.measure`.
  *(this file: skeleton with `sorry`.)*
* **Phase E** — shift `MeasurePreserving` + `Ergodic` transfer.
  *(this file: skeleton with `sorry`.)*
* **Phase F** — coupling `(Ω, T, μ) ↔ (ℤ → α, σ, μZ)` on ℕ-projection.
  *(this file: skeleton with `sorry`.)*
* **Phase G** — forward filtration `pastSigma` (finite past of length `k`),
  forward Lévy upward convergence `pmfLogCondPast → pmfLogCondInfty`, and
  the SMB bridge `∫ pmfLogCondInfty dμZ = entropyRate μ p`.

## Main definitions (Phase B)

* `shiftAmount J` — the smallest non-negative offset making every element of
  `J : Finset ℤ` non-negative.
* `obsZ μ p N J` — the joint observation `ω ↦ fun j : J ↦ X (T^[(j+N).toNat] ω)`.
* `shiftedMarginal μ p J` — `μ.map (obsZ μ p (shiftAmount J) J)`.

## Main results (Phase B)

* `shiftedMarginal_eq_of_shift` — N-independence: any sufficient shift gives
  the same pushforward, via stationarity.
* `isProjectiveMeasureFamily_shiftedMarginal` — projective consistency.
* `instIsProbabilityMeasure_shiftedMarginal` — each marginal is a probability
  measure.
-/
