/-
PROBE — not an in-project asset.  Regenerated by the N2 independent audit (leg N2-audit).
Nothing here is imported by `InformationTheory/`; it exists only to measure what the
region `Thm7(W)` costs to state in Lean.

Target of the reproduction: N2 §4 P9 (`n2_b.lean`) — the region `Thm7(W)` end to end.
Source of the constraints: [auxrec] Gohari-Nair, Theorem 7, `auxrec.txt:1034-1084`
(pdftotext -layout of https://chandra.ie.cuhk.edu.hk/pub/papers/NIT/Auxiliary-Receiver.pdf).
-/
import InformationTheory.Shannon.BroadcastChannel.Marton.RegionCardinality
import InformationTheory.Shannon.CondMutualInfo
import InformationTheory.Shannon.MutualInfo
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Probability.Independence.Conditional
import Mathlib.Data.Fin.VecNotation

open MeasureTheory ProbabilityTheory InformationTheory.Shannon
open InformationTheory.Shannon.BroadcastChannel
open InformationTheory.Shannon.BroadcastChannel.Marton

namespace ProbeThm7

universe u

/-- Mutual information as a real (the slots are differenced, so `ℝ≥0∞` truncation is wrong). -/
noncomputable def miR {Ω : Type*} [MeasurableSpace Ω] {S T : Type*}
    [MeasurableSpace S] [MeasurableSpace T] (ν : Measure Ω) (f : Ω → S) (g : Ω → T) : ℝ :=
  (mutualInfo ν f g).toReal

/-- Conditional mutual information as a real. -/
noncomputable def cmiR {Ω : Type*} [MeasurableSpace Ω] (ν : Measure Ω) (hν : IsFiniteMeasure ν)
    {S : Type*} [MeasurableSpace S] [StandardBorelSpace S] [Nonempty S]
    {T : Type*} [MeasurableSpace T] [StandardBorelSpace T] [Nonempty T]
    {R : Type*} [MeasurableSpace R] (f : Ω → S) (g : Ω → T) (h : Ω → R) : ℝ :=
  letI := hν
  (condMutualInfo ν f g h).toReal

/-- Auxiliary index: `(j, i)` is the `i`-th member of the `j`-th auxiliary triple.
`(0,·) = (U,V,W)`, `(1,·) = (Ũ,Ṽ,W̃)`, `(2,·) = (Û,V̂,Ŵ)`; slot `i = 2` is the `W`-type one. -/
abbrev AuxIdx := Fin 3 × Fin 3

/-- The 13-variable ambient space of `auxrec.txt:1074`:
nine auxiliaries (as an `AuxIdx`-indexed family) together with `X`, `Y`, `Z`, `J`. -/
abbrev Amb (kv : AuxIdx → ℕ) (kJ : ℕ) (α β₁ β₂ : Type u) : Type u :=
  ((i : AuxIdx) → bcAuxAlphabet.{u} (kv i)) × α × β₁ × β₂ × bcAuxAlphabet.{u} kJ

variable {α β₁ β₂ : Type u} [Fintype α] [MeasurableSpace α] [StandardBorelSpace α] [Nonempty α]
  [Fintype β₁] [MeasurableSpace β₁] [StandardBorelSpace β₁] [Nonempty β₁]
  [Fintype β₂] [MeasurableSpace β₂] [StandardBorelSpace β₂] [Nonempty β₂]

section Slots

variable {kv : AuxIdx → ℕ} {kJ : ℕ}

/-- The 25 information slots of Theorem 7, as reals.
`0-16` are the 17 slots that `(18a)-(18i)` mention; `17-24` are the 8 further slots that only
`(19a)-(19c)` / `(20a)-(20b)` mention. -/
noncomputable def slots (ν : Measure (Amb kv kJ α β₁ β₂)) (hν : IsFiniteMeasure ν) :
    Fin 25 → ℝ :=
  let A : (i : AuxIdx) → Amb kv kJ α β₁ β₂ → bcAuxAlphabet.{u} (kv i) := fun i q ↦ q.1 i
  let X : Amb kv kJ α β₁ β₂ → α := fun q ↦ q.2.1
  let Y : Amb kv kJ α β₁ β₂ → β₁ := fun q ↦ q.2.2.1
  let Z : Amb kv kJ α β₁ β₂ → β₂ := fun q ↦ q.2.2.2.1
  let J : Amb kv kJ α β₁ β₂ → bcAuxAlphabet.{u} kJ := fun q ↦ q.2.2.2.2
  ![ miR ν (A (0, 2)) Y,                                  -- 0  I(W ; Y)
     miR ν (A (2, 2)) Y,                                  -- 1  I(Ŵ ; Y)
     miR ν (A (0, 2)) Z,                                  -- 2  I(W ; Z)
     miR ν (A (1, 2)) Z,                                  -- 3  I(W̃ ; Z)
     cmiR ν hν (A (0, 0)) Y (A (0, 2)),                   -- 4  I(U ; Y | W)
     miR ν (A (1, 2)) J,                                  -- 5  I(W̃ ; J)
     miR ν (A (2, 2)) J,                                  -- 6  I(Ŵ ; J)
     cmiR ν hν (A (1, 0)) J (A (1, 2)),                   -- 7  I(Ũ ; J | W̃)
     cmiR ν hν (A (2, 0)) Y (A (2, 2)),                   -- 8  I(Û ; Y | Ŵ)
     cmiR ν hν (A (2, 0)) J (A (2, 2)),                   -- 9  I(Û ; J | Ŵ)
     cmiR ν hν (A (0, 1)) Z (A (0, 2)),                   -- 10 I(V ; Z | W)
     cmiR ν hν (A (2, 1)) J (A (2, 2)),                   -- 11 I(V̂ ; J | Ŵ)
     cmiR ν hν (A (1, 1)) Z (A (1, 2)),                   -- 12 I(Ṽ ; Z | W̃)
     cmiR ν hν (A (1, 1)) J (A (1, 2)),                   -- 13 I(Ṽ ; J | W̃)
     miR ν X J,                                           -- 14 I(X ; J)
     cmiR ν hν X Y (fun q ↦ (A (0, 1) q, A (0, 2) q)),    -- 15 I(X ; Y | V, W)
     cmiR ν hν X Z (fun q ↦ (A (0, 0) q, A (0, 2) q)),    -- 16 I(X ; Z | U, W)
     cmiR ν hν (A (1, 0)) Z (A (1, 2)),                   -- 17 I(Ũ ; Z | W̃)
     cmiR ν hν (A (0, 0)) Z (A (0, 2)),                   -- 18 I(U ; Z | W)
     cmiR ν hν (A (2, 1)) Y (A (2, 2)),                   -- 19 I(V̂ ; Y | Ŵ)
     cmiR ν hν (A (0, 1)) Y (A (0, 2)),                   -- 20 I(V ; Y | W)
     cmiR ν hν X Z (fun q ↦ (A (1, 0) q, A (1, 2) q)),    -- 21 I(X ; Z | Ũ, W̃)
     cmiR ν hν X J (fun q ↦ (A (1, 0) q, A (1, 2) q)),    -- 22 I(X ; J | Ũ, W̃)
     cmiR ν hν X Y (fun q ↦ (A (2, 1) q, A (2, 2) q)),    -- 23 I(X ; Y | V̂, Ŵ)
     cmiR ν hν X J (fun q ↦ (A (2, 1) q, A (2, 2) q)) ]   -- 24 I(X ; J | V̂, Ŵ)

end Slots

/-- The constraint bundle `(18a)-(18i)` of `auxrec.txt:1037-1071`, read off the 25 slots. -/
def InThm7 (s : Fin 25 → ℝ) (R : ℝ × ℝ × ℝ) : Prop :=
  R.1 ≤ min (min (s 0) (s 1)) (min (s 2) (s 3))                                         -- (18a)
  ∧ R.1 + R.2.1 ≤ min (s 0) (s 2) + s 4                                                 -- (18b)
  ∧ R.1 + R.2.1 ≤
      min (s 3 + min 0 (s 0 - s 2)) (s 5 + s 1 - s 6) + s 7 + s 8 - s 9                 -- (18c)
  ∧ R.1 + R.2.1 ≤ min (s 1 + min 0 (s 2 - s 0)) (s 6 + s 3 - s 5) + s 8                 -- (18d)
  ∧ R.1 + R.2.2 ≤ min (s 0) (s 2) + s 10                                                -- (18e)
  ∧ R.1 + R.2.2 ≤
      min (s 1 + min 0 (s 2 - s 0)) (s 6 + s 3 - s 5) + s 11 + s 12 - s 13              -- (18f)
  ∧ R.1 + R.2.2 ≤ min (s 3 + min 0 (s 0 - s 2)) (s 5 + s 1 - s 6) + s 12                -- (18g)
  ∧ R.1 + R.2.1 + R.2.2 ≤
      min (s 1 - s 6) (s 3 - s 5) + s 14 + s 8 - s 9 + s 12 - s 13                      -- (18h)
  ∧ R.1 + R.2.1 + R.2.2 ≤ min (s 0) (s 2) + min (s 10 + s 15) (s 4 + s 16)              -- (18i)

/-- The eligibility conditions `(19a)-(19c)` / `(20a)-(20c)` of `auxrec.txt:1076-1082`. -/
def Thm7Eligible (s : Fin 25 → ℝ) : Prop :=
  (s 3 - s 5) + (s 6 - s 1) = s 2 - s 0                                                 -- (19a)
  ∧ (s 17 - s 7) + (s 9 - s 8) = s 18 - s 4                                             -- (19b)
  ∧ (s 12 - s 13) + (s 11 - s 19) = s 10 - s 20                                         -- (19c)
  ∧ 0 ≤ s 21 - s 22 ∧ s 21 - s 22 ≤ s 12 - s 13                                         -- (20a)
  ∧ 0 ≤ s 23 - s 24 ∧ s 23 - s 24 ≤ s 8 - s 9                                           -- (20b)
  ∧ s 10 + s 15 = s 4 + s 16                                                            -- (20c)

section Law

variable {kv : AuxIdx → ℕ} {kJ : ℕ}

/-- The factorisation of `auxrec.txt:1074`, as four clauses: the three auxiliary triples are
conditionally independent given `X`; `(Y, Z)` is the channel applied to `X`; `J` is the
auxiliary channel applied to `(X, Y, Z)`; and `X` has the prescribed law. -/
def IsThm7Law (W : BCChannel α β₁ β₂) (TJ : Kernel (α × β₁ × β₂) (bcAuxAlphabet.{u} kJ))
    (p : Measure α) (ν : Measure (Amb kv kJ α β₁ β₂)) (hν : IsFiniteMeasure ν) : Prop :=
  @iCondIndepFun (Amb kv kJ α β₁ β₂) (Fin 3) _ _ inferInstance
      (((measurable_fst.comp measurable_snd :
        Measurable (fun q : Amb kv kJ α β₁ β₂ ↦ q.2.1))).comap_le)
      (fun j ↦ (i : Fin 3) → bcAuxAlphabet.{u} (kv (j, i))) _
      (fun j q i ↦ q.1 (j, i)) ν hν
  ∧ ν.map (fun q ↦ (q.2.1, q.2.2.1, q.2.2.2.1)) = (ν.map (fun q ↦ q.2.1)) ⊗ₘ W
  ∧ ν.map (fun q ↦ ((q.2.1, q.2.2.1, q.2.2.2.1), q.2.2.2.2)) =
      (ν.map (fun q ↦ (q.2.1, q.2.2.1, q.2.2.2.1))) ⊗ₘ TJ
  ∧ ν.map (fun q ↦ q.2.1) = p

end Law

/-- The cardinality caps of `auxrec.txt:1083-1084`: `|W|, |Ŵ|, |W̃| ≤ |X| + 6` and
`|U|, |V|, |Û|, |V̂|, |Ũ|, |Ṽ| ≤ |X| + 1`. -/
def thm7Cap (α : Type u) [Fintype α] (i : AuxIdx) : ℕ :=
  if i.2 = 2 then Fintype.card α + 6 else Fintype.card α + 1

/-- One admissible law's worth of the region. -/
noncomputable def thm7RegionOfLaw {kv : AuxIdx → ℕ} {kJ : ℕ}
    (ν : Measure (Amb kv kJ α β₁ β₂)) (hν : IsFiniteMeasure ν) : Set (ℝ × ℝ × ℝ) :=
  {R | InThm7 (slots ν hν) R ∧ Thm7Eligible (slots ν hν)}

/-- The region `Thm7(W) ⊆ ℝ³`: `⋃_p ⋂_{T_J} ⋃_{aux}` with the cardinality caps in place. -/
noncomputable def thm7Region (W : BCChannel α β₁ β₂) : Set (ℝ × ℝ × ℝ) :=
  ⋃ (p : ProbabilityMeasure α),
    ⋂ (kJ : ℕ) (TJ : Kernel (α × β₁ × β₂) (bcAuxAlphabet.{u} kJ)) (_ : IsMarkovKernel TJ),
      ⋃ (kv : AuxIdx → ℕ) (_ : ∀ i, kv i < thm7Cap α i)
        (ν : Measure (Amb kv kJ α β₁ β₂)) (hν : IsFiniteMeasure ν)
        (_ : IsThm7Law W TJ (p : Measure α) ν hν),
        thm7RegionOfLaw ν hν

/-- The `R₀ = 0` slice of `thm7Region`, as a subset of the plane. -/
noncomputable def thm7RegionSlice (W : BCChannel α β₁ β₂) : Set (ℝ × ℝ) :=
  {q | (0, q.1, q.2) ∈ thm7Region W}

/-- Slicing commutes with both the union and the intersection: it is a preimage. -/
lemma slice_comm {ι : Type*} (S : ι → Set (ℝ × ℝ × ℝ)) :
    ({q : ℝ × ℝ | (0, q.1, q.2) ∈ ⋃ i, S i} = ⋃ i, {q : ℝ × ℝ | (0, q.1, q.2) ∈ S i})
    ∧ ({q : ℝ × ℝ | (0, q.1, q.2) ∈ ⋂ i, S i} = ⋂ i, {q : ℝ × ℝ | (0, q.1, q.2) ∈ S i}) := by
  constructor <;> ext q <;> simp

end ProbeThm7
