/-
PROBE — not an in-project asset.  Regenerated by the N2 independent audit (leg N2-audit).
Nothing here is imported by `InformationTheory/`.

Target of the reproduction: N2 §4 P12 (`n2_beta.lean`) — the (β) effectivity layer,
statements only, no proofs.  The point of the probe is exactly that: every declaration
below is a `Prop`-valued definition or a statement whose proof is absent.
-/
import Mathlib.Computability.Halting
import Mathlib.Data.Rat.Denumerable
import Mathlib.Analysis.Convex.StdSimplex
import Mathlib.Topology.Maps.Proper.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Basic

open Set Topology

namespace ProbeBeta

/-- A rational ball in `ℝⁿ` (sup metric): a rational centre and a rational radius. -/
abbrev RatBallN (n : ℕ) : Type := (Fin n → ℚ) × ℚ

instance (n : ℕ) : Primcodable (RatBallN n) := inferInstance

/-- The subset of `ℝⁿ` a rational ball names. -/
def ratBallNSet {n : ℕ} (b : RatBallN n) : Set (Fin n → ℝ) :=
  {x | ∀ i, |x i - (b.1 i : ℝ)| < (b.2 : ℝ)}

/-- Effectively open: a c.e. union of rational balls. -/
def IsEffectivelyOpenN {n : ℕ} (S : Set (Fin n → ℝ)) : Prop :=
  ∃ E : RatBallN n → Prop, REPred E ∧ S = ⋃ b ∈ {b | E b}, ratBallNSet b

/-- Effectively closed (`Π01`): the complement is effectively open. -/
def IsEffectivelyClosedN {n : ℕ} (S : Set (Fin n → ℝ)) : Prop :=
  IsEffectivelyOpenN Sᶜ

/-- Effectively compact: compact, and the finite rational covers are c.e. -/
def IsEffectivelyCompactN {n : ℕ} (S : Set (Fin n → ℝ)) : Prop :=
  IsCompact S ∧ REPred (fun L : List (RatBallN n) ↦ S ⊆ ⋃ b ∈ L, ratBallNSet b)

/-- Computably overt: the rational balls that meet `S` are c.e.
This is the other one-sidedness, not the dual of effective compactness. -/
def IsComputablyOvertN {n : ℕ} (S : Set (Fin n → ℝ)) : Prop :=
  REPred (fun b : RatBallN n ↦ (S ∩ ratBallNSet b).Nonempty)

/-- Effectively continuous: a c.e. relation between rational input balls and rational
output balls whose image is contained in the output ball. -/
def IsEffectivelyContinuousN {n : ℕ} (f : (Fin n → ℝ) → ℝ) (S : Set (Fin n → ℝ)) : Prop :=
  ∃ E : RatBallN n × RatBallN 1 → Prop, REPred E ∧
    ∀ b c, E (b, c) → ∀ x ∈ S ∩ ratBallNSet b, (fun _ : Fin 1 ↦ f x) ∈ ratBallNSet c

/-- Concatenation of an `n`-point and an `m`-point into an `(n+m)`-point. -/
def joinFin {n m : ℕ} (x : Fin n → ℝ) (y : Fin m → ℝ) : Fin (n + m) → ℝ := Fin.append x y

/-- (L-∃), effective version: projecting a `Π01` relation along an effectively compact
fibre keeps it `Π01`.  Core theorem 4 of the N2 count; unproved here. -/
def LExists (n m : ℕ) : Prop :=
  ∀ (R : Set (Fin (n + m) → ℝ)) (Y : Set (Fin m → ℝ)),
    IsEffectivelyClosedN R → IsEffectivelyCompactN Y →
    IsEffectivelyClosedN {x : Fin n → ℝ | ∃ y ∈ Y, joinFin x y ∈ R}

/-- (L-∀), effective version: a universally quantified `Π01` relation stays `Π01` when the
fibre is computably overt.  Core theorem 6; unproved here. -/
def LForall (n m : ℕ) : Prop :=
  ∀ (R : Set (Fin (n + m) → ℝ)) (Y : Set (Fin m → ℝ)),
    IsEffectivelyClosedN R → IsComputablyOvertN Y →
    IsEffectivelyClosedN {x : Fin n → ℝ | ∀ y ∈ Y, joinFin x y ∈ R}

/-- Countable intersections of a *uniformly* `Π01` family stay `Π01`.  Core theorem 7. -/
def Pi01ClosedUnderIInterUniform (n : ℕ) : Prop :=
  ∀ S : ℕ → Set (Fin n → ℝ),
    (∃ E : ℕ × RatBallN n → Prop, REPred E ∧
      ∀ k, (S k)ᶜ = ⋃ b ∈ {b | E (k, b)}, ratBallNSet b) →
    IsEffectivelyClosedN (⋂ k, S k)

/-- The non-uniform variant, which is also writable and is *weaker*: the type does not
prevent the uniformity from being dropped. -/
def Pi01ClosedUnderIInter (n : ℕ) : Prop :=
  ∀ S : ℕ → Set (Fin n → ℝ), (∀ k, IsEffectivelyClosedN (S k)) →
    IsEffectivelyClosedN (⋂ k, S k)

/-- The constraint set of a non-strict inequality between effectively continuous
functionals is `Π01`.  Core theorem 2; unproved here. -/
def ConstraintSetPi01 (n : ℕ) : Prop :=
  ∀ (f g : (Fin n → ℝ) → ℝ) (S : Set (Fin n → ℝ)),
    IsEffectivelyCompactN S → IsEffectivelyContinuousN f S → IsEffectivelyContinuousN g S →
    IsEffectivelyClosedN {x ∈ S | f x ≤ g x}

/-- The standard simplex in `ℝⁿ`, as the witness space. -/
def simplexN (n : ℕ) : Set (Fin n → ℝ) := {x | (∀ i, 0 ≤ x i) ∧ ∑ i, x i = 1}

/-- Effective compactness of the witness space.  Core theorem 3, the body of the layer;
unproved here.

The over-general form `∀ S, IsCompact S → IsEffectivelyCompactN S` also type-checks, and it
is false: a compact set need not have a c.e. family of finite rational covers.  The audit
wrote that form first and the compiler accepted it in silence. -/
def WitnessEffectivelyCompact (n : ℕ) : Prop :=
  IsEffectivelyCompactN (simplexN n)

/-- Effective continuity of the entropy functional on the witness space.  Core theorem 1;
unproved here.  The mutual-information slots are differences of such functionals. -/
def MutualInfoEffectivelyContinuous (n : ℕ) : Prop :=
  IsEffectivelyContinuousN (fun x ↦ ∑ i, x i * Real.log (x i)) (simplexN n)

section Classical

/-- The classical (L-∃): available in Mathlib, one line. -/
theorem classical_LExists {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    [CompactSpace Y] {R : Set (X × Y)} (hR : IsClosed R) : IsClosed (Prod.fst '' R) :=
  isClosedMap_fst_of_compactSpace _ hR

/-- The classical (L-∀): available in Mathlib, and it asks *nothing* of `Y`.
The effective version needs computable overtness, which has no classical counterpart. -/
theorem classical_LForall {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    {R : Set (X × Y)} (hR : IsClosed R) : IsClosed {x : X | ∀ y : Y, (x, y) ∈ R} := by
  have : {x : X | ∀ y : Y, (x, y) ∈ R} = ⋂ y : Y, (fun x ↦ (x, y)) ⁻¹' R := by
    ext x; simp
  rw [this]
  exact isClosed_iInter fun y ↦ hR.preimage (by fun_prop)

/-- The classical compactness of the witness space. -/
theorem classical_witness_compact (ι : Type*) [Fintype ι] : IsCompact (stdSimplex ℝ ι) :=
  isCompact_stdSimplex ℝ ι

end Classical

end ProbeBeta
