import Mathlib.Dynamics.Ergodic.Ergodic
import Mathlib.Dynamics.Ergodic.MeasurePreserving
import Mathlib.Probability.IdentDistrib
import Mathlib.MeasureTheory.MeasurableSpace.Basic

/-!
# Stationary processes (E-8 / SMB Phase A — MVP)

Lean encoding of a stationary (resp. ergodic) discrete-time process via a
`MeasurePreserving` (resp. `Ergodic`) shift `T : Ω → Ω` together with a
single observable `X : Ω → α`. Time-`i` observation is `X ∘ T^[i]`, the
block `(X_0, …, X_{n-1})` is `blockRV n : Ω → (Fin n → α)`.

This is the Phase A skeleton from
[`docs/shannon/shannon-mcmillan-breiman-plan.md`](../../docs/shannon/shannon-mcmillan-breiman-plan.md);
the further phases (B onward) build the entropy rate, Birkhoff, log-likelihood
chain rule, and the SMB main theorem on top of these definitions.

## Main definitions

* `StationaryProcess` — bundles `T`, `X`, `MeasurePreserving T μ μ`, `Measurable X`.
* `StationaryProcess.obs i` — the time-`i` observation `X ∘ T^[i]`.
* `StationaryProcess.blockRV n` — joint `(X_0, …, X_{n-1}) : Ω → (Fin n → α)`.
* `ErgodicProcess` — extends `StationaryProcess` with `Ergodic T μ`.

## Main results (Phase A)

* `StationaryProcess.measurable_obs` — each `obs i` is measurable.
* `StationaryProcess.measurable_blockRV` — `blockRV n` is measurable.
* `StationaryProcess.identDistrib_obs_zero` — `obs i` has the same law as `obs 0`
  (stationarity, derived from `MeasurePreserving.iterate`).
-/

namespace InformationTheory.Shannon

open MeasureTheory ProbabilityTheory

variable {Ω : Type*} [MeasurableSpace Ω]
variable {α : Type*} [Fintype α] [DecidableEq α] [Nonempty α]
  [MeasurableSpace α] [MeasurableSingletonClass α]

/-- A stationary process: a measure-preserving transformation `T : Ω → Ω` on
`(Ω, μ)` together with a measurable observable `X : Ω → α`. The time-`i`
observation is `X ∘ T^[i]`. -/
structure StationaryProcess (μ : Measure Ω) (α : Type*) [MeasurableSpace α] where
  /-- The shift / time-evolution map. -/
  T : Ω → Ω
  /-- The single observable; later samples are obtained by composing with `T^[i]`. -/
  X : Ω → α
  /-- `T` preserves `μ`. -/
  measurePreserving : MeasurePreserving T μ μ
  /-- The observable is measurable. -/
  measurable_X : Measurable X

namespace StationaryProcess

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]

variable {μ : Measure Ω}

/-- Time-`i` observation `X_i := X ∘ T^[i]`. -/
def obs (p : StationaryProcess μ α) (i : ℕ) : Ω → α :=
  p.X ∘ p.T^[i]

/-- The shift map is measurable (it preserves `μ`, in particular it is measurable). -/
lemma measurable_T (p : StationaryProcess μ α) : Measurable p.T :=
  p.measurePreserving.measurable

/-- `T^[i]` is measurable for any `i`. -/
lemma measurable_iterate (p : StationaryProcess μ α) (i : ℕ) : Measurable (p.T^[i]) :=
  (p.measurePreserving.iterate i).measurable

/-- Each time-`i` observation is measurable. -/
lemma measurable_obs (p : StationaryProcess μ α) (i : ℕ) : Measurable (p.obs i) :=
  p.measurable_X.comp (p.measurable_iterate i)

/-- Block joint observation `(X_0, X_1, …, X_{n-1}) : Ω → (Fin n → α)`. -/
def blockRV (p : StationaryProcess μ α) (n : ℕ) : Ω → (Fin n → α) :=
  fun ω i => p.obs i ω

/-- The block random variable is measurable. -/
lemma measurable_blockRV (p : StationaryProcess μ α) (n : ℕ) :
    Measurable (p.blockRV n) := by
  refine measurable_pi_iff.mpr (fun i => ?_)
  exact p.measurable_obs i

end StationaryProcess

/-- An ergodic stationary process: a `StationaryProcess` whose shift is moreover
ergodic. The `toStationaryProcess` coercion is auto-generated by `extends`. -/
structure ErgodicProcess (μ : Measure Ω) (α : Type*) [MeasurableSpace α]
    extends StationaryProcess μ α where
  /-- `T` is ergodic for `μ`. -/
  ergodic : Ergodic T μ

end InformationTheory.Shannon
