/-
  scripts/DepGraph.lean — 定理の依存グラフ (dot 形式) 生成

  起点となる declaration (定理 / 定義) の証明・型に現れる定数参照を辿り、
  推移的な依存グラフを Graphviz dot 形式で出力する。

  - **プロジェクト内** (`InformationTheory.*` で定義) の定理は再帰的に展開する。
  - **外部依存** (Mathlib / Lean core / Std 等) はノードとしてグラフに含めるが、
    その内部 (外部定理がさらに何に依存するか) は追わない (葉ノード)。
  - **コンパイラ生成の補助定義** (`_proof_` / `match_` / `recOn` / projection /
    notation 等) はデフォルトで畳み (passthrough)、人が書いた定理・定義だけが
    ノードになるようにする。`DEP_RAW=1` で補助定義も表示。
  - **デフォルトは証明本体 (value) のみ追う**。型シグネチャ由来の依存
    (型クラスインスタンス等のノイズ) は除外する。`DEP_WITH_TYPE=1` で型も含める。

  ## 実行 (環境変数で設定。通常は scripts/dep_graph.sh ラッパ経由)

    DEP_ROOT=<完全修飾名> [DEP_OUT=out.dot] [DEP_WITH_TYPE=1]
      [DEP_MAX_DEPTH=n] [DEP_RAW=1] lake env lean scripts/DepGraph.lean

  | env var          | 意味                                                       |
  |------------------|------------------------------------------------------------|
  | DEP_ROOT         | 起点 declaration の完全修飾名 (単一グラフモードで必須)      |
  | DEP_OUT          | 出力 dot ファイル (default: dep_graph.dot)                  |
  | DEP_WITH_TYPE    | set すると型シグネチャ依存も含める (default: 証明本体のみ)  |
  | DEP_MAX_DEPTH    | 内部依存の展開深さ上限 (default: 無制限)                    |
  | DEP_RAW          | set すると auto-gen 補助定義も畳まずノード化                |

  ## ランキングモード (entry point 限定の依存数ランキング)

    DEP_RANK=1 [DEP_TOP=n] [DEP_WITH_TYPE=1] lake env lean scripts/DepGraph.lean

  `@[entry_point]` でマークされた declaration を対象に、推移的依存数の多い順
  (= より複雑・難解な定理の順) に上位 n 件を出力する。通常は scripts/dep_rank.sh 経由。
  各行には参考値として `pf-lines` (自身＋プロジェクト内依存定理の証明行数合計、
  コメント・空行除く) を併記する。これはソートには影響しない。

  | env var          | 意味                                                       |
  |------------------|------------------------------------------------------------|
  | DEP_RANK         | set するとランキングモード (DEP_ROOT より優先)             |
  | DEP_TOP          | 上位何件を表示するか (default: 20)                          |
  | DEP_SORT         | ソート基準 total / internal / external (default: total)    |
-/
import Lean
import InformationTheory
import InformationTheory.Meta.EntryPoint

open Lean

namespace Tooling.DepGraph

/-- declaration が `InformationTheory/*.lean` で定義されたか (module path で判定、
    FindOrphans.lean 流儀)。 -/
def isInInformationTheory (env : Environment) (n : Name) : Bool :=
  match env.getModuleIdxFor? n with
  | none     => false
  | some idx =>
    let modName := env.allImportedModuleNames[idx.toNat]!
    (`InformationTheory : Name).isPrefixOf modName

/-- 名前の最終 component が Lean elaborator の自動生成 suffix か
    (FindOrphans.lean より)。`.recOn` / `.eq_1` / `.match_1` / `@[ext]` 生成等。 -/
def hasAutoGenSuffix (n : Name) : Bool :=
  match n with
  | .str _ s =>
    s == "recOn" || s == "casesOn" || s == "ctorIdx" || s == "congr_simp"
    || s == "ext" || s == "ext_iff" || s == "eq_def" || s == "injEq"
    || s == "noConfusion" || s == "noConfusionType" || s == "sizeOf_spec"
    || s == "brecOn" || s == "below" || s == "induct" || s == "fwd"
    || (s.startsWith "eq_" && (s.drop 3).all Char.isDigit)
    || s.startsWith "match_" || s.startsWith "proof_"
  | _ => false

/-- `notation` / `syntax` / `macro` 生成の declaration か。生成名は `«…»` escape
    を含むことで判定 (FindOrphans.lean より)。 -/
def isNotationName (n : Name) : Bool :=
  (toString n).any (· == '«')

/-- declaration が auto-generated (ctor / rec / projection / 派生 helper / notation /
    macro-scoped internal) か。これらはデフォルトで passthrough (ノード化せず畳む)。 -/
def isAutoGenerated (env : Environment) (n : Name) : Bool :=
  n.isInternal
  || isNotationName n
  || match env.find? n with
     | some (.ctorInfo _) => true
     | some (.recInfo _)  => true
     | _                  => (env.getProjectionFnInfo? n).isSome || hasAutoGenSuffix n

/-- declaration の所属モジュール名。 -/
def moduleOf (env : Environment) (n : Name) : Name :=
  match env.getModuleIdxFor? n with
  | none     => `unknown
  | some idx => env.allImportedModuleNames[idx.toNat]!

/-- グラフ生成の設定。 -/
structure Config where
  root        : Name
  out         : String
  includeType : Bool
  raw         : Bool
  maxDepth?   : Option Nat

/-- declaration の type / value Expr に直接出現する定数参照の集合。
    デフォルトは value (証明本体) のみ。`includeType` のとき型シグネチャも見る。 -/
def refsOf (env : Environment) (cfg : Config) (n : Name) : NameSet :=
  let collect (e : Expr) (acc : NameSet) : NameSet :=
    e.foldConsts acc (fun m s => s.insert m)
  let fromType (acc : NameSet) (t : Expr) : NameSet :=
    if cfg.includeType then collect t acc else acc
  match env.find? n with
  | some (.thmInfo v)    => collect v.value (fromType {} v.type)
  | some (.defnInfo v)   => collect v.value (fromType {} v.type)
  | some (.opaqueInfo v) => collect v.value (fromType {} v.type)
  | some (.axiomInfo v)  => fromType {} v.type
  | some (.ctorInfo v)   => fromType {} v.type
  | some (.inductInfo v) => fromType {} v.type
  | some (.recInfo v)    => fromType {} v.type
  | some (.quotInfo v)   => fromType {} v.type
  | none                 => {}

/-- passthrough 対象 (= 補助定義として畳む) か。`raw` のときは常に false
    (全ての参照をノード化)。 -/
def isThrough (env : Environment) (cfg : Config) (n : Name) : Bool :=
  !cfg.raw && isAutoGenerated env n

/-- `n` の「実体ノード」依存集合。`n` の直接参照のうち、passthrough 対象は
    その先を辿って (補助定義チェーンを畳んで) 実体ノードまで到達させる。
    自己参照 (再帰定義) は除外する。 -/
def realDepsOf (env : Environment) (cfg : Config) (n : Name) : NameSet := Id.run do
  let mut result    : NameSet := {}
  let mut throughSeen : NameSet := {}
  let mut stack     : List Name := (refsOf env cfg n).toList
  while !stack.isEmpty do
    let d := stack.head!
    stack := stack.tail!
    if d == n then
      pure ()          -- 自己参照は無視
    else if isThrough env cfg d then
      if !throughSeen.contains d then
        throughSeen := throughSeen.insert d
        stack := (refsOf env cfg d).toList ++ stack
    else
      result := result.insert d
  return result

/-- 走査の途中状態。`expanded` は cycle 防止用 (展開済ノード)、
    `adj` は隣接リスト (依存元 → 依存先集合)。 -/
structure GraphState where
  expanded : NameSet := {}
  adj      : Std.HashMap Name NameSet := {}

/-- `realDepsOf` のメモ化 (root に非依存なので全 root 走査で再利用できる)。
    ランキングモードで 800+ entry point を走らせる際の高速化に効く。 -/
def cachedRealDeps (env : Environment) (cfg : Config)
    (cache : IO.Ref (Std.HashMap Name NameSet)) (n : Name) : IO NameSet := do
  match (← cache.get).get? n with
  | some v => return v
  | none   =>
    let v := realDepsOf env cfg n
    cache.modify (·.insert n v)
    return v

/-- 起点 `n` から DFS で依存を辿る。プロジェクト内ノードは再帰展開、
    外部ノードは葉として隣接リストに残すのみ (展開しない)。
    `cache` は `realDepsOf` のメモ (単一グラフ用には fresh な ref を渡せばよい)。 -/
partial def expand (env : Environment) (cfg : Config)
    (cache : IO.Ref (Std.HashMap Name NameSet)) (ref : IO.Ref GraphState)
    (depth : Nat) (n : Name) : IO Unit := do
  if (← ref.get).expanded.contains n then return
  ref.modify fun s => { s with expanded := s.expanded.insert n }
  match cfg.maxDepth? with
  | some md => if depth ≥ md then return    -- 深さ上限で打ち切り (out-edge を出さない)
  | none    => pure ()
  for d in (← cachedRealDeps env cfg cache n).toList do
    if d == n then continue
    ref.modify fun s =>
      { s with adj := s.adj.insert n ((s.adj.getD n {}).insert d) }
    if isInInformationTheory env d then
      expand env cfg cache ref (depth + 1) d
    -- 外部依存はここで止める (葉ノード)

/-- グラフに現れる全ノード集合 (root + 隣接リストの key / value)。 -/
def nodeSet (root : Name) (st : GraphState) : NameSet := Id.run do
  let mut s : NameSet := {}
  s := s.insert root
  for (k, succs) in st.adj.toList do
    s := s.insert k
    for d in succs.toList do
      s := s.insert d
  return s

/-- dot 文字列内のノード名を escape (`"` と `\`)。 -/
def dotEscape (s : String) : String :=
  s.foldl (init := "") fun acc c =>
    match c with
    | '"'  => acc ++ "\\\""
    | '\\' => acc ++ "\\\\"
    | _    => acc.push c

/-- 走査結果を Graphviz dot 文字列に整形。
    root は強調、プロジェクト内ノードは塗りつぶし、外部ノードは破線で区別する。 -/
def render (env : Environment) (cfg : Config) (st : GraphState) : String := Id.run do
  let nodes := (nodeSet cfg.root st).toList.toArray.qsort (fun a b => a.toString < b.toString)
  let mut out : Array String := #[]
  out := out.push "digraph deps {"
  out := out.push "  rankdir=LR;"
  out := out.push "  graph [fontname=\"monospace\"];"
  out := out.push "  node [shape=box, style=rounded, fontname=\"monospace\", fontsize=10];"
  out := out.push ""
  out := out.push s!"  // root: {cfg.root}"
  out := out.push "  // 青: 起点 / 水色: プロジェクト内 / 破線: 外部 (Mathlib 等, 未展開)"
  for n in nodes do
    let id := dotEscape (toString n)
    let attr :=
      if n == cfg.root then
        "style=\"filled,bold\", fillcolor=\"#cfe8ff\", penwidth=2"
      else if isInInformationTheory env n then
        "style=filled, fillcolor=\"#eef6ff\""
      else
        "shape=note, style=dashed, color=\"#999999\", fontcolor=\"#555555\""
    out := out.push s!"  \"{id}\" [{attr}];"
  out := out.push ""
  let mut edges : Array (String × String) := #[]
  for (k, succs) in st.adj.toList do
    for d in succs.toList do
      edges := edges.push (toString k, toString d)
  let edgesSorted := edges.qsort (fun a b => a.1 ++ " " ++ a.2 < b.1 ++ " " ++ b.2)
  for (a, b) in edgesSorted do
    out := out.push s!"  \"{dotEscape a}\" -> \"{dotEscape b}\";"
  out := out.push "}"
  return "\n".intercalate out.toList ++ "\n"

/-! ## ランキングモード (entry point 限定の依存数集計)

    依存定理が多い定理ほど複雑・難解という想定で、`@[entry_point]` でマークされた
    declaration を対象に、推移的依存数 (= root を起点にした依存グラフのノード数 −1)
    を降順ランキングする。`realDepsOf` のメモを全 entry point で共有して高速化する。 -/

/-- declaration が `@[entry_point]` でマークされているか。 -/
def isEntryPoint (env : Environment) (n : Name) : Bool :=
  InformationTheory.Meta.entryPointAttr.hasTag env n

/-- ランキング 1 行分。`total = internal + external` (いずれも root 自身を除く)。
    `proofLines` は自身＋プロジェクト内依存定理の証明行数合計 (コメント除く・参考値、
    ソート非対象)。 -/
structure RankRow where
  name       : Name
  total      : Nat
  internal   : Nat
  external   : Nat
  proofLines : Nat
  deriving Inhabited

/-- 右詰めパディング。 -/
def padLeft (w : Nat) (s : String) : String :=
  if s.length ≥ w then s else ("".pushn ' ' (w - s.length)) ++ s

/-! ## 証明行数 (コメント除く) の参考集計

    各 entry point について、自身＋プロジェクト内依存定理の証明行数 (コメント・空行を
    除いたソース行) の合計を参考値として併記する。ランキングのソートには影響しない。
    overlap (where 補助定義など同一ソース行を複数 decl が共有する場合) は行単位の
    和集合で重複排除する。 -/

/-- module 名 → ソースファイルパス
    (`InformationTheory.Foo.Bar` → `InformationTheory/Foo/Bar.lean`)。
    dep_rank.sh はプロジェクトルートで実行するので相対パスで開ける。 -/
def srcPathOf (mod : Name) : System.FilePath :=
  (System.mkFilePath (mod.components.map (·.toString))).addExtension "lean"

/-- ソース 1 ファイル分の「各行が実コードを含むか」フラグ配列 (1-based 行 → 0-based index)。
    ブロックコメント (スラッシュ＋ハイフン、ネスト可) / 行コメント (ハイフン 2 連) /
    文字列・文字リテラルを char 単位で追い、コメント・空行を除いた実コード行だけ
    `true` にする。文字列内のコメント開始記号でブロックコメント深さが暴走しないよう
    文字列・文字を追跡する (近似: 識別子の prime と文字リテラルの区別はヒューリスティック)。 -/
def computeIsCode (content : String) : Array Bool := Id.run do
  let mut nest : Nat := 0          -- block comment ネスト深さ
  let mut inStr : Bool := false    -- "…" 文字列内か (行跨ぎ gap も追う)
  let mut result : Array Bool := #[]
  for line in content.splitOn "\n" do
    let cs := line.toList.toArray
    let n := cs.size
    let mut i := 0
    let mut hasCode := false
    let mut lineComment := false
    while i < n && !lineComment do
      let c := cs[i]!
      if inStr then
        if c == '\\' then i := i + 2
        else if c == '"' then inStr := false; i := i + 1
        else i := i + 1
      else if nest > 0 then
        if c == '-' && i + 1 < n && cs[i+1]! == '/' then nest := nest - 1; i := i + 2
        else if c == '/' && i + 1 < n && cs[i+1]! == '-' then nest := nest + 1; i := i + 2
        else i := i + 1
      else
        if c == '/' && i + 1 < n && cs[i+1]! == '-' then nest := nest + 1; i := i + 2
        else if c == '-' && i + 1 < n && cs[i+1]! == '-' then lineComment := true
        else if c == '"' then inStr := true; hasCode := true; i := i + 1
        else if c == '\'' then
          hasCode := true
          if i + 1 < n && cs[i+1]! == '\\' then
            -- escape 文字リテラル '\n' / '\'' / '«' 等: 閉じ ' まで飛ばす
            i := i + 2
            while i < n && cs[i]! != '\'' do i := i + 1
            i := i + 1
          else if i + 2 < n && cs[i+2]! == '\'' then i := i + 3   -- 'x' 形
          else i := i + 1                                          -- 識別子の prime
        else
          if !c.isWhitespace then hasCode := true
          i := i + 1
    result := result.push hasCode
  return result

/-- module の isCode 配列をキャッシュ付きで取得。ファイルが無ければ空配列。 -/
def getFileIsCode (cache : IO.Ref (Std.HashMap Name (Array Bool))) (mod : Name) :
    IO (Array Bool) := do
  match (← cache.get).get? mod with
  | some v => return v
  | none   =>
    let path := srcPathOf mod
    let v ← if (← path.pathExists) then
              pure (computeIsCode (← IO.FS.readFile path))
            else pure #[]
    cache.modify (·.insert mod v)
    return v

/-- declaration の (所属 module, 開始行, 終了行) をキャッシュ付きで取得。 -/
def getDeclLineRange (env : Environment)
    (cache : IO.Ref (Std.HashMap Name (Option (Name × Nat × Nat)))) (n : Name) :
    IO (Option (Name × Nat × Nat)) := do
  match (← cache.get).get? n with
  | some v => return v
  | none   =>
    let v := match Lean.declRangeExt.find? env n with
      | some dr => some (moduleOf env n, dr.range.pos.line, dr.range.endPos.line)
      | none    => none
    cache.modify (·.insert n v)
    return v

/-- 内部依存ノード集合 (root 自身含む) の証明行数合計 (コメント・空行除く)。
    同一ソース行を複数 decl が共有する場合は行単位の和集合で重複排除する。 -/
def proofLinesOf (env : Environment)
    (fileCache : IO.Ref (Std.HashMap Name (Array Bool)))
    (rangeCache : IO.Ref (Std.HashMap Name (Option (Name × Nat × Nat))))
    (internalNodes : List Name) : IO Nat := do
  let mut covered : Std.HashMap Name (Std.HashSet Nat) := {}
  for nd in internalNodes do
    match ← getDeclLineRange env rangeCache nd with
    | none => pure ()
    | some (mod, s, e) =>
      let mut lines := covered.getD mod Std.HashSet.emptyWithCapacity
      for ln in [s:e+1] do
        lines := lines.insert ln
      covered := covered.insert mod lines
  let mut total : Nat := 0
  for (mod, lines) in covered.toList do
    let isCode ← getFileIsCode fileCache mod
    for ln in lines.toList do
      if 1 ≤ ln && ln ≤ isCode.size && isCode[ln-1]! then
        total := total + 1
  return total

/-- 1 つの root の推移的依存数 (internal / external) と、自身＋プロジェクト内依存定理の
    証明行数合計 (コメント除く・参考値) を求める。依存数は root 自身を除く。 -/
def depStats (env : Environment) (cfg : Config)
    (cache : IO.Ref (Std.HashMap Name NameSet))
    (fileCache : IO.Ref (Std.HashMap Name (Array Bool)))
    (rangeCache : IO.Ref (Std.HashMap Name (Option (Name × Nat × Nat))))
    (root : Name) : IO (Nat × Nat × Nat) := do
  let ref ← IO.mkRef ({} : GraphState)
  expand env { cfg with root := root } cache ref 0 root
  let st ← ref.get
  let nodes := nodeSet root st
  let internalNodes := nodes.toList.filter (fun n => isInInformationTheory env n)
  let intCount := internalNodes.length
  -- proofLines は root 自身も内部ノードに含むので「自身の証明込み」になる。
  let proofLines ← proofLinesOf env fileCache rangeCache internalNodes
  -- root は internal 前提。internal/total から root 1 件を差し引く。
  return (intCount - 1, nodes.size - intCount, proofLines)

/-- ランキングのソートキー。`total` = 内部+外部、`internal` = プロジェクト内のみ
    (自前の補題積み上げの厚み)、`external` = 外部 (Mathlib 等) のみ。 -/
inductive SortKey where
  | total | internal | external
  deriving Inhabited, BEq

/-- 文字列 → SortKey (未知の値は total)。 -/
def SortKey.ofString : String → SortKey
  | "internal" => .internal
  | "external" => .external
  | _          => .total

def SortKey.label : SortKey → String
  | .total    => "total (内部+外部)"
  | .internal => "internal (プロジェクト内のみ)"
  | .external => "external (外部のみ)"

/-- entry point を全列挙し、依存数の降順に上位 `topN` を出力する。
    `sortKey` でソート基準 (total / internal / external) を選ぶ。 -/
def runRank (env : Environment) (cfg : Config) (topN : Nat) (sortKey : SortKey) : IO Unit := do
  let mut entries : Array Name := #[]
  for (n, _) in env.constants.toList do
    if isEntryPoint env n && isInInformationTheory env n then
      entries := entries.push n
  let cache ← IO.mkRef ({} : Std.HashMap Name NameSet)
  let fileCache ← IO.mkRef ({} : Std.HashMap Name (Array Bool))
  let rangeCache ← IO.mkRef ({} : Std.HashMap Name (Option (Name × Nat × Nat)))
  let mut rows : Array RankRow := #[]
  for ep in entries do
    let (intDeps, extDeps, pf) ← depStats env cfg cache fileCache rangeCache ep
    rows := rows.push { name := ep, total := intDeps + extDeps, internal := intDeps,
                        external := extDeps, proofLines := pf }
  let keyOf (r : RankRow) : Nat :=
    match sortKey with
    | .total => r.total | .internal => r.internal | .external => r.external
  let sorted := rows.qsort (fun a b =>
    if keyOf a == keyOf b then a.name.toString < b.name.toString else keyOf a > keyOf b)
  let typeNote := if cfg.includeType then "型シグネチャ込み" else "証明本体のみ"
  IO.println "==== InformationTheory 依存数ランキング (entry point 限定) ===="
  IO.println s!"  entry point 総数 : {entries.size}   表示 : 上位 {topN}   依存集計 : {typeNote}"
  IO.println s!"  ソート基準 : {sortKey.label}"
  IO.println "  依存数 = 推移的に到達する declaration 数 (root 自身を除く / 内部は再帰展開・外部は葉)"
  IO.println "  pf-lines = 自身＋プロジェクト内依存定理の証明行数合計 (コメント・空行除く・参考値、ソート非対象)"
  IO.println ""
  IO.println ("  " ++ padLeft 4 "rank" ++ " " ++ padLeft 7 "total" ++ " "
    ++ padLeft 7 "int" ++ " " ++ padLeft 7 "ext" ++ " " ++ padLeft 9 "pf-lines" ++ "   declaration")
  let shown := min topN sorted.size
  for i in [0:shown] do
    let r := sorted[i]!
    IO.println s!"  {padLeft 4 (toString (i+1))} {padLeft 7 (toString r.total)} {padLeft 7 (toString r.internal)} {padLeft 7 (toString r.external)} {padLeft 9 (toString r.proofLines)}   {r.name}"

end Tooling.DepGraph

/-- 環境変数が「非空に設定されている」か。空文字 (`export X=""`) は未設定扱い。 -/
private def envFlag (name : String) : IO Bool := do
  return ((← IO.getEnv name).getD "") ≠ ""

open Tooling.DepGraph in
#eval! show MetaM Unit from do
  let env ← getEnv
  -- ランキングモード (DEP_RANK set): entry point 限定で依存数の多い順に出力
  if (← envFlag "DEP_RANK") then
    let topN := ((← IO.getEnv "DEP_TOP").bind String.toNat?).getD 20
    let cfg : Config := {
      root        := .anonymous          -- runRank が entry point ごとに上書き
      out         := ""
      includeType := (← envFlag "DEP_WITH_TYPE")
      raw         := (← envFlag "DEP_RAW")
      maxDepth?   := (← IO.getEnv "DEP_MAX_DEPTH").bind String.toNat?
    }
    let sortKey := SortKey.ofString ((← IO.getEnv "DEP_SORT").getD "total")
    runRank env cfg topN sortKey
    return
  -- 単一グラフモード (DEP_ROOT で指定)
  let rootStr := (← IO.getEnv "DEP_ROOT").getD ""
  if rootStr.isEmpty then
    IO.eprintln "[DepGraph] DEP_ROOT が未設定です (例: DEP_ROOT=InformationTheory.Foo.bar)"
    IO.eprintln "  ランキングは DEP_RANK=1 [DEP_TOP=n] で実行できます。"
    return
  let root := rootStr.toName
  unless env.contains root do
    IO.eprintln s!"[DepGraph] 未知の declaration: {root}"
    IO.eprintln "  完全修飾名で指定してください (namespace を含む)。"
    return
  let cfg : Config := {
    root      := root
    out       := (← IO.getEnv "DEP_OUT").getD "dep_graph.dot"
    includeType := (← envFlag "DEP_WITH_TYPE")
    raw         := (← envFlag "DEP_RAW")
    maxDepth?   := (← IO.getEnv "DEP_MAX_DEPTH").bind String.toNat?
  }
  let cache ← IO.mkRef ({} : Std.HashMap Name NameSet)
  let ref ← IO.mkRef ({} : GraphState)
  expand env cfg cache ref 0 root
  let st ← ref.get
  IO.FS.writeFile cfg.out (render env cfg st)
  -- サマリ
  let nodes := nodeSet root st
  let nodeList := nodes.toList
  let internal := nodeList.filter (fun n => isInInformationTheory env n)
  let edgeCount := st.adj.toList.foldl (fun acc (_, s) => acc + s.size) 0
  IO.println s!"[DepGraph] wrote {cfg.out}"
  IO.println s!"  root         : {root}"
  IO.println s!"  nodes        : {nodes.size}  (内部 {internal.length} / 外部 {nodes.size - internal.length})"
  IO.println s!"  edges        : {edgeCount}"
  IO.println s!"  include-type : {cfg.includeType}   raw : {cfg.raw}   max-depth : {cfg.maxDepth?}"
  IO.println s!"  画像化: dot -Tsvg {cfg.out} -o out.svg  (Graphviz)"
