/-
  scripts/DepGraph.lean — 定理の依存グラフ (dot 形式) 生成

  起点となる declaration (定理 / 定義) の証明・型に現れる定数参照を辿り、
  推移的な依存グラフを Graphviz dot 形式で出力する。

  - **プロジェクト内** (`InformationTheory.*` で定義) の定理は再帰的に展開する。
  - **外部依存** (Mathlib / Lean core / Std 等) はノードとしてグラフに含めるが、
    その内部 (外部定理がさらに何に依存するか) は追わない (葉ノード)。
  - **コンパイラ生成の補助定義** (`_proof_` / `match_` / `recOn` / projection /
    notation 等) はデフォルトで畳み (passthrough)、人が書いた定理・定義だけが
    ノードになるようにする。`DEP_RAW=1` で補助定義も表示。

  ## 実行 (環境変数で設定。通常は scripts/dep_graph.sh ラッパ経由)

    DEP_ROOT=<完全修飾名> [DEP_OUT=out.dot] [DEP_PROOF_ONLY=1]
      [DEP_MAX_DEPTH=n] [DEP_RAW=1] lake env lean scripts/DepGraph.lean

  | env var          | 意味                                                       |
  |------------------|------------------------------------------------------------|
  | DEP_ROOT (必須)  | 起点 declaration の完全修飾名                               |
  | DEP_OUT          | 出力 dot ファイル (default: dep_graph.dot)                  |
  | DEP_PROOF_ONLY   | set すると証明本体 (value) のみ追う。型シグネチャ依存は除外 |
  | DEP_MAX_DEPTH    | 内部依存の展開深さ上限 (default: 無制限)                    |
  | DEP_RAW          | set すると auto-gen 補助定義も畳まずノード化                |
-/
import Lean
import InformationTheory

open Lean

namespace Tooling.DepGraph

/-- declaration が `InformationTheory/*.lean` で定義されたか (module path で判定、
    FindOrphans.lean 流儀)。 -/
def isInInformationTheory (env : Environment) (n : Name) : Bool :=
  match env.getModuleIdxFor? n with
  | none     => false
  | some idx =>
    let modName := env.allImportedModuleNames[idx.toNat]!
    (`InformationTheory : Name).isPrefixOf modName

/-- 名前の最終 component が Lean elaborator の自動生成 suffix か
    (FindOrphans.lean より)。`.recOn` / `.eq_1` / `.match_1` / `@[ext]` 生成等。 -/
def hasAutoGenSuffix (n : Name) : Bool :=
  match n with
  | .str _ s =>
    s == "recOn" || s == "casesOn" || s == "ctorIdx" || s == "congr_simp"
    || s == "ext" || s == "ext_iff" || s == "eq_def" || s == "injEq"
    || s == "noConfusion" || s == "noConfusionType" || s == "sizeOf_spec"
    || s == "brecOn" || s == "below" || s == "induct" || s == "fwd"
    || (s.startsWith "eq_" && (s.drop 3).all Char.isDigit)
    || s.startsWith "match_" || s.startsWith "proof_"
  | _ => false

/-- `notation` / `syntax` / `macro` 生成の declaration か。生成名は `«…»` escape
    を含むことで判定 (FindOrphans.lean より)。 -/
def isNotationName (n : Name) : Bool :=
  (toString n).any (· == '«')

/-- declaration が auto-generated (ctor / rec / projection / 派生 helper / notation /
    macro-scoped internal) か。これらはデフォルトで passthrough (ノード化せず畳む)。 -/
def isAutoGenerated (env : Environment) (n : Name) : Bool :=
  n.isInternal
  || isNotationName n
  || match env.find? n with
     | some (.ctorInfo _) => true
     | some (.recInfo _)  => true
     | _                  => (env.getProjectionFnInfo? n).isSome || hasAutoGenSuffix n

/-- declaration の所属モジュール名。 -/
def moduleOf (env : Environment) (n : Name) : Name :=
  match env.getModuleIdxFor? n with
  | none     => `unknown
  | some idx => env.allImportedModuleNames[idx.toNat]!

/-- グラフ生成の設定。 -/
structure Config where
  root      : Name
  out       : String
  proofOnly : Bool
  raw       : Bool
  maxDepth? : Option Nat

/-- declaration の type / value Expr に直接出現する定数参照の集合。
    `proofOnly` のときは value (証明本体) のみ見る。 -/
def refsOf (env : Environment) (cfg : Config) (n : Name) : NameSet :=
  let collect (e : Expr) (acc : NameSet) : NameSet :=
    e.foldConsts acc (fun m s => s.insert m)
  let fromType (acc : NameSet) (t : Expr) : NameSet :=
    if cfg.proofOnly then acc else collect t acc
  match env.find? n with
  | some (.thmInfo v)    => collect v.value (fromType {} v.type)
  | some (.defnInfo v)   => collect v.value (fromType {} v.type)
  | some (.opaqueInfo v) => collect v.value (fromType {} v.type)
  | some (.axiomInfo v)  => fromType {} v.type
  | some (.ctorInfo v)   => fromType {} v.type
  | some (.inductInfo v) => fromType {} v.type
  | some (.recInfo v)    => fromType {} v.type
  | some (.quotInfo v)   => fromType {} v.type
  | none                 => {}

/-- passthrough 対象 (= 補助定義として畳む) か。`raw` のときは常に false
    (全ての参照をノード化)。 -/
def isThrough (env : Environment) (cfg : Config) (n : Name) : Bool :=
  !cfg.raw && isAutoGenerated env n

/-- `n` の「実体ノード」依存集合。`n` の直接参照のうち、passthrough 対象は
    その先を辿って (補助定義チェーンを畳んで) 実体ノードまで到達させる。
    自己参照 (再帰定義) は除外する。 -/
def realDepsOf (env : Environment) (cfg : Config) (n : Name) : NameSet := Id.run do
  let mut result    : NameSet := {}
  let mut throughSeen : NameSet := {}
  let mut stack     : List Name := (refsOf env cfg n).toList
  while !stack.isEmpty do
    let d := stack.head!
    stack := stack.tail!
    if d == n then
      pure ()          -- 自己参照は無視
    else if isThrough env cfg d then
      if !throughSeen.contains d then
        throughSeen := throughSeen.insert d
        stack := (refsOf env cfg d).toList ++ stack
    else
      result := result.insert d
  return result

/-- 走査の途中状態。`expanded` は cycle 防止用 (展開済ノード)、
    `adj` は隣接リスト (依存元 → 依存先集合)。 -/
structure GraphState where
  expanded : NameSet := {}
  adj      : Std.HashMap Name NameSet := {}

/-- 起点 `n` から DFS で依存を辿る。プロジェクト内ノードは再帰展開、
    外部ノードは葉として隣接リストに残すのみ (展開しない)。 -/
partial def expand (env : Environment) (cfg : Config) (ref : IO.Ref GraphState)
    (depth : Nat) (n : Name) : IO Unit := do
  if (← ref.get).expanded.contains n then return
  ref.modify fun s => { s with expanded := s.expanded.insert n }
  match cfg.maxDepth? with
  | some md => if depth ≥ md then return    -- 深さ上限で打ち切り (out-edge を出さない)
  | none    => pure ()
  for d in (realDepsOf env cfg n).toList do
    if d == n then continue
    ref.modify fun s =>
      { s with adj := s.adj.insert n ((s.adj.getD n {}).insert d) }
    if isInInformationTheory env d then
      expand env cfg ref (depth + 1) d
    -- 外部依存はここで止める (葉ノード)

/-- グラフに現れる全ノード集合 (root + 隣接リストの key / value)。 -/
def nodeSet (root : Name) (st : GraphState) : NameSet := Id.run do
  let mut s : NameSet := {}
  s := s.insert root
  for (k, succs) in st.adj.toList do
    s := s.insert k
    for d in succs.toList do
      s := s.insert d
  return s

/-- dot 文字列内のノード名を escape (`"` と `\`)。 -/
def dotEscape (s : String) : String :=
  s.foldl (init := "") fun acc c =>
    match c with
    | '"'  => acc ++ "\\\""
    | '\\' => acc ++ "\\\\"
    | _    => acc.push c

/-- 走査結果を Graphviz dot 文字列に整形。
    root は強調、プロジェクト内ノードは塗りつぶし、外部ノードは破線で区別する。 -/
def render (env : Environment) (cfg : Config) (st : GraphState) : String := Id.run do
  let nodes := (nodeSet cfg.root st).toList.toArray.qsort (fun a b => a.toString < b.toString)
  let mut out : Array String := #[]
  out := out.push "digraph deps {"
  out := out.push "  rankdir=LR;"
  out := out.push "  graph [fontname=\"monospace\"];"
  out := out.push "  node [shape=box, style=rounded, fontname=\"monospace\", fontsize=10];"
  out := out.push ""
  out := out.push s!"  // root: {cfg.root}"
  out := out.push "  // 青: 起点 / 水色: プロジェクト内 / 破線: 外部 (Mathlib 等, 未展開)"
  for n in nodes do
    let id := dotEscape (toString n)
    let attr :=
      if n == cfg.root then
        "style=\"filled,bold\", fillcolor=\"#cfe8ff\", penwidth=2"
      else if isInInformationTheory env n then
        "style=filled, fillcolor=\"#eef6ff\""
      else
        "shape=note, style=dashed, color=\"#999999\", fontcolor=\"#555555\""
    out := out.push s!"  \"{id}\" [{attr}];"
  out := out.push ""
  let mut edges : Array (String × String) := #[]
  for (k, succs) in st.adj.toList do
    for d in succs.toList do
      edges := edges.push (toString k, toString d)
  let edgesSorted := edges.qsort (fun a b => a.1 ++ " " ++ a.2 < b.1 ++ " " ++ b.2)
  for (a, b) in edgesSorted do
    out := out.push s!"  \"{dotEscape a}\" -> \"{dotEscape b}\";"
  out := out.push "}"
  return "\n".intercalate out.toList ++ "\n"

end Tooling.DepGraph

/-- 環境変数が「非空に設定されている」か。空文字 (`export X=""`) は未設定扱い。 -/
private def envFlag (name : String) : IO Bool := do
  return ((← IO.getEnv name).getD "") ≠ ""

open Tooling.DepGraph in
#eval! show MetaM Unit from do
  let env ← getEnv
  let rootStr := (← IO.getEnv "DEP_ROOT").getD ""
  if rootStr.isEmpty then
    IO.eprintln "[DepGraph] DEP_ROOT が未設定です (例: DEP_ROOT=InformationTheory.Foo.bar)"
    return
  let root := rootStr.toName
  unless env.contains root do
    IO.eprintln s!"[DepGraph] 未知の declaration: {root}"
    IO.eprintln "  完全修飾名で指定してください (namespace を含む)。"
    return
  let cfg : Config := {
    root      := root
    out       := (← IO.getEnv "DEP_OUT").getD "dep_graph.dot"
    proofOnly := (← envFlag "DEP_PROOF_ONLY")
    raw       := (← envFlag "DEP_RAW")
    maxDepth? := (← IO.getEnv "DEP_MAX_DEPTH").bind String.toNat?
  }
  let ref ← IO.mkRef ({} : GraphState)
  expand env cfg ref 0 root
  let st ← ref.get
  IO.FS.writeFile cfg.out (render env cfg st)
  -- サマリ
  let nodes := nodeSet root st
  let nodeList := nodes.toList
  let internal := nodeList.filter (fun n => isInInformationTheory env n)
  let edgeCount := st.adj.toList.foldl (fun acc (_, s) => acc + s.size) 0
  IO.println s!"[DepGraph] wrote {cfg.out}"
  IO.println s!"  root         : {root}"
  IO.println s!"  nodes        : {nodes.size}  (内部 {internal.length} / 外部 {nodes.size - internal.length})"
  IO.println s!"  edges        : {edgeCount}"
  IO.println s!"  proof-only   : {cfg.proofOnly}   raw : {cfg.raw}   max-depth : {cfg.maxDepth?}"
  IO.println s!"  画像化: dot -Tsvg {cfg.out} -o out.svg  (Graphviz)"
