-- This module serves as the root of the `Common2026` library.
-- Import modules here that should be built as part of `lake build`.
-- 入試系 (Common2026/Exam/) は完成済みのため列挙から外している。
-- 個別検証は `lake env lean Common2026/Exam/...` または `lake build Common2026.Exam.<...>` で行う。

-- Fano 不等式
import Common2026.Fano
import Common2026.Fano.Entropy
import Common2026.Fano.BinaryJensen
import Common2026.Fano.CondEntropy
import Common2026.Fano.Core
import Common2026.Fano.DPI
import Common2026.Fano.Measure
-- Shannon converse (Phase 4)
import Common2026.Shannon.MutualInfo
import Common2026.Shannon.DPI
import Common2026.Shannon.Bridge
import Common2026.Shannon.CondMutualInfo
import Common2026.Shannon.Converse
import Common2026.Shannon.Entropy
import Common2026.Shannon.SlepianWolf
import Common2026.Shannon.SlepianWolfAchievability
import Common2026.Shannon.SlepianWolfBinning
import Common2026.Shannon.SlepianWolfConditionalTypicalSlice
import Common2026.Shannon.SlepianWolfFullRateRegion
import Common2026.Shannon.Pi
import Common2026.Shannon.Han
import Common2026.Shannon.HanD
import Common2026.Shannon.HanDAverage
import Common2026.Shannon.HanDShearer
import Common2026.Shannon.LoomisWhitney
import Common2026.Shannon.BrascampLieb
import Common2026.Shannon.HypercubeEdgeBoundary
import Common2026.Shannon.HypercubeEdgeBoundarySharp
import Common2026.Polymatroid.Basic
import Common2026.Shannon.Polymatroid
import Common2026.Shannon.AEP
import Common2026.Shannon.AEPRate
import Common2026.Shannon.Stein
import Common2026.Shannon.StrongStein
import Common2026.Shannon.MaxEntropy
import Common2026.Shannon.Pinsker
import Common2026.Shannon.PinskerSharp
import Common2026.Shannon.MIChainRule
import Common2026.Shannon.ChannelCoding
import Common2026.Shannon.IIDProductInput
import Common2026.Shannon.IIDProductInputJoint
import Common2026.Shannon.ChannelCodingAchievability
import Common2026.Shannon.ChannelCodingConverse
import Common2026.Shannon.ChannelCodingConverseGeneral
import Common2026.Shannon.ChannelCodingConverseGeneralComplete
import Common2026.Shannon.ChannelCodingStrongConverse
import Common2026.Shannon.ChannelCodingFeedback
import Common2026.Shannon.ChannelCodingFeedbackComplete
import Common2026.Shannon.ChannelCodingShannonTheorem
import Common2026.Shannon.ChannelCodingShannonTheoremGeneral
import Common2026.Shannon.ChannelCodingShannonTheoremFull
import Common2026.Shannon.RateDistortionConverse
import Common2026.Shannon.RateDistortionConverseMonotone
import Common2026.Shannon.RateDistortionConvexity
import Common2026.Shannon.RateDistortionConvexityDischarge
import Common2026.Shannon.RateDistortionAchievability
import Common2026.Shannon.RateDistortionAchievabilityPhaseB
import Common2026.Shannon.RateDistortionAchievabilityPhaseC
import Common2026.Shannon.RateDistortionAchievabilityPhaseD
import Common2026.Shannon.RateDistortionAchievabilityPhaseE
import Common2026.Shannon.RateDistortionConverseNLetter
import Common2026.Shannon.Sanov
import Common2026.Shannon.SanovLDP
import Common2026.Shannon.KLDivContinuous
import Common2026.Shannon.SanovLDPEquality
import Common2026.Shannon.TypeClassLowerBound
import Common2026.Shannon.StrongTypicality
import Common2026.Shannon.ShannonCode
import Common2026.Shannon.ShannonCodeKraftReverse
import Common2026.Shannon.CsiszarProjection
import Common2026.Shannon.DifferentialEntropy
import Common2026.Shannon.Stationary
import Common2026.Shannon.EntropyRate
import Common2026.Shannon.ShannonMcMillanBreiman
