#!/usr/bin/env -S deno run -A
// gen_readme_table.ts — keep the "Formalized results" table in README.md reproducible.
//
// 手書きの表は rename / move / scope-out で黙って drift する (README が公開で嘘をつく)。
// 再現性の核心は「curation だけ手で (docs/readme-theorems.txt)、表は生成物、--check で
// 『生成結果 == コミット済み』を保証」。パスはマニフェストに書かず毎回コードから解決するので
// ファイル移動は自動追従、true rename/delete だけが落ちる。
//
// 説明文 (Statement 列) も生成物: 各定理の **docstring 先頭**から要約する。docstring は
// コード側の SoT (docs/rules/docstrings.md) なので、定理の意味が変わればそこが直り、表は
// 次の --write で自動追従する。README 用に別の説明文を手書きすると同じ drift が再発するため、
// 手書きはマニフェストの override (`NAME | 説明`) に限り、docstring が読みにくいときだけ使う。
//
// 純 Deno でコード走査 (rg はシェル関数で spawn 不可 — plan_lint.ts と同方針、外部 cmd なし)。
//
// Usage:
//   deno run -A scripts/gen_readme_table.ts            # = --check
//   deno run -A scripts/gen_readme_table.ts --check    # 検証のみ。drift で exit 1 (CI 用)
//   deno run -A scripts/gen_readme_table.ts --write    # README のマーカー間に表を再生成
//   deno run -A scripts/gen_readme_table.ts --hook     # pre-commit 用: WARN のみ, 常に exit 0
//
// 誠実性 (README の 2 主張を別々に検証):
//   (1) listed 定理はすべて complete: 定理表に載る定理が属するファイルは strict 0-sorry。
//       listed 定理ファイルに実 sorry があれば documented であっても fail。
//   (2) ライブラリ全体は documented Mathlib 壁のみ許容: 実 sorry は必ず `@residual(wall:<slug>)`
//       タグを伴う (プロジェクト規約 = pre-commit hook が強制)。タグ無しの実 sorry は fail、
//       タグ付き (かつ listed でない) 壁は許容し info 報告。独自 axiom=0 は従来どおり必須。
//   Mathlib は sorry-free なので、listed 定理ファイルが 0-sorry である限り列挙定理は構造的に
//   sorryAx に依存しえず標準 3 公理のみ。「実 sorry」は stripComments 後に残る sorry トークン
//   (散文の "sorry-free" 等は除外)、壁タグ検出は strip 前の生テキスト。
//   説明文側の誠実性: 監査ナラティブ (`@audit:` / `sorryAx-free` / `#print axioms` …) は
//   README に出さず、そこで切る。要約が途中で切れた場合は末尾に `…` を付け、省略を明示する。

const MANIFEST = "docs/readme-theorems.txt";
const README = "README.md";
const CODE_ROOT = "InformationTheory";
const START_MARK = "<!-- THEOREMS:START";
const END_MARK = "<!-- THEOREMS:END -->";
const START_LINE =
  "<!-- THEOREMS:START — generated by scripts/gen_readme_table.ts from docs/readme-theorems.txt; do not edit by hand -->";

const mode = Deno.args.includes("--write")
  ? "write"
  : Deno.args.includes("--hook")
  ? "hook"
  : "check";

// ── manifest ─────────────────────────────────────────────────────────────────

// A result is 'NAME', optionally '@ <path-substring>' to disambiguate same-named decls,
// optionally '| <statement>' to override the docstring-derived summary (used only when the
// docstring reads badly out of context). e.g. 'entropy_le_log_card @ MaxEntropy/Basic'.
type Result = { name: string; note?: string; pathHint?: string };
type Chapter = { num: string; title: string; results: Result[] };

function parseManifest(text: string): Chapter[] {
  const chapters: Chapter[] = [];
  let cur: Chapter | null = null;
  for (const raw of text.split("\n")) {
    const line = raw.replace(/\s+$/, "");
    if (line === "" || line.trimStart().startsWith("#")) continue;
    const ch = line.match(/^@\s*([^|]+?)\s*\|\s*(.+)$/);
    if (ch && /^@\s*\d/.test(line)) {
      cur = { num: ch[1].trim(), title: ch[2].trim(), results: [] };
      chapters.push(cur);
      continue;
    }
    if (!cur) throw new Error(`manifest: entry before any '@ <ch> | <title>': ${line}`);
    // Only the FIRST '|' separates the name from the override — the override itself is
    // markdown prose and routinely contains '|' (set-builder bars, cardinalities).
    const bar = line.indexOf("|");
    const head = (bar >= 0 ? line.slice(0, bar) : line).trim();
    const note = bar >= 0 ? line.slice(bar + 1).trim() : undefined;
    if (note === "") throw new Error(`manifest: empty override after '|': ${line}`);
    const hm = head.match(/^(\S+?)(?:\s+@\s*(\S+))?$/);
    if (!hm) throw new Error(`manifest: cannot parse line: ${line}`);
    cur.results.push({ name: hm[1], note, pathHint: hm[2] });
  }
  return chapters;
}

// ── code scan (pure Deno) ────────────────────────────────────────────────────

// Lean のコメント (行 -- / ネスト可ブロック /- -/、doc /-- -/ 含む) を空白に潰す。改行は保つ
// (行ベース正規表現のため)。pre-commit hook の strip_lean_comments と同じ意図。
function stripComments(src: string): string {
  let out = "";
  let depth = 0;
  for (let i = 0, n = src.length; i < n;) {
    const two = src.substr(i, 2);
    if (depth > 0) {
      if (two === "-/") { depth--; i += 2; continue; }
      if (two === "/-") { depth++; i += 2; continue; }
      out += src[i] === "\n" ? "\n" : " ";
      i++;
      continue;
    }
    if (two === "/-") { depth++; i += 2; continue; }
    if (two === "--") { while (i < n && src[i] !== "\n") i++; continue; }
    out += src[i];
    i++;
  }
  return out;
}

// Name captures a full Lean identifier: Unicode letters/digits incl. subscripts (₂), primes,
// !/?. The 'u' flag + \p{L}\p{N} is essential — a plain \w would truncate `foo₂` to `foo`
// and manufacture false ambiguities/resolutions.
const IDENT = "[\\p{L}_][\\p{L}\\p{N}_'!?.]*";
const DECL_KW = "(?:theorem|lemma|def|abbrev|structure|inductive|class|instance|opaque)";
const MODIFIERS = "(?:(?:noncomputable|private|protected|scoped|local|partial|unsafe|mutual)[ \\t]+)*";
const DECL_RE = new RegExp(
  `^[ \\t]*(?:@\\[[^\\]]*\\][ \\t]*)*${MODIFIERS}(${DECL_KW})[ \\t]+(?:@\\[[^\\]]*\\][ \\t]*)*(${IDENT})`,
  "gmu",
);
// A doc comment `/-- … -/` binds to the next declaration, possibly across attribute lines
// (`@[entry_point]`) and `… in` prefixes (`omit … in`, `set_option … in`). A blank line in
// between is *not* allowed, so an orphan doc comment never captures an unrelated decl.
const DOC_RE = new RegExp(
  `/--([\\s\\S]*?)-/[ \\t]*\\n?` +
    `((?:[ \\t]*(?:@\\[[^\\]]*\\]|omit[^\\n]*\\bin|set_option[^\\n]*\\bin|attribute[^\\n]*)[ \\t]*\\n)*)` +
    `[ \\t]*${MODIFIERS}${DECL_KW}[ \\t]+(${IDENT})`,
  "gmu",
);
const SORRY_RE = /\bsorry\b/g;
const AXIOM_RE = /^[ \t]*axiom[ \t]/gm;
// A documented Mathlib wall carries a `@residual(wall:<slug>)` tag (project convention,
// enforced by the pre-commit hook). The tag lives in a comment, so it is detected on the
// RAW text, before stripComments. Everything else with a real sorry is undocumented → fail.
const WALL_TAG = "@residual(wall:";

type Index = {
  decls: Map<string, string[]>; // name -> repo-relative file paths
  docs: Map<string, string>; // `${name} ${path}` -> raw docstring body
  // Library-wide totals published in the README. All four are recounted on every run —
  // a hand-kept figure goes stale on the next commit and --check cannot notice.
  modules: number; // .lean files under CODE_ROOT
  proofDecls: number; // theorem + lemma
  otherDecls: number; // def / abbrev / structure / inductive / class / instance / opaque
  codeLines: number; // non-blank lines after comments are stripped
  sorryCount: number; // real sorry tokens (0 unless a documented wall is open)
  axiomCount: number; // custom axiom declarations (any is a hard failure)
  documentedWallFiles: string[]; // real sorry + a `@residual(wall:` tag → tolerated
  undocumentedSorryFiles: string[]; // real sorry, no wall tag → always fail
  axiomFiles: string[];
};

async function* walkLean(dir: string): AsyncGenerator<string> {
  for await (const e of Deno.readDir(dir)) {
    const p = `${dir}/${e.name}`;
    if (e.isDirectory) yield* walkLean(p);
    else if (e.isFile && p.endsWith(".lean")) yield p;
  }
}

async function buildIndex(): Promise<Index> {
  const decls = new Map<string, string[]>();
  const docs = new Map<string, string>();
  const documentedWallFiles: string[] = [];
  const undocumentedSorryFiles: string[] = [];
  const axiomFiles: string[] = [];
  let modules = 0;
  let proofDecls = 0;
  let otherDecls = 0;
  let codeLines = 0;
  let sorryCount = 0;
  let axiomCount = 0;
  for await (const path of walkLean(CODE_ROOT)) {
    modules++;
    const raw = await Deno.readTextFile(path);
    const code = stripComments(raw);
    codeLines += code.split("\n").filter((l) => l.trim() !== "").length;
    sorryCount += (code.match(SORRY_RE) ?? []).length;
    axiomCount += (code.match(AXIOM_RE) ?? []).length;
    for (const m of code.matchAll(DECL_RE)) {
      const [, kind, name] = m;
      if (kind === "theorem" || kind === "lemma") proofDecls++;
      else otherDecls++;
      const arr = decls.get(name);
      if (arr) { if (!arr.includes(path)) arr.push(path); }
      else decls.set(name, [path]);
    }
    // Docstrings are read from the RAW text (stripComments erases them by construction).
    for (const m of raw.matchAll(DOC_RE)) {
      const key = `${m[3]} ${path}`;
      if (!docs.has(key)) docs.set(key, m[1]);
    }
    if (SORRY_RE.test(code)) {
      // A real sorry (survives stripComments). Documented iff the raw text carries a
      // `@residual(wall:` tag (which lives in a comment, hence checked on raw, not code).
      if (raw.includes(WALL_TAG)) documentedWallFiles.push(path);
      else undocumentedSorryFiles.push(path);
    }
    SORRY_RE.lastIndex = 0;
    if (AXIOM_RE.test(code)) axiomFiles.push(path);
    AXIOM_RE.lastIndex = 0;
  }
  return {
    decls,
    docs,
    modules,
    proofDecls,
    otherDecls,
    codeLines,
    sorryCount,
    axiomCount,
    documentedWallFiles,
    undocumentedSorryFiles,
    axiomFiles,
  };
}

// ── docstring → statement summary ────────────────────────────────────────────

// Everything from here on is audit bookkeeping / cross-reference / proof recipe, not the
// statement: the summary stops at the first marker. Keeping `@audit:` and `sorryAx-free`
// out of the README is deliberate — process narration is git's job, not the shop window's.
const STOP_MARKERS = [
  "@audit:",
  "@residual(",
  "sorryAx-free",
  "`sorryAx`-free",
  "#print axioms",
  "See also",
  "References:",
  "Proof:",
  "$$", // display math renders badly inside a table cell
];

// A sentence opening with one of these recites the proof, not the statement. The summary
// stops there: how it is proved is what the linked source is for.
const RECIPE_OPENERS = [
  "Proof",
  "The proof",
  "Genuine proof",
  "Reduces to",
  "Routes through",
  "The body is assembled",
];

const MAX_SENTENCES = 3;
const MAX_CHARS = 400; // hard budget for the whole summary
const EXTEND_TO = 400; // a further sentence is kept only if the total stays within this
const MIN_CHARS = 140; // below this the next sentence is taken even if it must be cut short

// Sentence boundary: '.', '?' or '!' followed by whitespace and an opening character of the
// next sentence. Version numbers ("Thm 14.3.1") keep their dots because those are not
// followed by whitespace; abbreviations ("e.g. foo") are safe because a lowercase letter
// does not open a sentence here.
const SENTENCE_SPLIT = /(?<=[.?!])\s+(?=[A-Z*`([\p{Lu}])/u;

// Truncation must not leave a code span or a bold run open — an unbalanced marker bleeds
// into the rest of the cell. Cut back to the last unpaired one instead.
function closeMarkup(text: string): string {
  let out = text;
  for (const marker of ["`", "**"]) {
    const n = out.split(marker).length - 1;
    if (n % 2 === 1) out = out.slice(0, out.lastIndexOf(marker));
  }
  return out;
}

function trimTail(text: string): string {
  return text.replace(/[\s,;:—-]+$/u, "");
}

function ellipsize(text: string, budget: number): string {
  if (text.length <= budget) return text;
  const cut = text.lastIndexOf(" ", budget);
  return trimTail(closeMarkup(text.slice(0, cut > 0 ? cut : budget))) + " …";
}

function summarizeDocstring(doc: string): string {
  // Fenced blocks become inline code — a ``` block inside a table cell breaks the row.
  let s = doc.replace(/```+([\s\S]*?)```+/g, (_m, body: string) => "`" + body.trim() + "`");
  // Bullet markers only make sense across line breaks; inline they read as stray asterisks.
  s = s.replace(/^[ \t]*[*-][ \t]+/gm, "· ");
  s = s.replace(/\s+/g, " ").trim();
  for (const marker of STOP_MARKERS) {
    const i = s.indexOf(marker);
    if (i >= 0) s = s.slice(0, i);
  }
  s = trimTail(s.trim());
  if (s === "") return "";

  const sentences: string[] = [];
  for (const sentence of s.split(SENTENCE_SPLIT)) {
    if (sentences.length > 0 && RECIPE_OPENERS.some((p) => sentence.startsWith(p))) break;
    sentences.push(sentence);
  }

  let out = sentences[0];
  for (let i = 1; i < sentences.length && i < MAX_SENTENCES; i++) {
    const next = `${out} ${sentences[i]}`;
    // A summary too short to carry the statement takes the next sentence anyway, cut short.
    if (next.length > EXTEND_TO && out.length >= MIN_CHARS) break;
    out = next;
    if (out.length > EXTEND_TO) break;
  }
  return ellipsize(out.trim(), MAX_CHARS);
}

// GFM table cells: a raw '|' ends the cell — even inside a code span — so it must be
// escaped. Backslash-escaping is the only form GitHub honours there.
function cell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

// ── resolution ───────────────────────────────────────────────────────────────

type Resolved = { r: Result; path: string; statement: string };

function resolve(ch: Chapter, r: Result, idx: Index, errs: string[]): Resolved {
  let sites = idx.decls.get(r.name) ?? [];
  if (r.pathHint) sites = sites.filter((p) => p.includes(r.pathHint!));
  let path: string;
  if (sites.length === 0) {
    const hint = r.pathHint ? ` matching '@ ${r.pathHint}'` : "";
    errs.push(`Ch.${ch.num}: '${r.name}'${hint} not found in ${CODE_ROOT}/ (renamed or deleted?)`);
    path = "#";
  } else if (sites.length > 1) {
    errs.push(`Ch.${ch.num}: '${r.name}' is ambiguous (${sites.length} decls): ${sites.join(", ")} — add '@ <path-substring>' in the manifest`);
    path = sites[0];
  } else {
    path = sites[0];
  }
  // A manifest note overrides the docstring — curation wins where the docstring reads
  // badly out of context. Otherwise the docstring is the single source for the wording.
  const doc = idx.docs.get(`${r.name} ${path}`);
  const statement = r.note ?? (doc ? summarizeDocstring(doc) : "");
  if (statement === "" && path !== "#") {
    errs.push(`Ch.${ch.num}: '${r.name}' (${path}) has no usable docstring — document the declaration, or supply an override with '${r.name} | <statement>' in the manifest`);
  }
  return { r, path, statement };
}

// The set of files that a README-listed theorem resolves to. Every listed result must be
// complete, so a real sorry in one of these files is a hard fail even when documented.
function listedTheoremFiles(resolved: Resolved[]): Set<string> {
  return new Set(resolved.map((x) => x.path).filter((p) => p !== "#"));
}

// ── render ───────────────────────────────────────────────────────────────────

// The library totals are counted, never typed in: a hand-kept number goes stale on the very
// next commit, and --check would have no way to notice.
function renderTotals(idx: Index, listed: number): string {
  const n = (x: number) => x.toLocaleString("en-US");
  // An open wall is reported as the count it is, not rounded away — the sentence has to
  // stay true the day a `sorry` reappears, without anyone remembering to rewrite it.
  const honesty = idx.sorryCount === 0
    ? `**0 \`sorry\`** and **${n(idx.axiomCount)} custom axioms**`
    : `**${n(idx.sorryCount)} \`sorry\`**, every one under a documented \`@residual(wall:…)\` tag, ` +
      `and **${n(idx.axiomCount)} custom axioms**`;
  return `Library totals, recounted on every regeneration: **${n(idx.proofDecls)} theorems and ` +
    `lemmas**, **${n(idx.otherDecls)} definitions** and **${n(idx.codeLines)} lines of Lean** ` +
    `(non-blank, comments excluded) across **${n(idx.modules)} modules**, with ${honesty}. ` +
    `The ${n(listed)} results below are the curated selection.`;
}

function renderTable(chapters: Chapter[], byChapter: Map<Chapter, Resolved[]>, totals: string): string {
  const blocks: string[] = [totals];
  for (const ch of chapters) {
    const rows = [
      `**Ch. ${ch.num} — ${ch.title}**`,
      "",
      "| Result | Statement |",
      "|--------|-----------|",
    ];
    for (const x of byChapter.get(ch) ?? []) {
      rows.push(`| [\`${x.r.name}\`](${x.path}) | ${cell(x.statement)} |`);
    }
    blocks.push(rows.join("\n"));
  }
  return blocks.join("\n\n");
}

function spliceReadme(readme: string, table: string): string {
  const lines = readme.split("\n");
  const s = lines.findIndex((l) => l.includes(START_MARK));
  const e = lines.findIndex((l) => l.includes(END_MARK));
  if (s === -1 || e === -1 || e < s) {
    throw new Error(`${README}: markers ${START_MARK} … ${END_MARK} not found (add them around the table first)`);
  }
  const before = lines.slice(0, s);
  const after = lines.slice(e + 1);
  return [...before, START_LINE, table, END_MARK, ...after].join("\n");
}

function currentTable(readme: string): string | null {
  const lines = readme.split("\n");
  const s = lines.findIndex((l) => l.includes(START_MARK));
  const e = lines.findIndex((l) => l.includes(END_MARK));
  if (s === -1 || e === -1 || e < s) return null;
  return lines.slice(s + 1, e).join("\n").replace(/\s+$/, "");
}

// ── main ─────────────────────────────────────────────────────────────────────

const chapters = parseManifest(await Deno.readTextFile(MANIFEST));
const idx = await buildIndex();
const errs: string[] = [];
const byChapter = new Map<Chapter, Resolved[]>();
const allResolved: Resolved[] = [];
for (const ch of chapters) {
  const rs = ch.results.map((r) => resolve(ch, r, idx, errs));
  byChapter.set(ch, rs);
  allResolved.push(...rs);
}
const table = renderTable(chapters, byChapter, renderTotals(idx, allResolved.length));

// honesty — the README publishes two distinct claims, checked separately:
//   (1) every *listed* result is complete: no sorry in a listed-theorem file, ever;
//   (2) the library as a whole carries only *documented* Mathlib walls: any real sorry
//       must sit under a `@residual(wall:<slug>)` tag (undocumented sorry → fail).
const listedFiles = listedTheoremFiles(allResolved);

// (a) any real sorry without a wall tag → fail.
if (idx.undocumentedSorryFiles.length > 0) {
  errs.push(`honesty: ${idx.undocumentedSorryFiles.length} file(s) contain a real 'sorry' with no @residual(wall:…) tag: ${idx.undocumentedSorryFiles.join(", ")}`);
}
// (b) any real sorry (documented or not) inside a README-listed result's file → fail:
//     "every result listed below is complete" must stay true.
const listedWithSorry = [...idx.documentedWallFiles, ...idx.undocumentedSorryFiles]
  .filter((p) => listedFiles.has(p));
if (listedWithSorry.length > 0) {
  errs.push(`honesty: ${listedWithSorry.length} README-listed result file(s) contain a real 'sorry' — every listed result must be complete: ${listedWithSorry.join(", ")}`);
}
// (c) documented walls outside any listed file are tolerated (reported as info below).
const infoWallFiles = idx.documentedWallFiles.filter((p) => !listedFiles.has(p));

if (idx.axiomFiles.length > 0) {
  errs.push(`honesty: ${idx.axiomFiles.length} file(s) declare a custom 'axiom' — README claims none: ${idx.axiomFiles.join(", ")}`);
}

const readme = await Deno.readTextFile(README);

if (mode === "write") {
  if (errs.length) {
    console.error("✗ refusing to write — fix these first:\n  " + errs.join("\n  "));
    Deno.exit(1);
  }
  const out = spliceReadme(readme, table);
  if (out !== readme) {
    await Deno.writeTextFile(README, out);
    console.log("✓ README table regenerated.");
  } else {
    console.log("✓ README table already up to date.");
  }
  Deno.exit(0);
}

// check / hook
const stale = currentTable(readme) !== table.replace(/\s+$/, "");
if (stale && !errs.some((e) => e.startsWith("Ch."))) {
  errs.push("README table is out of date with the manifest/code — run: deno run -A scripts/gen_readme_table.ts --write");
}

if (infoWallFiles.length > 0) {
  console.log(`ℹ ${infoWallFiles.length} documented wall(s) (real 'sorry' + @residual(wall:…), not among listed results): ${infoWallFiles.join(", ")}`);
}

if (errs.length === 0) {
  const overrides = allResolved.filter((x) => x.r.note !== undefined).length;
  console.log(`✓ README table in sync — ${chapters.length} chapters, ${allResolved.length} theorems, all resolved, ${allResolved.length - overrides} statement(s) from docstrings + ${overrides} manifest override(s), 0 undocumented sorry, ${infoWallFiles.length} documented wall(s), 0 custom axiom.`);
  Deno.exit(0);
}

const label = mode === "hook" ? "⚠ [readme-table]" : "✗ [readme-table]";
console.error(`${label}\n  ` + errs.join("\n  "));
Deno.exit(mode === "hook" ? 0 : 1);
