#!/usr/bin/env -S deno run -A
// gen_readme_table.ts — keep the "Formalized results" table in README.md reproducible.
//
// 手書きの表は rename / move / scope-out で黙って drift する (README が公開で嘘をつく)。
// 再現性の核心は「curation だけ手で (docs/readme-theorems.txt)、表は生成物、--check で
// 『生成結果 == コミット済み』を保証」。パスはマニフェストに書かず毎回コードから解決するので
// ファイル移動は自動追従、true rename/delete だけが落ちる。
//
// 純 Deno でコード走査 (rg はシェル関数で spawn 不可 — plan_lint.ts と同方針、外部 cmd なし)。
//
// Usage:
//   deno run -A scripts/gen_readme_table.ts            # = --check
//   deno run -A scripts/gen_readme_table.ts --check    # 検証のみ。drift で exit 1 (CI 用)
//   deno run -A scripts/gen_readme_table.ts --write    # README のマーカー間に表を再生成
//   deno run -A scripts/gen_readme_table.ts --hook     # pre-commit 用: WARN のみ, 常に exit 0
//
// 誠実性 (README の 2 主張を別々に検証):
//   (1) listed 定理はすべて complete: 定理表に載る定理が属するファイルは strict 0-sorry。
//       listed 定理ファイルに実 sorry があれば documented であっても fail。
//   (2) ライブラリ全体は documented Mathlib 壁のみ許容: 実 sorry は必ず `@residual(wall:<slug>)`
//       タグを伴う (プロジェクト規約 = pre-commit hook が強制)。タグ無しの実 sorry は fail、
//       タグ付き (かつ listed でない) 壁は許容し info 報告。独自 axiom=0 は従来どおり必須。
//   Mathlib は sorry-free なので、listed 定理ファイルが 0-sorry である限り列挙定理は構造的に
//   sorryAx に依存しえず標準 3 公理のみ。per-theorem の #print axioms (lake 必要) は
//   belt-and-suspenders で別 (scripts/ReadmeAxioms.lean)。「実 sorry」は stripComments 後に
//   残る sorry トークン (散文の "sorry-free" 等は除外)、壁タグ検出は strip 前の生テキスト。

const MANIFEST = "docs/readme-theorems.txt";
const README = "README.md";
const CODE_ROOT = "InformationTheory";
const START_MARK = "<!-- THEOREMS:START";
const END_MARK = "<!-- THEOREMS:END -->";
const START_LINE =
  "<!-- THEOREMS:START — generated by scripts/gen_readme_table.ts from docs/readme-theorems.txt; do not edit by hand -->";

const mode = Deno.args.includes("--write")
  ? "write"
  : Deno.args.includes("--hook")
  ? "hook"
  : "check";

// ── manifest ─────────────────────────────────────────────────────────────────

// A result is 'NAME', optionally '@ <path-substring>' to disambiguate same-named decls,
// optionally '| <note>' for a parenthetical. e.g. 'entropy_le_log_card @ MaxEntropy/Basic'.
type Result = { name: string; note?: string; pathHint?: string };
type Chapter = { num: string; title: string; results: Result[] };

function parseManifest(text: string): Chapter[] {
  const chapters: Chapter[] = [];
  let cur: Chapter | null = null;
  for (const raw of text.split("\n")) {
    const line = raw.replace(/\s+$/, "");
    if (line === "" || line.trimStart().startsWith("#")) continue;
    const ch = line.match(/^@\s*([^|]+?)\s*\|\s*(.+)$/);
    if (ch && /^@\s*\d/.test(line)) {
      cur = { num: ch[1].trim(), title: ch[2].trim(), results: [] };
      chapters.push(cur);
      continue;
    }
    if (!cur) throw new Error(`manifest: entry before any '@ <ch> | <title>': ${line}`);
    const parts = line.split(/\s*\|\s*/);
    const note = parts.length > 1 ? parts.slice(1).join(" | ") : undefined;
    const hm = parts[0].match(/^(\S+?)(?:\s+@\s*(\S+))?$/);
    if (!hm) throw new Error(`manifest: cannot parse line: ${line}`);
    cur.results.push({ name: hm[1], note, pathHint: hm[2] });
  }
  return chapters;
}

// ── code scan (pure Deno) ────────────────────────────────────────────────────

// Lean のコメント (行 -- / ネスト可ブロック /- -/、doc /-- -/ 含む) を空白に潰す。改行は保つ
// (行ベース正規表現のため)。pre-commit hook の strip_lean_comments と同じ意図。
function stripComments(src: string): string {
  let out = "";
  let depth = 0;
  for (let i = 0, n = src.length; i < n;) {
    const two = src.substr(i, 2);
    if (depth > 0) {
      if (two === "-/") { depth--; i += 2; continue; }
      if (two === "/-") { depth++; i += 2; continue; }
      out += src[i] === "\n" ? "\n" : " ";
      i++;
      continue;
    }
    if (two === "/-") { depth++; i += 2; continue; }
    if (two === "--") { while (i < n && src[i] !== "\n") i++; continue; }
    out += src[i];
    i++;
  }
  return out;
}

// Name captures a full Lean identifier: Unicode letters/digits incl. subscripts (₂), primes,
// !/?. The 'u' flag + \p{L}\p{N} is essential — a plain \w would truncate `foo₂` to `foo`
// and manufacture false ambiguities/resolutions.
const DECL_RE =
  /^[ \t]*(?:@\[[^\]]*\][ \t]*)*(?:(?:noncomputable|private|protected|scoped|local|partial|unsafe|mutual)[ \t]+)*(?:theorem|lemma|def|abbrev|structure|inductive|class|instance|opaque)[ \t]+(?:@\[[^\]]*\][ \t]*)*([\p{L}_][\p{L}\p{N}_'!?.]*)/gmu;
const SORRY_RE = /\bsorry\b/g;
const AXIOM_RE = /^[ \t]*axiom[ \t]/gm;
// A documented Mathlib wall carries a `@residual(wall:<slug>)` tag (project convention,
// enforced by the pre-commit hook). The tag lives in a comment, so it is detected on the
// RAW text, before stripComments. Everything else with a real sorry is undocumented → fail.
const WALL_TAG = "@residual(wall:";

type Index = {
  decls: Map<string, string[]>; // name -> repo-relative file paths
  documentedWallFiles: string[]; // real sorry + a `@residual(wall:` tag → tolerated
  undocumentedSorryFiles: string[]; // real sorry, no wall tag → always fail
  axiomFiles: string[];
};

async function* walkLean(dir: string): AsyncGenerator<string> {
  for await (const e of Deno.readDir(dir)) {
    const p = `${dir}/${e.name}`;
    if (e.isDirectory) yield* walkLean(p);
    else if (e.isFile && p.endsWith(".lean")) yield p;
  }
}

async function buildIndex(): Promise<Index> {
  const decls = new Map<string, string[]>();
  const documentedWallFiles: string[] = [];
  const undocumentedSorryFiles: string[] = [];
  const axiomFiles: string[] = [];
  for await (const path of walkLean(CODE_ROOT)) {
    const raw = await Deno.readTextFile(path);
    const code = stripComments(raw);
    for (const m of code.matchAll(DECL_RE)) {
      const name = m[1];
      const arr = decls.get(name);
      if (arr) { if (!arr.includes(path)) arr.push(path); }
      else decls.set(name, [path]);
    }
    if (SORRY_RE.test(code)) {
      // A real sorry (survives stripComments). Documented iff the raw text carries a
      // `@residual(wall:` tag (which lives in a comment, hence checked on raw, not code).
      if (raw.includes(WALL_TAG)) documentedWallFiles.push(path);
      else undocumentedSorryFiles.push(path);
    }
    SORRY_RE.lastIndex = 0;
    if (AXIOM_RE.test(code)) axiomFiles.push(path);
    AXIOM_RE.lastIndex = 0;
  }
  return { decls, documentedWallFiles, undocumentedSorryFiles, axiomFiles };
}

// The set of files that a README-listed theorem resolves to. Every listed result must be
// complete, so a real sorry in one of these files is a hard fail even when documented.
// Path selection mirrors renderTable (single site → it; ambiguous → sites[0]; none → skip).
function listedTheoremFiles(chapters: Chapter[], idx: Index): Set<string> {
  const files = new Set<string>();
  for (const ch of chapters) {
    for (const r of ch.results) {
      let sites = idx.decls.get(r.name) ?? [];
      if (r.pathHint) sites = sites.filter((p) => p.includes(r.pathHint!));
      if (sites.length >= 1) files.add(sites[0]);
    }
  }
  return files;
}

// ── render ───────────────────────────────────────────────────────────────────

function renderTable(chapters: Chapter[], idx: Index, errs: string[]): string {
  const rows = [
    "| Ch. | Topic | Key results |",
    "|-----|-------|-------------|",
  ];
  for (const ch of chapters) {
    const cells: string[] = [];
    for (const r of ch.results) {
      let sites = idx.decls.get(r.name) ?? [];
      if (r.pathHint) sites = sites.filter((p) => p.includes(r.pathHint!));
      let path: string;
      if (sites.length === 0) {
        const hint = r.pathHint ? ` matching '@ ${r.pathHint}'` : "";
        errs.push(`Ch.${ch.num}: '${r.name}'${hint} not found in ${CODE_ROOT}/ (renamed or deleted?)`);
        path = "#";
      } else if (sites.length > 1) {
        errs.push(`Ch.${ch.num}: '${r.name}' is ambiguous (${sites.length} decls): ${sites.join(", ")} — add '@ <path-substring>' in the manifest`);
        path = sites[0];
      } else {
        path = sites[0];
      }
      const note = r.note ? ` (${r.note})` : "";
      cells.push(`[\`${r.name}\`](${path})${note}`);
    }
    rows.push(`| ${ch.num} | ${ch.title} | ${cells.join(" · ")} |`);
  }
  return rows.join("\n");
}

function spliceReadme(readme: string, table: string): string {
  const lines = readme.split("\n");
  const s = lines.findIndex((l) => l.includes(START_MARK));
  const e = lines.findIndex((l) => l.includes(END_MARK));
  if (s === -1 || e === -1 || e < s) {
    throw new Error(`${README}: markers ${START_MARK} … ${END_MARK} not found (add them around the table first)`);
  }
  const before = lines.slice(0, s);
  const after = lines.slice(e + 1);
  return [...before, START_LINE, table, END_MARK, ...after].join("\n");
}

function currentTable(readme: string): string | null {
  const lines = readme.split("\n");
  const s = lines.findIndex((l) => l.includes(START_MARK));
  const e = lines.findIndex((l) => l.includes(END_MARK));
  if (s === -1 || e === -1 || e < s) return null;
  return lines.slice(s + 1, e).join("\n").replace(/\s+$/, "");
}

// ── main ─────────────────────────────────────────────────────────────────────

const chapters = parseManifest(await Deno.readTextFile(MANIFEST));
const idx = await buildIndex();
const errs: string[] = [];
const table = renderTable(chapters, idx, errs);

// honesty — the README publishes two distinct claims, checked separately:
//   (1) every *listed* result is complete: no sorry in a listed-theorem file, ever;
//   (2) the library as a whole carries only *documented* Mathlib walls: any real sorry
//       must sit under a `@residual(wall:<slug>)` tag (undocumented sorry → fail).
const listedFiles = listedTheoremFiles(chapters, idx);

// (a) any real sorry without a wall tag → fail.
if (idx.undocumentedSorryFiles.length > 0) {
  errs.push(`honesty: ${idx.undocumentedSorryFiles.length} file(s) contain a real 'sorry' with no @residual(wall:…) tag: ${idx.undocumentedSorryFiles.join(", ")}`);
}
// (b) any real sorry (documented or not) inside a README-listed result's file → fail:
//     "every result listed below is complete" must stay true.
const listedWithSorry = [...idx.documentedWallFiles, ...idx.undocumentedSorryFiles]
  .filter((p) => listedFiles.has(p));
if (listedWithSorry.length > 0) {
  errs.push(`honesty: ${listedWithSorry.length} README-listed result file(s) contain a real 'sorry' — every listed result must be complete: ${listedWithSorry.join(", ")}`);
}
// (c) documented walls outside any listed file are tolerated (reported as info below).
const infoWallFiles = idx.documentedWallFiles.filter((p) => !listedFiles.has(p));

if (idx.axiomFiles.length > 0) {
  errs.push(`honesty: ${idx.axiomFiles.length} file(s) declare a custom 'axiom' — README claims none: ${idx.axiomFiles.join(", ")}`);
}

const readme = await Deno.readTextFile(README);

if (mode === "write") {
  if (errs.length) {
    console.error("✗ refusing to write — fix these first:\n  " + errs.join("\n  "));
    Deno.exit(1);
  }
  const out = spliceReadme(readme, table);
  if (out !== readme) {
    await Deno.writeTextFile(README, out);
    console.log("✓ README table regenerated.");
  } else {
    console.log("✓ README table already up to date.");
  }
  Deno.exit(0);
}

// check / hook
const stale = currentTable(readme) !== table.replace(/\s+$/, "");
if (stale && !errs.some((e) => e.startsWith("Ch."))) {
  errs.push("README table is out of date with the manifest/code — run: deno run -A scripts/gen_readme_table.ts --write");
}

if (infoWallFiles.length > 0) {
  console.log(`ℹ ${infoWallFiles.length} documented wall(s) (real 'sorry' + @residual(wall:…), not among listed results): ${infoWallFiles.join(", ")}`);
}

if (errs.length === 0) {
  const walls = infoWallFiles.length;
  console.log(`✓ README table in sync — ${chapters.length} chapters, ${chapters.reduce((a, c) => a + c.results.length, 0)} theorems, all resolved, 0 undocumented sorry, ${walls} documented wall(s), 0 custom axiom.`);
  Deno.exit(0);
}

const label = mode === "hook" ? "⚠ [readme-table]" : "✗ [readme-table]";
console.error(`${label}\n  ` + errs.join("\n  "));
Deno.exit(mode === "hook" ? 0 : 1);
