import Common2026.Shannon.Stationary
import Common2026.Shannon.EntropyRate
import Mathlib.MeasureTheory.Constructions.Projective
import Mathlib.MeasureTheory.Constructions.ProjectiveFamilyContent
import Mathlib.MeasureTheory.Constructions.Cylinders
import Mathlib.MeasureTheory.Constructions.ClosedCompactCylinders
import Mathlib.MeasureTheory.OuterMeasure.OfAddContent
import Mathlib.MeasureTheory.Measure.AddContent
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Indicator
import Mathlib.Probability.Martingale.Basic
import Mathlib.Probability.Martingale.Convergence

/-!
# 2-sided stationary extension `μ_ℤ` (SMB Phase D — sub-plan)

For a stationary process `(Ω, T, μ, X)` with `X : Ω → α` (Fintype), this module
builds the canonical 2-sided extension `μ_ℤ : Measure (ℤ → α)` such that:

* the natural ℕ-projection of `μ_ℤ` agrees with the law of `(X ∘ T^[i])_{i ≥ 0}`,
* the shift `σ : (ℤ → α) → (ℤ → α)`, `σ x i := x (i + 1)`, is `μ_ℤ`-preserving,
* `μ_ℤ` is ergodic whenever `(Ω, T, μ)` is.

The extension is needed because the SMB lower bound (`liminf blockLogAvg ≥
entropyRate`) hinges on the *backward* Levy convergence applied to the
σ-algebra generated by the negative-time coordinates, which is *not* available
on the one-sided (`ℕ`-indexed) side.

See `docs/shannon/smb-two-sided-extension-plan.md` for the full plan, route
choice (Hahn–Kolmogorov on cylinder semiring), and per-phase risks.

## Structure

The plan is split into eight phases A–H. This file is the carrier for Phase B
through Phase G, with Phase A being the skeleton. Phase H (the actual SMB
`liminf` discharge) lives in a follow-up file `SMBLiminfDischarge.lean`.

* **Phase A** — skeleton, namespace, imports.
* **Phase B** — `shiftedMarginal`, the family of finite-dimensional marginals
  obtained from the one-sided stationary distribution by translating any finite
  index set into `ℕ`. *(this file: filled.)*
* **Phase C** — projective consistency `IsProjectiveMeasureFamily` + the
  `tendsto_zero` σ-additivity input. *(this file: skeleton with `sorry`.)*
* **Phase D** — Carathéodory extension `μZ` via `AddContent.measure`.
  *(this file: skeleton with `sorry`.)*
* **Phase E** — shift `MeasurePreserving` + `Ergodic` transfer.
  *(this file: skeleton with `sorry`.)*
* **Phase F** — coupling `(Ω, T, μ) ↔ (ℤ → α, σ, μZ)` on ℕ-projection.
  *(this file: skeleton with `sorry`.)*
* **Phase G** — forward filtration `pastSigma` (finite past of length `k`),
  forward Lévy upward convergence `pmfLogCondPast → pmfLogCondInfty`, and
  the SMB bridge `∫ pmfLogCondInfty dμZ = entropyRate μ p`.

## Main definitions (Phase B)

* `shiftAmount J` — the smallest non-negative offset making every element of
  `J : Finset ℤ` non-negative.
* `obsZ μ p N J` — the joint observation `ω ↦ fun j : J ↦ X (T^[(j+N).toNat] ω)`.
* `shiftedMarginal μ p J` — `μ.map (obsZ μ p (shiftAmount J) J)`.

## Main results (Phase B)

* `shiftedMarginal_eq_of_shift` — N-independence: any sufficient shift gives
  the same pushforward, via stationarity.
* `isProjectiveMeasureFamily_shiftedMarginal` — projective consistency.
* `instIsProbabilityMeasure_shiftedMarginal` — each marginal is a probability
  measure.
-/

namespace InformationTheory.Shannon.TwoSided

open MeasureTheory ProbabilityTheory Filter
open scoped ENNReal Topology

variable {Ω : Type*} [MeasurableSpace Ω]
variable {α : Type*} [Fintype α] [DecidableEq α] [Nonempty α]
  [MeasurableSpace α] [MeasurableSingletonClass α]

/-! ## Phase B — shifted finite-dimensional marginals -/

section ShiftedMarginal

variable (μ : Measure Ω) [IsProbabilityMeasure μ] (p : StationaryProcess μ α)

/-- The minimal non-negative integer `N` that makes every element of `J` non-negative
after shifting by `N`. For empty `J` we return `0`. -/
noncomputable def shiftAmount (J : Finset ℤ) : ℕ :=
  if h : J.Nonempty then (-(J.min' h)).toNat else 0

/-- For any sufficient shift `N`, every `j ∈ J` satisfies `0 ≤ j + N`. -/
lemma zero_le_shiftAmount_add (J : Finset ℤ) {j : ℤ} (hj : j ∈ J) :
    (0 : ℤ) ≤ j + shiftAmount J := by
  classical
  have hJ : J.Nonempty := ⟨j, hj⟩
  unfold shiftAmount
  rw [dif_pos hJ]
  have hmin : J.min' hJ ≤ j := J.min'_le _ hj
  by_cases hpos : 0 ≤ -(J.min' hJ)
  · have hcoe : ((-(J.min' hJ)).toNat : ℤ) = -(J.min' hJ) := Int.toNat_of_nonneg hpos
    rw [hcoe]; linarith
  · -- `-J.min' hJ < 0`, i.e. `J.min' hJ > 0`; then `j ≥ 0` and toNat ≥ 0.
    have hcoe : (0 : ℤ) ≤ ((-(J.min' hJ)).toNat : ℤ) := Int.natCast_nonneg _
    have h0 : 0 ≤ j := le_trans (by linarith) hmin
    linarith

/-- The joint observation at `ℤ`-indexed times, parametrized by a shift `N`:
`obsZ μ p N J ω j := X (T^[(j + N).toNat] ω)`. When `N ≥ shiftAmount J`, this
records the genuine block `(X_{j₀+N}, X_{j₁+N}, …)` evaluated at the points of `J`. -/
noncomputable def obsZ (N : ℕ) (J : Finset ℤ) : Ω → (∀ _ : J, α) :=
  fun ω j => p.obs (j.1 + N).toNat ω

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- The joint observation `obsZ μ p N J` is measurable. -/
lemma measurable_obsZ (N : ℕ) (J : Finset ℤ) : Measurable (obsZ μ p N J) := by
  refine measurable_pi_iff.mpr (fun j => ?_)
  exact p.measurable_obs _

/-- The finite-dimensional marginal of the (yet-to-be-built) two-sided extension at
the index set `J : Finset ℤ`. Defined as the law of `obsZ` at the canonical shift
`shiftAmount J`; the value is independent of the chosen shift by stationarity
(`shiftedMarginal_eq_of_shift`). -/
noncomputable def shiftedMarginal (J : Finset ℤ) : Measure (∀ _ : J, α) :=
  μ.map (obsZ μ p (shiftAmount J) J)

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- For two non-negative shifts `N₁ ≤ N₂` both valid for `J`, the joint observation
under `N₂` is the same as under `N₁` precomposed with `T^[N₂ - N₁]`. -/
lemma obsZ_succ_shift {J : Finset ℤ} (N k : ℕ)
    (hN : ∀ j ∈ J, (0 : ℤ) ≤ j + N) :
    obsZ μ p (N + k) J = (obsZ μ p N J) ∘ p.T^[k] := by
  funext ω j
  simp only [obsZ, Function.comp_apply, StationaryProcess.obs]
  -- Goal: X (T^[(j.1 + (N + k)).toNat] ω) = X (T^[(j.1 + N).toNat] (T^[k] ω))
  have hjN : (0 : ℤ) ≤ j.1 + N := hN _ j.2
  have hjNk : (0 : ℤ) ≤ j.1 + ((N + k : ℕ) : ℤ) := by
    have hk : (0 : ℤ) ≤ (k : ℤ) := Int.natCast_nonneg _
    have : ((N + k : ℕ) : ℤ) = (N : ℤ) + k := by push_cast; ring
    rw [this]; linarith
  -- `(j.1 + (N+k)).toNat = (j.1 + N).toNat + k`
  have htoNat : ((j.1 + ((N + k : ℕ) : ℤ)).toNat) = (j.1 + N).toNat + k := by
    have h1 : ((j.1 + N).toNat : ℤ) = j.1 + N := Int.toNat_of_nonneg hjN
    have h2 : ((j.1 + ((N + k : ℕ) : ℤ)).toNat : ℤ) = j.1 + ((N + k : ℕ) : ℤ) :=
      Int.toNat_of_nonneg hjNk
    -- Lift through ℤ
    have : ((((j.1 + N).toNat + k : ℕ)) : ℤ) = j.1 + ((N + k : ℕ) : ℤ) := by
      push_cast; linarith [h1]
    have h3 : ((j.1 + ((N + k : ℕ) : ℤ)).toNat : ℤ)
        = (((j.1 + N).toNat + k : ℕ) : ℤ) := by rw [h2, ← this]
    exact_mod_cast h3
  -- T^[(j.1 + N + k).toNat] ω = T^[(j.1 + N).toNat + k] ω
  -- We want T^[a + k] ω = T^[a] (T^[k] ω), which is `Function.iterate_add_apply T a k ω`.
  rw [htoNat, Function.iterate_add_apply p.T]

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- **N-invariance of `obsZ` under push-forward** (stationarity, single-shift step).
For any valid shift `N`, pushing forward by `obsZ μ p (N + k) J` agrees with pushing
forward by `obsZ μ p N J`. -/
lemma map_obsZ_succ {J : Finset ℤ} (N k : ℕ) (hN : ∀ j ∈ J, (0 : ℤ) ≤ j + N) :
    μ.map (obsZ μ p (N + k) J) = μ.map (obsZ μ p N J) := by
  rw [obsZ_succ_shift μ p N k hN,
      ← Measure.map_map (measurable_obsZ μ p N J) (p.measurable_iterate k),
      (p.measurePreserving.iterate k).map_eq]

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- **N-invariance of the pushforward law** (general form): any two valid shifts
yield the same pushforward measure. -/
theorem map_obsZ_eq_of_shift {J : Finset ℤ} (N₁ N₂ : ℕ)
    (h₁ : ∀ j ∈ J, (0 : ℤ) ≤ j + N₁)
    (h₂ : ∀ j ∈ J, (0 : ℤ) ≤ j + N₂) :
    μ.map (obsZ μ p N₁ J) = μ.map (obsZ μ p N₂ J) := by
  -- WLOG via the symmetric chain
  rcases le_total N₁ N₂ with h | h
  · obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le h
    exact (map_obsZ_succ μ p N₁ k h₁).symm
  · obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le h
    exact map_obsZ_succ μ p N₂ k h₂

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- The shifted marginal coincides with the pushforward of `obsZ` for any valid shift,
not just the canonical `shiftAmount J`. -/
theorem shiftedMarginal_eq_of_shift (J : Finset ℤ) (N : ℕ)
    (hN : ∀ j ∈ J, (0 : ℤ) ≤ j + N) :
    shiftedMarginal μ p J = μ.map (obsZ μ p N J) := by
  unfold shiftedMarginal
  exact map_obsZ_eq_of_shift μ p _ _ (fun j hj => zero_le_shiftAmount_add J hj) hN

/-- Each shifted marginal is a probability measure (pushforward of a probability
measure under a measurable map). -/
instance instIsProbabilityMeasure_shiftedMarginal (J : Finset ℤ) :
    IsProbabilityMeasure (shiftedMarginal μ p J) := by
  unfold shiftedMarginal
  exact Measure.isProbabilityMeasure_map (measurable_obsZ μ p _ J).aemeasurable

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- **Projective consistency**: for `J ⊆ I`, restricting `shiftedMarginal μ p I` along
the inclusion gives `shiftedMarginal μ p J`. -/
theorem isProjectiveMeasureFamily_shiftedMarginal :
    IsProjectiveMeasureFamily
      (α := fun _ : ℤ => α) (shiftedMarginal μ p) := by
  intro I J hJI
  classical
  -- Pick a shift `N` that works for `I` (and hence for `J ⊆ I`).
  -- Use the larger of `shiftAmount I` and `shiftAmount J` to be safe; in fact
  -- `shiftAmount I` alone works since `J ⊆ I` means `J.min' ≥ I.min'`.
  by_cases hI : I.Nonempty
  · set N := shiftAmount I with hN_def
    have hN_I : ∀ i ∈ I, (0 : ℤ) ≤ i + N :=
      fun i hi => zero_le_shiftAmount_add I hi
    have hN_J : ∀ j ∈ J, (0 : ℤ) ≤ j + N :=
      fun j hj => hN_I j (hJI hj)
    -- Rewrite both sides via the explicit shift `N`.
    rw [shiftedMarginal_eq_of_shift μ p I N hN_I,
        shiftedMarginal_eq_of_shift μ p J N hN_J]
    -- Now: `μ.map (obsZ N J) = (μ.map (obsZ N I)).map (Finset.restrict₂ hJI)`.
    -- The key observation: `obsZ N J = Finset.restrict₂ hJI ∘ obsZ N I`.
    have h_comp :
        obsZ μ p N J
          = (Finset.restrict₂ (π := fun _ : ℤ => α) hJI) ∘ (obsZ μ p N I) := by
      funext ω j; rfl
    rw [h_comp,
        Measure.map_map (Finset.measurable_restrict₂ (X := fun _ : ℤ => α) hJI)
          (measurable_obsZ μ p N I)]
  · -- I is empty, so J = ∅ too.
    have hJ_empty : J = ∅ := by
      rw [Finset.not_nonempty_iff_eq_empty] at hI
      rw [Finset.eq_empty_iff_forall_notMem]
      intro j hj
      have := hJI hj
      rw [hI] at this
      exact Finset.notMem_empty _ this
    subst hJ_empty
    -- I = ∅, J = ∅. The empty inclusion is the identity (uniquely typed).
    have hI_empty : I = ∅ := Finset.not_nonempty_iff_eq_empty.mp hI
    subst hI_empty
    -- Now `Finset.restrict₂ hJI : (∀ i : (∅ : Finset ℤ), α) → (∀ j : (∅ : Finset ℤ), α)`.
    -- Both shiftedMarginal `∅` are probability measures on a subsingleton type.
    -- It suffices to show they're both probability measures on the unique singleton.
    have : Finset.restrict₂ (π := fun _ : ℤ => α) hJI = id := by
      funext f j
      exact (Finset.notMem_empty _ j.2).elim
    rw [this, Measure.map_id]

end ShiftedMarginal

/-! ## Phase C — projective consistency + σ-additivity -/

section StationaryContent

variable (μ : Measure Ω) [IsProbabilityMeasure μ] (p : StationaryProcess μ α)

/-- The `AddContent` on measurable cylinders of `ℤ → α` induced by the shifted
finite-dimensional marginals. -/
noncomputable def stationaryContent :
    AddContent ℝ≥0∞ (measurableCylinders (fun _ : ℤ => α)) :=
  projectiveFamilyContent (isProjectiveMeasureFamily_shiftedMarginal μ p)

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- σ-additivity input: for any antitone sequence of measurable cylinders with empty
intersection, the content tends to 0.

The proof uses the **finite-type Cantor argument**: equipping `α` with the discrete
topology turns `ℤ → α` into a compact Hausdorff space (`Pi.compactSpace` from finite
discrete factors), every cylinder `cylinder I S` is closed (preimage of a finite, hence
closed, set), and every closed subset of a compact space is compact. Cantor's
intersection theorem for sequences (`IsCompact.nonempty_iInter_of_sequence_…`) then
gives `∃ N, A N = ∅`, after which `stationaryContent (A n) = 0` for `n ≥ N`. -/
theorem stationaryContent_tendsto_zero
    {A : ℕ → Set (∀ _ : ℤ, α)}
    (A_mem : ∀ n, A n ∈ measurableCylinders (fun _ : ℤ => α))
    (A_anti : Antitone A) (A_inter : ⋂ n, A n = ∅) :
    Tendsto (fun n => stationaryContent μ p (A n)) atTop (𝓝 0) := by
  classical
  -- Equip `α` with the discrete topology; `ℤ → α` becomes compact Hausdorff.
  letI : TopologicalSpace α := ⊥
  haveI : DiscreteTopology α := ⟨rfl⟩
  -- (Pi instances ensure ℤ → α is a topological space; finite + discrete ⇒ compact.)
  -- Extract a cylinder representation for each `A n`.
  have A_cyl : ∀ n, ∃ (s : Finset ℤ) (S : Set (∀ _ : s, α)),
      MeasurableSet S ∧ A n = cylinder s S := by
    intro n; exact (mem_measurableCylinders (A n)).1 (A_mem n)
  choose s S _hS A_eq using A_cyl
  -- The base set `S n` is a finite subset of the finite type `∀ i : s n, α`.
  have hS_finite : ∀ n, (S n).Finite := fun n => Set.toFinite (S n)
  -- Finite subsets of a (discrete, hence T1) space are closed.
  have hS_closed : ∀ n, IsClosed (S n) := fun n => (hS_finite n).isClosed
  -- The cylinder is the preimage of `S n` under the continuous restriction map.
  have hAn_closed : ∀ n, IsClosed (A n) := by
    intro n
    rw [A_eq n]
    exact (hS_closed n).preimage (s n).continuous_restrict
  -- ℤ → α is a compact space (product of compact discrete finite α).
  have hAn_compact : ∀ n, IsCompact (A n) := fun n => (hAn_closed n).isCompact
  -- Cantor: ⋂ A n = ∅ + each A n is compact + closed + antitone ⇒ some A N = ∅.
  -- Apply the contrapositive of `IsCompact.nonempty_iInter_of_sequence_…`.
  have hN : ∃ N, A N = ∅ := by
    by_contra h
    push Not at h
    have hA_ne : ∀ n, (A n).Nonempty := h
    have hA_dec : ∀ n, A (n + 1) ⊆ A n := fun n => A_anti (Nat.le_succ n)
    have hnon : (⋂ n, A n).Nonempty :=
      IsCompact.nonempty_iInter_of_sequence_nonempty_isCompact_isClosed
        A hA_dec hA_ne (hAn_compact 0) hAn_closed
    rw [A_inter] at hnon
    exact hnon.ne_empty rfl
  obtain ⟨N, hAN⟩ := hN
  -- For n ≥ N, A n ⊆ A N = ∅, hence A n = ∅, hence content is 0.
  apply Tendsto.congr' (f₁ := fun _ => (0 : ℝ≥0∞)) _ tendsto_const_nhds
  rw [EventuallyEq, eventually_atTop]
  refine ⟨N, fun n hn => ?_⟩
  have hAn_empty : A n = ∅ := Set.subset_empty_iff.mp (hAN ▸ A_anti hn)
  rw [hAn_empty]
  exact (addContent_empty (m := stationaryContent μ p)).symm

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `stationaryContent` is σ-subadditive (from `tendsto_zero`). -/
theorem stationaryContent_isSigmaSubadditive :
    (stationaryContent μ p).IsSigmaSubadditive := by
  -- Mirrors `Mathlib/Probability/ProductMeasure.lean : isSigmaSubadditive_piContent`.
  refine isSigmaSubadditive_of_addContent_iUnion_eq_tsum
    isSetRing_measurableCylinders (fun f hf hf_Union hf' => ?_)
  exact addContent_iUnion_eq_sum_of_tendsto_zero isSetRing_measurableCylinders
    (stationaryContent μ p)
    (fun _ _ => projectiveFamilyContent_ne_top _)
    (fun _ hs_mem hs_anti hs_inter =>
      stationaryContent_tendsto_zero μ p hs_mem hs_anti hs_inter)
    hf hf_Union hf'

end StationaryContent

/-! ## Phase D — Carathéodory extension `μZ` -/

section MuZ

variable (μ : Measure Ω) [IsProbabilityMeasure μ] (p : StationaryProcess μ α)

/-- The two-sided extension `μ_ℤ : Measure (ℤ → α)` obtained from the stationary
process `(Ω, T, μ, X)` by Carathéodory extension of the `stationaryContent`. -/
noncomputable def μZ : Measure (∀ _ : ℤ, α) :=
  (stationaryContent μ p).measure
    isSetSemiring_measurableCylinders
    (by rw [generateFrom_measurableCylinders])
    (stationaryContent_isSigmaSubadditive μ p)

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- On measurable cylinders, `μZ` agrees with `shiftedMarginal`. -/
theorem μZ_cylinder {I : Finset ℤ} {S : Set (∀ _ : I, α)} (hS : MeasurableSet S) :
    μZ μ p (cylinder I S) = shiftedMarginal μ p I S := by
  -- μZ on a cylinder = stationaryContent on that cylinder
  --                  = projectiveFamilyFun applied to the cylinder
  --                  = shiftedMarginal μ p I S.
  rw [μZ, AddContent.measure_eq _ _ generateFrom_measurableCylinders.symm _
    (cylinder_mem_measurableCylinders _ _ hS)]
  exact projectiveFamilyContent_cylinder
    (isProjectiveMeasureFamily_shiftedMarginal μ p) hS

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `μZ` is the projective limit of the shifted marginals. -/
theorem isProjectiveLimit_μZ :
    IsProjectiveLimit (μZ μ p) (shiftedMarginal μ p) := by
  intro I
  ext s hs
  -- `(μZ).map (I.restrict) s = μZ ((I.restrict)⁻¹' s) = μZ (cylinder I s) = shiftedMarginal s`.
  rw [Measure.map_apply (Finset.measurable_restrict I) hs, ← cylinder, μZ_cylinder μ p hs]

/-- `μZ` is a probability measure. -/
instance instIsProbabilityMeasure_μZ : IsProbabilityMeasure (μZ μ p) := by
  -- μZ univ = μZ (cylinder ∅ univ) = shiftedMarginal μ p ∅ univ = 1.
  constructor
  rw [show (Set.univ : Set (∀ _ : ℤ, α)) = cylinder (∅ : Finset ℤ) Set.univ from
        (cylinder_univ ∅).symm,
      μZ_cylinder μ p MeasurableSet.univ]
  exact measure_univ

end MuZ

/-! ## Phase E — shift `MeasurePreserving` + `Ergodic` -/

section Shift

variable (μ : Measure Ω) [IsProbabilityMeasure μ] (p : StationaryProcess μ α)

/-- The two-sided shift `σ : (ℤ → α) → (ℤ → α)`, `σ x i := x (i + 1)`. -/
def shiftZ : (∀ _ : ℤ, α) → (∀ _ : ℤ, α) := fun x i => x (i + 1)

/-- The inverse shift, `σ⁻¹ x i := x (i - 1)`. -/
def shiftZSymm : (∀ _ : ℤ, α) → (∀ _ : ℤ, α) := fun x i => x (i - 1)

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- The shift is measurable. -/
theorem measurable_shiftZ : Measurable (shiftZ : (∀ _ : ℤ, α) → _) :=
  measurable_pi_iff.mpr (fun i => measurable_pi_apply (i + 1))

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- The inverse shift is measurable. -/
theorem measurable_shiftZSymm : Measurable (shiftZSymm : (∀ _ : ℤ, α) → _) :=
  measurable_pi_iff.mpr (fun i => measurable_pi_apply (i - 1))

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- The two-sided shift preserves `μZ`.

Proof outline: both `μZ μ p` and `(μZ μ p).map shiftZ` are projective limits of
the family `shiftedMarginal μ p` of finite-dimensional marginals. By
`IsProjectiveLimit.unique` they are equal. The projective property of the
pushforward reduces to the *shift-invariance of the marginals*: for any
`I : Finset ℤ`, the marginal at `I + 1` (relabeled through the bijection `· + 1`)
equals the marginal at `I`, which is exactly `shiftedMarginal_eq_of_shift`. -/
theorem measurePreserving_shiftZ :
    MeasurePreserving (shiftZ : (∀ _ : ℤ, α) → _) (μZ μ p) (μZ μ p) := by
  classical
  refine ⟨measurable_shiftZ, ?_⟩
  -- The pushforward by `shiftZ` is also a projective limit of `shiftedMarginal`.
  have hlimit : IsProjectiveLimit ((μZ μ p).map shiftZ) (shiftedMarginal μ p) := by
    intro I
    -- Define `I_shift := I.map ⟨(· + 1), …⟩` and the natural bijection
    -- `e : (∀ _ : I_shift, α) → (∀ _ : I, α)`, `e f j := f ⟨j.1 + 1, _⟩`.
    set I_shift : Finset ℤ :=
      I.map ⟨fun i => i + 1, fun a b h => by linarith⟩ with hI_shift
    have hmem_shift : ∀ j : I, j.1 + 1 ∈ I_shift := by
      intro j; rw [hI_shift, Finset.mem_map]
      exact ⟨j.1, j.2, rfl⟩
    set e : (∀ _ : I_shift, α) → (∀ _ : I, α) :=
      fun f j => f ⟨j.1 + 1, hmem_shift j⟩ with he_def
    have hmeas_e : Measurable e :=
      measurable_pi_iff.mpr (fun _ => measurable_pi_apply _)
    -- Rewrite the composition: `I.restrict ∘ shiftZ = e ∘ I_shift.restrict`.
    have hcomp : I.restrict ∘ (shiftZ : (∀ _ : ℤ, α) → _) = e ∘ I_shift.restrict := by
      funext x j
      show shiftZ x j.1 = (I_shift.restrict x) ⟨j.1 + 1, hmem_shift j⟩
      rfl
    -- Push everything through.
    calc ((μZ μ p).map shiftZ).map I.restrict
        = (μZ μ p).map (I.restrict ∘ shiftZ) := by
            rw [← Measure.map_map (Finset.measurable_restrict I) measurable_shiftZ]
      _ = (μZ μ p).map (e ∘ I_shift.restrict) := by rw [hcomp]
      _ = ((μZ μ p).map I_shift.restrict).map e := by
            rw [Measure.map_map hmeas_e (Finset.measurable_restrict I_shift)]
      _ = (shiftedMarginal μ p I_shift).map e := by
            rw [isProjectiveLimit_μZ μ p I_shift]
      _ = shiftedMarginal μ p I := ?_
    -- Final step: shifted marginal at `I_shift` pushed through `e` recovers
    -- the marginal at `I`. Pick a common shift `N := shiftAmount I` and use the
    -- N-independence of the pushforward to compute both sides via `obsZ`.
    -- Show `shiftedMarginal μ p I_shift = μ.map (obsZ μ p (shiftAmount I) I_shift)`
    have hN_shift : ∀ k ∈ I_shift, (0 : ℤ) ≤ k + shiftAmount I := by
      intro k hk
      rw [hI_shift, Finset.mem_map] at hk
      obtain ⟨j, hj, rfl⟩ := hk
      have : (0 : ℤ) ≤ j + shiftAmount I := zero_le_shiftAmount_add I hj
      show (0 : ℤ) ≤ (j + 1) + shiftAmount I
      linarith
    have hN_I_succ : ∀ j ∈ I, (0 : ℤ) ≤ j + (shiftAmount I + 1) := by
      intro j hj
      have : (0 : ℤ) ≤ j + shiftAmount I := zero_le_shiftAmount_add I hj
      linarith
    rw [shiftedMarginal_eq_of_shift μ p I_shift (shiftAmount I) hN_shift,
        shiftedMarginal_eq_of_shift μ p I (shiftAmount I + 1) hN_I_succ]
    -- Now: `(μ.map (obsZ μ p (shiftAmount I) I_shift)).map e = μ.map (obsZ μ p (shiftAmount I + 1) I)`.
    rw [Measure.map_map hmeas_e (measurable_obsZ μ p _ I_shift)]
    congr 1
    funext ω
    funext j
    -- LHS at `j : I`: `e (obsZ N I_shift ω) j = obsZ N I_shift ω ⟨j.1+1, _⟩
    --                = p.obs (j.1 + 1 + N).toNat ω`
    -- RHS at `j : I`: `obsZ (N+1) I ω j = p.obs (j.1 + (N+1)).toNat ω`
    show p.obs ((j.1 + 1) + (shiftAmount I : ℤ)).toNat ω
        = p.obs (j.1 + ((shiftAmount I + 1 : ℕ) : ℤ)).toNat ω
    congr 2
    push_cast; ring
  -- Conclude via `IsProjectiveLimit.unique`.
  exact IsProjectiveLimit.unique hlimit (isProjectiveLimit_μZ μ p)

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSpace α]
  [MeasurableSingletonClass α] [IsProbabilityMeasure μ] in
/-- `shiftZSymm` is the left-inverse of `shiftZ`. -/
theorem leftInverse_shiftZSymm :
    Function.LeftInverse (shiftZSymm (α := α)) shiftZ := by
  intro x; funext i; simp [shiftZ, shiftZSymm]

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSpace α]
  [MeasurableSingletonClass α] [IsProbabilityMeasure μ] in
/-- `shiftZSymm` is the right-inverse of `shiftZ`. -/
theorem rightInverse_shiftZSymm :
    Function.RightInverse (shiftZSymm (α := α)) shiftZ := by
  intro x; funext i; simp [shiftZ, shiftZSymm]

/-- The two-sided shift is ergodic when the underlying process is.

**Status**: declared as `sorry`. Phase E plan (R1, 100-200 LOC) defers this to a
cross-phase task once Phase F coupling is available. The intended route uses
`MeasureTheory.MeasurePreserving.ergodic_of_ergodic_semiconj` after building
a measure-preserving semiconjugacy between `(Ω, T, μ)` and `((ℤ → α), shiftZ, μZ)`.
The obstacle is that stationarity alone does not canonically produce such a
semiconjugacy on the full ℤ-side; the standard workaround is to argue that any
ℤ-shift-invariant cylinder approximation is essentially an `ℕ`-invariant event,
which transfers to a `T`-invariant event on `Ω` via `μZ_nat_proj_eq` / Phase F,
then use the triviality of `T`-invariant events. The full formalization is
budgeted as a follow-up. -/
theorem ergodic_shiftZ (p : ErgodicProcess μ α) :
    Ergodic (shiftZ : (∀ _ : ℤ, α) → _) (μZ μ p.toStationaryProcess) := by
  sorry

end Shift

/-! ## Phase F — coupling with the one-sided side -/

section Coupling

variable (μ : Measure Ω) [IsProbabilityMeasure μ] (p : StationaryProcess μ α)

/-- The forward (one-sided) embedding `Ω → (ℕ → α)`, `ω ↦ (X (T^[i] ω))_i`. -/
def forwardEmbed : Ω → (∀ _ : ℕ, α) := fun ω i => p.obs i ω

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- The forward embedding is measurable. -/
theorem measurable_forwardEmbed : Measurable (forwardEmbed (μ := μ) p) := by
  refine measurable_pi_iff.mpr (fun i => ?_)
  exact p.measurable_obs i

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- The ℕ-projection of `μZ` agrees with the law of `forwardEmbed`.

Both sides are probability measures on `ℕ → α`. We verify equality on the
π-system of measurable cylinders using `MeasureTheory.ext_of_generate_finite`,
then compute each cylinder's measure: on the LHS via `μZ_cylinder` after
rewriting the preimage as a ℤ-cylinder, and on the RHS via the definition
of `forwardEmbed` together with `shiftedMarginal_eq_of_shift` at shift `0`. -/
theorem μZ_nat_proj_eq :
    Measure.map (fun x : (∀ _ : ℤ, α) => fun i : ℕ => x (i : ℤ)) (μZ μ p)
      = Measure.map (forwardEmbed (μ := μ) p) μ := by
  classical
  -- Abbreviate the ℕ-projection map.
  set natProj : (∀ _ : ℤ, α) → (∀ _ : ℕ, α) :=
    fun x i => x (i : ℤ) with hnatProj
  have hmeas_natProj : Measurable natProj :=
    measurable_pi_iff.mpr (fun i => measurable_pi_apply (i : ℤ))
  -- Cast `ℕ → ℤ` is injective; use it to map `Finset ℕ → Finset ℤ`.
  have hcast_inj : Function.Injective (Nat.cast : ℕ → ℤ) := Nat.cast_injective
  -- Both LHS, RHS are probability measures; in particular finite.
  have hLHS_prob : IsProbabilityMeasure
      (Measure.map natProj (μZ μ p)) :=
    Measure.isProbabilityMeasure_map hmeas_natProj.aemeasurable
  -- Apply `ext_of_generate_finite` on `measurableCylinders (fun _ : ℕ => α)`.
  refine MeasureTheory.ext_of_generate_finite (measurableCylinders (fun _ : ℕ => α))
    generateFrom_measurableCylinders.symm isPiSystem_measurableCylinders
    (fun s hs => ?_) ?_
  · -- Cylinder case.
    obtain ⟨I, S, hS, rfl⟩ := (mem_measurableCylinders s).mp hs
    -- Map `I` into ℤ.
    set I_ℤ : Finset ℤ := I.map ⟨Nat.cast, hcast_inj⟩ with hI_ℤ
    -- Bijection helper: each `j : I` corresponds to `⟨(j.1 : ℤ), _⟩ : I_ℤ`.
    have hmem : ∀ j : I, ((j.1 : ℕ) : ℤ) ∈ I_ℤ := by
      intro j; rw [hI_ℤ, Finset.mem_map]
      exact ⟨j.1, j.2, rfl⟩
    -- The bijection `bij : (∀ i : I_ℤ, α) → (∀ j : I, α)`.
    set bij : (∀ _ : I_ℤ, α) → (∀ _ : I, α) :=
      fun f j => f ⟨((j.1 : ℕ) : ℤ), hmem j⟩ with hbij_def
    have hmeas_bij : Measurable bij :=
      measurable_pi_iff.mpr (fun _ => measurable_pi_apply _)
    -- Preimage rewrite: `natProj⁻¹ (cylinder I S) = cylinder I_ℤ (bij⁻¹ S)`.
    have hpre : natProj ⁻¹' cylinder I S = cylinder I_ℤ (bij ⁻¹' S) := by
      ext x
      change (I.restrict (natProj x)) ∈ S ↔ (I_ℤ.restrict x) ∈ bij ⁻¹' S
      rfl
    -- LHS evaluation.
    rw [Measure.map_apply hmeas_natProj (MeasurableSet.cylinder I hS),
        hpre,
        μZ_cylinder μ p (hmeas_bij hS)]
    -- Now: `shiftedMarginal μ p I_ℤ (bij⁻¹ S) = (Measure.map forwardEmbed μ) (cylinder I S)`.
    -- All elements of `I_ℤ` are non-negative, so we can take shift `N=0`.
    have hI_ℤ_nonneg : ∀ i ∈ I_ℤ, (0 : ℤ) ≤ i + (0 : ℕ) := by
      intro i hi
      rw [hI_ℤ, Finset.mem_map] at hi
      obtain ⟨n, _, rfl⟩ := hi
      simp [Function.Embedding.coeFn_mk]
    rw [shiftedMarginal_eq_of_shift μ p I_ℤ 0 hI_ℤ_nonneg,
        Measure.map_apply (measurable_obsZ μ p 0 I_ℤ) (hmeas_bij hS)]
    rw [Measure.map_apply (measurable_forwardEmbed (μ := μ) p)
          (MeasurableSet.cylinder I hS)]
    -- Identify the two preimages on `Ω`: both compute to the same set.
    apply congrArg
    ext ω
    -- Goal: ω ∈ (bij ∘ obsZ ...)⁻¹ S ↔ ω ∈ (forwardEmbed)⁻¹ (cylinder I S)
    have hcoerce : ∀ j : I, ((((j.1 : ℕ) : ℤ) + ((0 : ℕ) : ℤ)).toNat) = j.1 := by
      intro j; simp
    have hfun : bij (obsZ μ p 0 I_ℤ ω) = I.restrict (forwardEmbed (μ := μ) p ω) := by
      funext j
      simp only [hbij_def, obsZ, forwardEmbed, Finset.restrict]
      rw [show ((((j.1 : ℕ) : ℤ) + ((0 : ℕ) : ℤ)).toNat) = j.1 from hcoerce j]
    simp only [Set.mem_preimage, hfun, mem_cylinder]
  · -- Equality on univ.
    rw [Measure.map_apply hmeas_natProj MeasurableSet.univ,
        Measure.map_apply (measurable_forwardEmbed (μ := μ) p) MeasurableSet.univ]
    simp

omit [DecidableEq α] [Nonempty α] in
/-- Block cylinder under `μZ` equals the block-law on the one-sided side. -/
theorem μZ_block_cylinder_eq (n : ℕ) (s : Fin n → α) :
    μZ μ p { x | ∀ i : Fin n, x ((i : ℕ) : ℤ) = s i }
      = (μ.map (p.blockRV n)) {s} := by
  classical
  -- The set `{x | ∀ i : Fin n, x ((i : ℕ) : ℤ) = s i}` is a measurable cylinder on
  -- the finite index set `I_ℤ := (Finset.range n).map (Nat.cast embedding)`.
  -- We express it as a cylinder on `I_ℤ` with base equal to a singleton in
  -- the relabeled function space, then apply `μZ_cylinder` + `shiftedMarginal`.
  set I_ℤ : Finset ℤ :=
    (Finset.range n).map ⟨Nat.cast, Nat.cast_injective⟩ with hI_ℤ
  -- Bijection: each `j : I_ℤ` corresponds to some `i : Fin n` with `i.1 = j.1.toNat`.
  -- Define `S_ℤ : Set (∀ _ : I_ℤ, α)` = `{f | ∀ i : Fin n, f ⟨(i : ℤ), _⟩ = s i}`.
  have hmem : ∀ i : Fin n, ((i : ℕ) : ℤ) ∈ I_ℤ := by
    intro i; rw [hI_ℤ, Finset.mem_map]
    exact ⟨i, by simp [Finset.mem_range, i.2], rfl⟩
  set S_ℤ : Set (∀ _ : I_ℤ, α) :=
    {f | ∀ i : Fin n, f ⟨((i : ℕ) : ℤ), hmem i⟩ = s i} with hS_ℤ
  -- Measurability of S_ℤ: intersection of fiber-equality sets (`α` has
  -- `MeasurableSingletonClass`).
  have hS_ℤ_meas : MeasurableSet S_ℤ := by
    rw [hS_ℤ]
    have : {f : ∀ _ : I_ℤ, α | ∀ i : Fin n, f ⟨((i : ℕ) : ℤ), hmem i⟩ = s i}
        = ⋂ i : Fin n, {f | f ⟨((i : ℕ) : ℤ), hmem i⟩ = s i} := by
      ext f; simp
    rw [this]
    refine MeasurableSet.iInter (fun i => ?_)
    have hmeas : Measurable (fun f : ∀ _ : I_ℤ, α => f ⟨((i : ℕ) : ℤ), hmem i⟩) :=
      measurable_pi_apply _
    have hpre : {f : ∀ _ : I_ℤ, α | f ⟨((i : ℕ) : ℤ), hmem i⟩ = s i}
        = (fun f : ∀ _ : I_ℤ, α => f ⟨((i : ℕ) : ℤ), hmem i⟩) ⁻¹' {s i} := rfl
    rw [hpre]
    exact hmeas (measurableSet_singleton (s i))
  -- The set equality.
  have hset : {x : (∀ _ : ℤ, α) | ∀ i : Fin n, x ((i : ℕ) : ℤ) = s i}
      = cylinder I_ℤ S_ℤ := by
    ext x
    simp only [Set.mem_setOf_eq, cylinder, Set.mem_preimage, Finset.restrict, hS_ℤ]
  rw [hset, μZ_cylinder μ p hS_ℤ_meas]
  -- All elements of `I_ℤ` are non-negative; use shift `N = 0`.
  have hI_ℤ_nonneg : ∀ i ∈ I_ℤ, (0 : ℤ) ≤ i + (0 : ℕ) := by
    intro i hi
    rw [hI_ℤ, Finset.mem_map] at hi
    obtain ⟨k, _, rfl⟩ := hi
    simp [Function.Embedding.coeFn_mk]
  rw [shiftedMarginal_eq_of_shift μ p I_ℤ 0 hI_ℤ_nonneg]
  rw [Measure.map_apply (measurable_obsZ μ p 0 I_ℤ) hS_ℤ_meas]
  rw [Measure.map_apply (p.measurable_blockRV n) (measurableSet_singleton s)]
  -- Identify preimages on Ω.
  congr 1
  ext ω
  simp only [Set.mem_preimage, hS_ℤ, Set.mem_setOf_eq, obsZ,
    Set.mem_singleton_iff]
  constructor
  · intro h
    funext i
    have := h i
    -- `p.obs ((((i:ℕ):ℤ) + 0).toNat) ω = s i`
    have hcast : ((((i : ℕ) : ℤ) + ((0 : ℕ) : ℤ)).toNat) = i.1 := by simp
    rw [hcast] at this
    exact this
  · intro h i
    have hcast : ((((i : ℕ) : ℤ) + ((0 : ℕ) : ℤ)).toNat) = i.1 := by simp
    rw [hcast]
    exact congrFun h i

end Coupling

/-! ## Phase G — forward filtration of finite past + `pmfLogCond` Levy

The forward filtration is the monotone (in `ℕ`) family of σ-algebras `pastSigma k`
of events depending only on the **finite past** `{coord_i : -k ≤ i ≤ -1}` of length
`k`. As `k → ∞`, the filtration's `⨆`-limit is the σ-algebra
`cylinderEvents {i : ℤ | i ≤ -1}` of the **infinite negative past**.

This is the shape needed by **`MeasureTheory.Integrable.tendsto_ae_condExp`**
(forward Lévy upward convergence): if `g` is `(⨆ k, ℱ k)`-strongly measurable
and integrable, then `μ[g | ℱ k] → g` a.s.

For each `a : α`, the real-valued process
`condProbPast a k := μZ[ (coord0 ⁻¹' {a}).indicator (1 : (ℤ→α)→ℝ) | pastFiltration k ]`
is a martingale (via `martingale_condExp`). The infinite-past conditional
probability `condProbInfty a` is defined directly as the conditional
expectation with respect to `⨆ k, pastFiltration k`; forward Lévy then gives
`condProbPast a k → condProbInfty a` a.s.

The per-step conditional log-likelihood is then
`pmfLogCondPast k ω := -log ( ∑ a, indicator(coord0 ω = a) * condProbPast a k ω )`,
which collapses pointwise to `-log condProbPast (coord0 ω) k ω`.

The terminal integral identity
`∫ pmfLogCondInfty dμZ = entropyRate μ p` is the SMB bridge: it follows from
the per-step identity `∫ pmfLogCondPast k dμZ = conditionalEntropyTail μ p k`
(via the joint-law equality of Phase B's `shiftedMarginal`) and DCT pushed
through forward Lévy + `entropyRate_eq_lim_condEntropy`.
-/

section Backward

variable (μ : Measure Ω) [IsProbabilityMeasure μ] (p : StationaryProcess μ α)

/-- The σ-algebra of events depending only on the finite past
`{coord_i : -k ≤ i ≤ -1}` of length `k`. For `k = 0` this is the trivial
σ-algebra (the set `{i | 0 ≤ i ∧ i ≤ -1}` is empty). -/
@[reducible] def pastSigma (k : ℕ) : MeasurableSpace (∀ _ : ℤ, α) :=
  cylinderEvents (X := fun _ : ℤ => α) {i : ℤ | -(k : ℤ) ≤ i ∧ i ≤ -1}

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- `pastSigma` is monotone in `k` (longer past = larger σ-algebra). -/
lemma pastSigma_mono : Monotone (pastSigma (α := α)) := by
  intro k₁ k₂ hk
  -- `{i | -k₁ ≤ i ∧ i ≤ -1} ⊆ {i | -k₂ ≤ i ∧ i ≤ -1}` because `-k₂ ≤ -k₁`.
  have hsub : {i : ℤ | -(k₁ : ℤ) ≤ i ∧ i ≤ -1} ⊆ {i : ℤ | -(k₂ : ℤ) ≤ i ∧ i ≤ -1} := by
    intro i ⟨h_lo, h_hi⟩
    refine ⟨?_, h_hi⟩
    have h_neg : -(k₂ : ℤ) ≤ -(k₁ : ℤ) :=
      neg_le_neg (by exact_mod_cast hk)
    exact le_trans h_neg h_lo
  exact cylinderEvents_mono (X := fun _ : ℤ => α) hsub

/-- The forward past filtration on `ℕ`: `pastFiltration k` is `pastSigma k`,
the σ-algebra of events depending on the finite past `{coord_i : -k ≤ i ≤ -1}`. -/
def pastFiltration : Filtration ℕ
    (MeasurableSpace.pi : MeasurableSpace (∀ _ : ℤ, α)) where
  seq k := pastSigma (α := α) k
  mono' _ _ hij := pastSigma_mono (α := α) hij
  le' _ := cylinderEvents_le_pi

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
@[simp] lemma pastFiltration_apply (k : ℕ) :
    (pastFiltration (α := α)) k = pastSigma (α := α) k := rfl

/-- The σ-algebra of events depending on the **infinite negative past**
`{coord_i : i ≤ -1}`. This is `⨆ k, pastSigma k`. -/
@[reducible] def negPastSigma : MeasurableSpace (∀ _ : ℤ, α) :=
  cylinderEvents (X := fun _ : ℤ => α) {i : ℤ | i ≤ -1}

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- The supremum of the forward past filtration is the infinite negative past
σ-algebra.

Unfolds `cylinderEvents` as `⨆ i ∈ Δ, (m i).comap (· i)` and rearranges the
nested `iSup`s: for any `i ≤ -1`, `i ∈ [-k, -1]` for `k := (-i).toNat`. -/
lemma iSup_pastSigma_eq_negPastSigma :
    ⨆ k : ℕ, pastSigma (α := α) k = negPastSigma (α := α) := by
  -- Unfold both sides to the generator iSup form.
  -- LHS = ⨆ k, ⨆ i ∈ [-k,-1], (m_α).comap (· i)
  -- RHS = ⨆ i ≤ -1, (m_α).comap (· i)
  apply le_antisymm
  · -- LHS ⊆ RHS: each `pastSigma k` has indices ⊆ {i ≤ -1}.
    refine iSup_le (fun k => ?_)
    refine cylinderEvents_mono (X := fun _ : ℤ => α) ?_
    rintro i ⟨_, h_hi⟩
    exact h_hi
  · -- RHS ⊆ LHS: each generator at index `i ≤ -1` sits inside `pastSigma ((-i).toNat)`.
    -- Use the `cylinderEvents = ⨆ i ∈ Δ, ...` unfolding.
    show cylinderEvents (X := fun _ : ℤ => α) {i : ℤ | i ≤ -1}
        ≤ ⨆ k : ℕ, cylinderEvents (X := fun _ : ℤ => α)
            {i : ℤ | -(k : ℤ) ≤ i ∧ i ≤ -1}
    refine iSup₂_le (fun i hi => ?_)
    -- Goal: `(m_α).comap (· i) ≤ ⨆ k, pastSigma k`.
    set k : ℕ := (-i).toNat with hk_def
    have hi_neg : i ≤ -1 := hi
    have hi_le0 : i ≤ (0 : ℤ) := le_trans hi (by norm_num)
    have hk_eq : ((k : ℤ)) = -i :=
      Int.toNat_of_nonneg (neg_nonneg.mpr hi_le0)
    have h_lo : -(k : ℤ) ≤ i := by omega
    have h_hi : i ≤ -1 := hi
    -- `(m_α).comap (· i) ≤ pastSigma k` because `i ∈ [-k,-1]`.
    have h_in_pastSigma_k :
        ((inferInstance : MeasurableSpace α).comap (fun x : (∀ _ : ℤ, α) => x i))
          ≤ pastSigma (α := α) k := by
      change ((inferInstance : MeasurableSpace α).comap (fun x : (∀ _ : ℤ, α) => x i))
          ≤ ⨆ j ∈ ({i : ℤ | -(k : ℤ) ≤ i ∧ i ≤ -1} : Set ℤ),
              ((inferInstance : MeasurableSpace α).comap (fun x : (∀ _ : ℤ, α) => x j))
      exact le_iSup₂ (f := fun j _ =>
        ((inferInstance : MeasurableSpace α).comap (fun x : (∀ _ : ℤ, α) => x j))) i ⟨h_lo, h_hi⟩
    exact le_trans h_in_pastSigma_k (le_iSup (fun k : ℕ => pastSigma (α := α) k) k)

/-- The coordinate-0 evaluation. -/
def coord0 : (∀ _ : ℤ, α) → α := fun x => x 0

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- The coordinate-0 map is measurable. -/
theorem measurable_coord0 : Measurable (coord0 : (∀ _ : ℤ, α) → α) :=
  measurable_pi_apply 0

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSpace α]
  [MeasurableSingletonClass α] [IsProbabilityMeasure μ] in
/-- The indicator of `{coord0 = a}` is bounded by `1`. -/
lemma indicator_coord0_eq_le_one (a : α) (x : (∀ _ : ℤ, α)) :
    ((coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ))) x ≤ 1 := by
  by_cases hx : x ∈ (coord0 ⁻¹' {a})
  · simp [Set.indicator_of_mem hx]
  · simp [Set.indicator_of_notMem hx]

omit [Fintype α] [DecidableEq α] [Nonempty α] [MeasurableSpace α]
  [MeasurableSingletonClass α] [IsProbabilityMeasure μ] in
/-- The indicator of `{coord0 = a}` is nonneg. -/
lemma indicator_coord0_eq_nonneg (a : α) (x : (∀ _ : ℤ, α)) :
    0 ≤ ((coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ))) x := by
  by_cases hx : x ∈ (coord0 ⁻¹' {a})
  · simp [Set.indicator_of_mem hx]
  · simp [Set.indicator_of_notMem hx]

omit [Fintype α] [DecidableEq α] [Nonempty α] [IsProbabilityMeasure μ] in
/-- The set `{coord0 = a}` is measurable. -/
lemma measurableSet_coord0_eq (a : α) :
    MeasurableSet (coord0 ⁻¹' {a} : Set (∀ _ : ℤ, α)) :=
  measurable_coord0 (measurableSet_singleton a)

omit [DecidableEq α] [Nonempty α] in
/-- The indicator function `(coord0 ⁻¹' {a}).indicator 1` is integrable under `μZ`. -/
lemma integrable_indicator_coord0_eq (a : α) :
    Integrable ((coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ))) (μZ μ p) := by
  refine (integrable_indicator_iff (measurableSet_coord0_eq (α := α) a)).mpr ?_
  exact integrableOn_const

/-- The real-valued forward conditional probability of `{coord0 = a}` given
the finite past `pastFiltration k`, viewed as a function on `ℤ → α`. -/
noncomputable def condProbPast (a : α) (k : ℕ) : (∀ _ : ℤ, α) → ℝ :=
  (μZ μ p)[((coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)))
    | (pastFiltration (α := α)) k]

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- For each `a : α`, `condProbPast a` is a (forward) martingale w.r.t. the past
filtration. -/
lemma martingale_condProbPast (a : α) :
    Martingale (fun k : ℕ => (μZ μ p)[((coord0 ⁻¹' {a}).indicator
        (fun _ => (1 : ℝ))) | (pastFiltration (α := α)) k])
      (pastFiltration (α := α)) (μZ μ p) :=
  martingale_condExp _ _ _

/-- The infinite-past conditional probability of `{coord0 = a}` given
`⨆ k, pastFiltration k`. -/
noncomputable def condProbInfty (a : α) : (∀ _ : ℤ, α) → ℝ :=
  (μZ μ p)[((coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)))
    | ⨆ k : ℕ, (pastFiltration (α := α)) k]

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- **Forward Lévy upward convergence**: `condProbPast a k → condProbInfty a` a.s.
as `k → ∞`. Direct application of
`MeasureTheory.Integrable.tendsto_ae_condExp` (Lévy's upward theorem). -/
lemma condProbPast_tendsto_condProbInfty (a : α) :
    ∀ᵐ x ∂(μZ μ p),
      Tendsto (fun k : ℕ => condProbPast μ p a k x) atTop
        (𝓝 (condProbInfty μ p a x)) := by
  -- `tendsto_ae_condExp` gives `μ[g | ℱ k] → μ[g | ⨆ k, ℱ k]` a.s. for any `g`.
  exact MeasureTheory.tendsto_ae_condExp (ℱ := pastFiltration (α := α))
    (μ := μZ μ p) (m0 := MeasurableSpace.pi)
    ((coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)))

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `condProbPast a k` is integrable. -/
lemma integrable_condProbPast (a : α) (k : ℕ) :
    Integrable (condProbPast μ p a k) (μZ μ p) :=
  integrable_condExp

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `condProbPast a k` is strongly measurable w.r.t. `pastFiltration k`. -/
lemma stronglyMeasurable_condProbPast (a : α) (k : ℕ) :
    StronglyMeasurable[(pastFiltration (α := α)) k]
      (condProbPast μ p a k) :=
  stronglyMeasurable_condExp

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `condProbInfty a` is `⨆ k, pastFiltration k`-strongly measurable. -/
lemma stronglyMeasurable_condProbInfty (a : α) :
    StronglyMeasurable[⨆ n : ℕ, (pastFiltration (α := α)) n]
      (condProbInfty μ p a) :=
  stronglyMeasurable_condExp

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `condProbPast a k ≥ 0` a.s. -/
lemma ae_zero_le_condProbPast (a : α) (k : ℕ) :
    0 ≤ᵐ[μZ μ p] condProbPast μ p a k := by
  refine condExp_nonneg ?_
  filter_upwards with x
  exact indicator_coord0_eq_nonneg a x

omit [DecidableEq α] [Nonempty α] in
/-- `condProbPast a k ≤ 1` a.s. -/
lemma ae_condProbPast_le_one (a : α) (k : ℕ) :
    condProbPast μ p a k ≤ᵐ[μZ μ p] (fun _ => (1 : ℝ)) := by
  have h_mono :
      (μZ μ p)[(coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ))
          | (pastFiltration (α := α)) k]
        ≤ᵐ[μZ μ p] (μZ μ p)[(fun _ : (∀ _ : ℤ, α) => (1 : ℝ))
          | (pastFiltration (α := α)) k] := by
    refine condExp_mono (integrable_indicator_coord0_eq μ p a)
      (integrable_const _) ?_
    filter_upwards with x
    exact indicator_coord0_eq_le_one a x
  have h_const_eq :
      (μZ μ p)[(fun _ : (∀ _ : ℤ, α) => (1 : ℝ))
          | (pastFiltration (α := α)) k]
        = fun _ => (1 : ℝ) :=
    condExp_const ((pastFiltration (α := α)).le _) 1
  filter_upwards [h_mono] with x hx
  have := hx
  rw [h_const_eq] at this
  exact this

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `condProbInfty a ≥ 0` a.s. -/
lemma ae_zero_le_condProbInfty (a : α) :
    0 ≤ᵐ[μZ μ p] condProbInfty μ p a := by
  have h_tendsto := condProbPast_tendsto_condProbInfty μ p a
  -- For each x in the AE-set, we have `condProbPast a k x → condProbInfty a x` and each
  -- `condProbPast a k x ≥ 0` a.s. Pick a fixed `k = 0` AE-set and pass to limit.
  have h_nn : ∀ᵐ x ∂(μZ μ p), ∀ k : ℕ, 0 ≤ condProbPast μ p a k x := by
    rw [ae_all_iff]; exact fun k => ae_zero_le_condProbPast μ p a k
  filter_upwards [h_tendsto, h_nn] with x hx_lim hx_nn
  exact ge_of_tendsto' hx_lim hx_nn

omit [DecidableEq α] [Nonempty α] in
/-- `condProbInfty a ≤ 1` a.s. -/
lemma ae_condProbInfty_le_one (a : α) :
    condProbInfty μ p a ≤ᵐ[μZ μ p] (fun _ => (1 : ℝ)) := by
  have h_tendsto := condProbPast_tendsto_condProbInfty μ p a
  have h_le : ∀ᵐ x ∂(μZ μ p), ∀ k : ℕ, condProbPast μ p a k x ≤ 1 := by
    rw [ae_all_iff]; exact fun k => ae_condProbPast_le_one μ p a k
  filter_upwards [h_tendsto, h_le] with x hx_lim hx_le
  exact le_of_tendsto' hx_lim hx_le

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- `condProbInfty a` is by definition the conditional expectation of the indicator
`1_{coord0=a}` w.r.t. the σ-algebra `⨆ k, pastFiltration k` of the infinite past. -/
lemma condProbInfty_eq_condExp_tail (a : α) :
    condProbInfty μ p a =ᵐ[μZ μ p]
      (μZ μ p)[(coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ))
        | ⨆ n : ℕ, (pastFiltration (α := α)) n] := by
  exact Filter.EventuallyEq.refl _ _

/-- Per-step conditional log-likelihood under `μZ` conditioned on `pastSigma k`.

Defined as `-log (∑ a, indicator(coord0 = a) * condProbPast a k)`. On the
full-measure set where the conditional probability of the actual `coord0` value
is positive, this is `-log condProbPast (coord0 x) k x`. -/
noncomputable def pmfLogCondPast (k : ℕ) : (∀ _ : ℤ, α) → ℝ := fun x =>
  -Real.log (∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
    * condProbPast μ p a k x)

/-- Limit log-likelihood (conditional on the full backward tail). -/
noncomputable def pmfLogCondInfty : (∀ _ : ℤ, α) → ℝ := fun x =>
  -Real.log (∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
    * condProbInfty μ p a x)

omit [DecidableEq α] [Nonempty α] [MeasurableSpace α] [MeasurableSingletonClass α]
  [IsProbabilityMeasure μ] in
/-- Per-step (and limit) inner sum simplifies to a single conditional probability
of the realized coord-0 value. -/
lemma pmfLogCondPast_inner_eq_self (f : α → ℝ) (x : (∀ _ : ℤ, α)) :
    (∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x * f a)
      = f (coord0 x) := by
  classical
  have hmem : (coord0 x) ∈ (Finset.univ : Finset α) := Finset.mem_univ _
  rw [Finset.sum_eq_single (coord0 x)]
  · have hin : x ∈ coord0 ⁻¹' {coord0 x} := rfl
    rw [Set.indicator_of_mem hin]
    ring
  · intro a _ hne
    have hnotmem : x ∉ coord0 ⁻¹' {a} := fun hx => hne hx.symm
    simp [Set.indicator_of_notMem hnotmem]
  · intro hne; exact absurd hmem hne

/-! ### Integrability of `pmfLogCondPast` and `pmfLogCondInfty`

The integrand has the pointwise decomposition
`pmfLogCondPast μ p k x = ∑ a, 1_{coord0=a}(x) * (-log condProbPast a k x)`
(indicators partition unity on the singleton `{coord0=a}`, so the inner sum has
a single nonzero summand at `a = coord0 x`).

For each `a`, the summand `1_{coord0=a} * (-log condProbPast a k)` is integrable
via the L¹ tower (`condExp_stronglyMeasurable_mul_of_bound` with a truncated
`-log` factor) + monotone convergence. The truncated bound `F_M := min(M, (-log g)⁺)`
satisfies `∫ (1_{coord0=a}) * F_M = ∫ g * F_M ≤ ∫ negMulLog g ≤ 1`, uniformly in
`M`, so by MCT `∫ (1_{coord0=a}) * (-log g)⁺ ≤ 1`. -/

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- Pointwise decomposition: `pmfLogCondPast μ p k = ∑_a 1_{coord0=a} * (-log condProbPast a k)`.
The inner sum collapses to a single nonzero term at `a = coord0 x`. -/
private lemma pmfLogCondPast_eq_sum_indicator_neg_log (k : ℕ) (x : (∀ _ : ℤ, α)) :
    pmfLogCondPast μ p k x
      = ∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbPast μ p a k x)) := by
  classical
  unfold pmfLogCondPast
  have h_inner :
      (∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * condProbPast μ p a k x) = condProbPast μ p (coord0 x) k x :=
    pmfLogCondPast_inner_eq_self (fun a => condProbPast μ p a k x) x
  have h_sum :
      (∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbPast μ p a k x)))
        = -Real.log (condProbPast μ p (coord0 x) k x) :=
    pmfLogCondPast_inner_eq_self (fun a => -Real.log (condProbPast μ p a k x)) x
  rw [h_inner, h_sum]

omit [DecidableEq α] [Nonempty α] [MeasurableSingletonClass α] in
/-- Analogous decomposition for `pmfLogCondInfty`. -/
private lemma pmfLogCondInfty_eq_sum_indicator_neg_log (x : (∀ _ : ℤ, α)) :
    pmfLogCondInfty μ p x
      = ∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbInfty μ p a x)) := by
  classical
  unfold pmfLogCondInfty
  have h_inner :
      (∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * condProbInfty μ p a x) = condProbInfty μ p (coord0 x) x :=
    pmfLogCondPast_inner_eq_self (fun a => condProbInfty μ p a x) x
  have h_sum :
      (∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbInfty μ p a x)))
        = -Real.log (condProbInfty μ p (coord0 x) x) :=
    pmfLogCondPast_inner_eq_self (fun a => -Real.log (condProbInfty μ p a x)) x
  rw [h_inner, h_sum]

omit [DecidableEq α] [Nonempty α] in
/-- **Auxiliary integrability** (key technical lemma for both integrability theorems).

For any `m`-strongly-measurable `g : (∀ _ : ℤ, α) → ℝ` with `g ∈ [0, 1]` a.s. and
`g =ᵐ μZ[1_{coord0=a} | m]`, the function `1_{coord0=a} · (-log g)` is `μZ`-integrable.

Proof: truncate `(-log g)⁺` to `F_M := min M (-log g)⁺`. Each `F_M` is `m`-measurable and bounded
by `M`. By `condExp_stronglyMeasurable_mul_of_bound`, `μZ[ind · F_M | m] =ᵐ F_M · g` (using
`μZ[ind | m] = g`). Integrating: `∫ ind · F_M = ∫ F_M · g ≤ ∫ negMulLog g ≤ 1`.
Apply MCT (Lebesgue MCT on the `lintegral` form) as `M → ∞`. -/
private lemma integrable_indicator_mul_negLog_of_condExp
    (m : MeasurableSpace (∀ _ : ℤ, α)) (hm : m ≤ MeasurableSpace.pi)
    (a : α) (g : (∀ _ : ℤ, α) → ℝ)
    (hg_meas_m : StronglyMeasurable[m] g)
    (hg_eq_ce : g =ᵐ[μZ μ p]
      (μZ μ p)[(coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)) | m])
    (hg_nn : 0 ≤ᵐ[μZ μ p] g)
    (hg_le : g ≤ᵐ[μZ μ p] (fun _ => (1 : ℝ))) :
    Integrable (fun x => (coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)) x
      * (-Real.log (g x))) (μZ μ p) := by
  classical
  set ind : (∀ _ : ℤ, α) → ℝ :=
    (coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)) with hind_def
  have h_g_m : Measurable[m] g := hg_meas_m.measurable
  have h_meas_g : @Measurable _ _ MeasurableSpace.pi _ g :=
    @Measurable.mono _ _ m MeasurableSpace.pi _ _ g h_g_m hm le_rfl
  have h_meas_log_g : @Measurable _ _ MeasurableSpace.pi _ (fun x => Real.log (g x)) :=
    Real.measurable_log.comp h_meas_g
  have h_meas_ind : @Measurable _ _ MeasurableSpace.pi _ ind := by
    refine Measurable.indicator measurable_const ?_
    exact measurableSet_coord0_eq a
  have h_int_ind : Integrable ind (μZ μ p) := integrable_indicator_coord0_eq μ p a
  have h_ind_nn : ∀ x, 0 ≤ ind x := indicator_coord0_eq_nonneg a
  have h_ind_le : ∀ x, ind x ≤ 1 := indicator_coord0_eq_le_one a
  -- Truncated factor `F_M(x) := min ((-log g x)⁺) M`. m-measurable and bounded by M.
  set F : ℕ → (∀ _ : ℤ, α) → ℝ := fun M x => min ((-Real.log (g x))⁺) M with hF_def
  have h_neg_log_m : Measurable[m] (fun x => -Real.log (g x)) :=
    (Real.measurable_log.comp h_g_m).neg
  have h_pos_part_m : Measurable[m] (fun x => (-Real.log (g x))⁺) :=
    h_neg_log_m.max measurable_const
  have hF_meas_m : ∀ M, StronglyMeasurable[m] (F M) := by
    intro M
    exact (h_pos_part_m.min measurable_const).stronglyMeasurable
  have hF_nn : ∀ M x, 0 ≤ F M x := fun M x =>
    le_min (le_max_right _ _) M.cast_nonneg
  have hF_bound : ∀ M x, F M x ≤ M := fun M x => min_le_right _ _
  have hF_mono : ∀ x, Monotone (fun M : ℕ => F M x) := by
    intro x M N hMN
    exact min_le_min le_rfl (by exact_mod_cast hMN)
  have hF_tendsto : ∀ x, Tendsto (fun M : ℕ => F M x) atTop (𝓝 ((-Real.log (g x))⁺)) := by
    intro x
    obtain ⟨N, hN⟩ := exists_nat_ge ((-Real.log (g x))⁺)
    rw [Metric.tendsto_atTop]
    intro ε hε
    refine ⟨N, fun M hM => ?_⟩
    have hMbig : (N : ℝ) ≤ (M : ℝ) := by exact_mod_cast hM
    have h_pos_part_le_M : (-Real.log (g x))⁺ ≤ (M : ℝ) := hN.trans hMbig
    have hFM : F M x = (-Real.log (g x))⁺ := min_eq_left h_pos_part_le_M
    rw [hFM]; simp [hε]
  -- F M is bounded by M (as a real norm), hence integrable; ind * F M integrable via
  -- `Integrable.bdd_mul` (with bounded factor F M).
  have hF_norm_bound : ∀ M x, ‖F M x‖ ≤ (M : ℝ) := by
    intro M x
    rw [Real.norm_eq_abs]
    exact abs_le.mpr ⟨by have := hF_nn M x; linarith, hF_bound M x⟩
  have hF_meas : ∀ M, @Measurable _ _ MeasurableSpace.pi _ (F M) :=
    fun M => ((hF_meas_m M).mono hm).measurable
  -- Pull-out for each M: μZ[ind * F M | m] =ᵐ F M * g. We compute via
  -- `condExp_stronglyMeasurable_mul_of_bound` applied to (F M * ind) (F M is the bounded
  -- m-measurable factor); then commute *.
  have h_pullout_step1 : ∀ M,
      (μZ μ p)[fun x => F M x * ind x | m] =ᵐ[μZ μ p]
        fun x => F M x * (μZ μ p)[ind | m] x := by
    intro M
    refine condExp_stronglyMeasurable_mul_of_bound hm (hF_meas_m M) h_int_ind (M : ℝ) ?_
    filter_upwards with x using hF_norm_bound M x
  have h_pullout : ∀ M,
      (μZ μ p)[fun x => F M x * ind x | m] =ᵐ[μZ μ p] fun x => F M x * g x := by
    intro M
    refine (h_pullout_step1 M).trans ?_
    filter_upwards [hg_eq_ce] with x hxg
    rw [hxg]
  -- Integrability of ind * F M (and F M * ind).
  have h_int_FM_ind : ∀ M, Integrable (fun x => ind x * F M x) (μZ μ p) := by
    intro M
    refine Integrable.mul_bdd (c := (M : ℝ)) h_int_ind (hF_meas M).aestronglyMeasurable ?_
    filter_upwards with x using hF_norm_bound M x
  have h_int_FM_ind' : ∀ M, Integrable (fun x => F M x * ind x) (μZ μ p) := by
    intro M
    refine (h_int_FM_ind M).congr ?_
    filter_upwards with x using by ring
  -- Bound F M x * g x ≤ negMulLog (g x) a.s. (key inequality).
  have h_bound : ∀ M, ∀ᵐ x ∂(μZ μ p), F M x * g x ≤ Real.negMulLog (g x) := by
    intro M
    filter_upwards [hg_nn, hg_le] with x hx_nn hx_le
    have hx_nn' : (0 : ℝ) ≤ g x := hx_nn
    have hlog_np : Real.log (g x) ≤ 0 := Real.log_nonpos hx_nn' hx_le
    have hneg_log_nn : 0 ≤ -Real.log (g x) := neg_nonneg.mpr hlog_np
    have h_pos_part : (-Real.log (g x))⁺ = -Real.log (g x) := max_eq_left hneg_log_nn
    have h_FM_le : F M x ≤ -Real.log (g x) := by
      have h1 : F M x ≤ (-Real.log (g x))⁺ := min_le_left _ _
      rwa [h_pos_part] at h1
    calc F M x * g x ≤ (-Real.log (g x)) * g x :=
          mul_le_mul_of_nonneg_right h_FM_le hx_nn'
      _ = Real.negMulLog (g x) := by rw [Real.negMulLog]; ring
  -- Integrability of negMulLog g (bounded by 1 - g ≤ 1).
  have h_meas_negMulLog : @Measurable _ _ MeasurableSpace.pi _ (fun x => Real.negMulLog (g x)) :=
    Real.continuous_negMulLog.measurable.comp h_meas_g
  have h_int_negMulLog : Integrable (fun x => Real.negMulLog (g x)) (μZ μ p) := by
    refine Integrable.mono (integrable_const (1 : ℝ)) h_meas_negMulLog.aestronglyMeasurable ?_
    filter_upwards [hg_nn, hg_le] with x hx_nn hx_le
    have hx_nn' : (0 : ℝ) ≤ g x := hx_nn
    rw [Real.norm_eq_abs, abs_of_nonneg (Real.negMulLog_nonneg hx_nn' hx_le),
      Real.norm_eq_abs, abs_of_nonneg zero_le_one]
    have h1 : Real.negMulLog (g x) ≤ 1 - g x := Real.negMulLog_le_one_sub_self hx_nn'
    linarith
  have h_int_FM_g : ∀ M, Integrable (fun x => F M x * g x) (μZ μ p) := by
    intro M
    refine Integrable.mono h_int_negMulLog
      (((hF_meas M).mul h_meas_g).aestronglyMeasurable) ?_
    filter_upwards [h_bound M, hg_nn, hg_le] with x hx_b hx_nn hx_le
    have hx_nn' : (0 : ℝ) ≤ g x := hx_nn
    have h_nn' : 0 ≤ F M x * g x := mul_nonneg (hF_nn M x) hx_nn'
    rw [Real.norm_eq_abs, abs_of_nonneg h_nn',
      Real.norm_eq_abs, abs_of_nonneg (Real.negMulLog_nonneg hx_nn' hx_le)]
    exact hx_b
  -- Integral identity per M: ∫ F M * ind = ∫ μZ[F M * ind | m] = ∫ F M * g.
  have h_int_eq : ∀ M,
      ∫ x, F M x * ind x ∂(μZ μ p) = ∫ x, F M x * g x ∂(μZ μ p) := by
    intro M
    have h1 : ∫ x, F M x * ind x ∂(μZ μ p)
        = ∫ x, ((μZ μ p)[fun x => F M x * ind x | m]) x ∂(μZ μ p) :=
      (integral_condExp hm).symm
    rw [h1]
    exact integral_congr_ae (h_pullout M)
  -- ∫ negMulLog g ≤ 1 (probability measure).
  have h_negMulLog_le_one :
      ∫ x, Real.negMulLog (g x) ∂(μZ μ p) ≤ 1 := by
    have h_bd : (fun x => Real.negMulLog (g x)) ≤ᵐ[μZ μ p] fun _ => (1 : ℝ) := by
      filter_upwards [hg_nn, hg_le] with x hx_nn hx_le
      have hx_nn' : (0 : ℝ) ≤ g x := hx_nn
      have : Real.negMulLog (g x) ≤ 1 - g x := Real.negMulLog_le_one_sub_self hx_nn'
      linarith
    calc ∫ x, Real.negMulLog (g x) ∂(μZ μ p)
        ≤ ∫ _, (1 : ℝ) ∂(μZ μ p) :=
          integral_mono_ae h_int_negMulLog (integrable_const _) h_bd
      _ = 1 := by
          rw [integral_const, smul_eq_mul]
          simp
  -- Uniform integral bound per M: ∫ ind * F M ≤ 1.
  have h_uniform_bound : ∀ M, ∫ x, ind x * F M x ∂(μZ μ p) ≤ 1 := by
    intro M
    have h_comm : ∫ x, ind x * F M x ∂(μZ μ p) = ∫ x, F M x * ind x ∂(μZ μ p) := by
      refine integral_congr_ae ?_; filter_upwards with x using by ring
    rw [h_comm, h_int_eq]
    refine le_trans ?_ h_negMulLog_le_one
    exact integral_mono_ae (h_int_FM_g M) h_int_negMulLog (h_bound M)
  -- Now build Integrable via lintegral bound + MCT.
  -- ‖ind(x) * (-log g(x))‖ₑ = ENNReal.ofReal (ind(x) * (-log g)⁺) a.s.
  have h_eq_pos_part : (fun x => (‖ind x * (-Real.log (g x))‖ₑ : ENNReal))
      =ᵐ[μZ μ p] fun x => ENNReal.ofReal (ind x * (-Real.log (g x))⁺) := by
    filter_upwards [hg_nn, hg_le] with x hx_nn hx_le
    have hx_nn' : (0 : ℝ) ≤ g x := hx_nn
    have hlog_np : Real.log (g x) ≤ 0 := Real.log_nonpos hx_nn' hx_le
    have hneg_log_nn : 0 ≤ -Real.log (g x) := neg_nonneg.mpr hlog_np
    have h_pos_part : (-Real.log (g x))⁺ = -Real.log (g x) := max_eq_left hneg_log_nn
    have hprod_nn : 0 ≤ ind x * (-Real.log (g x)) :=
      mul_nonneg (h_ind_nn x) hneg_log_nn
    rw [h_pos_part]
    exact Real.enorm_eq_ofReal hprod_nn
  -- The product ind * (-log g) is AEStronglyMeasurable.
  have h_meas_prod_pi : @Measurable _ _ MeasurableSpace.pi _
      (fun x => ind x * (-Real.log (g x))) :=
    h_meas_ind.mul h_meas_log_g.neg
  have h_meas_prod : AEStronglyMeasurable[MeasurableSpace.pi]
      (fun x => ind x * (-Real.log (g x))) (μZ μ p) :=
    h_meas_prod_pi.aestronglyMeasurable
  refine ⟨h_meas_prod, ?_⟩
  rw [hasFiniteIntegral_iff_enorm, lintegral_congr_ae h_eq_pos_part]
  -- ENNReal-of-real-integral identity per M.
  have h_ind_FM_nn : ∀ M x, 0 ≤ ind x * F M x := fun M x =>
    mul_nonneg (h_ind_nn x) (hF_nn M x)
  have h_lintegral_eq : ∀ M,
      ∫⁻ x, ENNReal.ofReal (ind x * F M x) ∂(μZ μ p)
        = ENNReal.ofReal (∫ x, ind x * F M x ∂(μZ μ p)) := by
    intro M
    rw [← ofReal_integral_eq_lintegral_ofReal]
    · refine (h_int_FM_ind M)
    · filter_upwards with x using h_ind_FM_nn M x
  have h_lintegral_bound : ∀ M,
      ∫⁻ x, ENNReal.ofReal (ind x * F M x) ∂(μZ μ p) ≤ 1 := by
    intro M
    rw [h_lintegral_eq M]
    exact_mod_cast ENNReal.ofReal_le_one.mpr (h_uniform_bound M)
  -- MCT (monotone increasing supremum).
  have h_mono : ∀ x, Monotone (fun M => ENNReal.ofReal (ind x * F M x)) := by
    intro x M N hMN
    apply ENNReal.ofReal_le_ofReal
    exact mul_le_mul_of_nonneg_left (hF_mono x hMN) (h_ind_nn x)
  have h_tendsto : ∀ x, Tendsto (fun M => ENNReal.ofReal (ind x * F M x)) atTop
      (𝓝 (ENNReal.ofReal (ind x * (-Real.log (g x))⁺))) := by
    intro x
    refine (ENNReal.continuous_ofReal.tendsto _).comp ?_
    exact (hF_tendsto x).const_mul (ind x)
  have h_meas_FM_ENN : ∀ M, @Measurable _ _ MeasurableSpace.pi _
      (fun x => ENNReal.ofReal (ind x * F M x)) :=
    fun M => ENNReal.continuous_ofReal.measurable.comp (h_meas_ind.mul (hF_meas M))
  have h_supr_eq : ∫⁻ x, ENNReal.ofReal (ind x * (-Real.log (g x))⁺) ∂(μZ μ p)
      = ⨆ M, ∫⁻ x, ENNReal.ofReal (ind x * F M x) ∂(μZ μ p) := by
    rw [show (fun x => ENNReal.ofReal (ind x * (-Real.log (g x))⁺))
        = fun x => ⨆ M, ENNReal.ofReal (ind x * F M x) by
      funext x
      exact (iSup_eq_of_tendsto (h_mono x) (h_tendsto x)).symm]
    exact lintegral_iSup h_meas_FM_ENN (fun M N hMN x => h_mono x hMN)
  rw [h_supr_eq]
  refine lt_of_le_of_lt (iSup_le h_lintegral_bound) ?_
  exact ENNReal.one_lt_top

omit [DecidableEq α] [Nonempty α] in
/-- Integrability of `pmfLogCondPast k`.

The integrand `-log(condProbPast (coord0 x) k x)` decomposes as `∑_a 1_{coord0=a}(x)
* (-log condProbPast a k x)`. Each summand is integrable via
`integrable_indicator_mul_negLog_of_condExp` applied at `m := pastFiltration k`,
using the defining identity `condProbPast a k = μZ[1_{coord0=a} | pastFiltration k]`
and the `[0,1]` bound. The sum of finitely many integrable functions is integrable. -/
theorem integrable_pmfLogCondPast (k : ℕ) :
    Integrable (pmfLogCondPast μ p k) (μZ μ p) := by
  classical
  have h_eq : pmfLogCondPast μ p k = fun x =>
      ∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbPast μ p a k x)) := by
    funext x
    exact pmfLogCondPast_eq_sum_indicator_neg_log μ p k x
  rw [h_eq]
  refine integrable_finsetSum _ (fun a _ => ?_)
  refine integrable_indicator_mul_negLog_of_condExp μ p
    ((pastFiltration (α := α)) k)
    ((pastFiltration (α := α)).le _)
    a (condProbPast μ p a k)
    (stronglyMeasurable_condProbPast μ p a k)
    ?_ (ae_zero_le_condProbPast μ p a k) (ae_condProbPast_le_one μ p a k)
  exact Filter.EventuallyEq.refl _ _

omit [DecidableEq α] [Nonempty α] in
/-- Integrability of `pmfLogCondInfty`.

Same argument as `integrable_pmfLogCondPast`, but applied to the infinite-past
limit `condProbInfty a`, which is by definition the condExp of the indicator
w.r.t. the σ-algebra `⨆ k, pastFiltration k` of the infinite past. -/
theorem integrable_pmfLogCondInfty :
    Integrable (pmfLogCondInfty μ p) (μZ μ p) := by
  classical
  have h_eq : pmfLogCondInfty μ p = fun x =>
      ∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbInfty μ p a x)) := by
    funext x
    exact pmfLogCondInfty_eq_sum_indicator_neg_log μ p x
  rw [h_eq]
  refine integrable_finsetSum _ (fun a _ => ?_)
  -- `condProbInfty a := μZ[ind | ⨆ k, pastFiltration k]` by definition.
  refine integrable_indicator_mul_negLog_of_condExp μ p
    (⨆ n : ℕ, (pastFiltration (α := α)) n)
    (iSup_le (fun n => (pastFiltration (α := α)).le n))
    a (condProbInfty μ p a)
    (stronglyMeasurable_condProbInfty μ p a) ?_
    (ae_zero_le_condProbInfty μ p a) (ae_condProbInfty_le_one μ p a)
  exact condProbInfty_eq_condExp_tail μ p a

omit [DecidableEq α] [Nonempty α] in
/-- **AE positivity of the realized conditional probability**.

Almost surely under `μZ`, the infinite-past conditional probability of the
realized `coord0` value is strictly positive. This is a standard fact: the
indicator `1_{coord0 = coord0 x}` is exactly 1 at `x`, and the conditional
expectation w.r.t. `⨆ k, pastFiltration k` of an indicator-of-a-set has total
mass equal to that set's measure. Positivity on a full-measure set follows from
the integral identity `∫_E condProbInfty (coord0 x) = (μZ μ p)({coord0 = a} ∩ E)`.

Used inside `pmfLogCondPast_tendsto_pmfLogCondInfty` to handle `Real.log`
discontinuity at 0. -/
lemma ae_condProbInfty_coord0_pos :
    ∀ᵐ x ∂(μZ μ p), 0 < condProbInfty μ p (coord0 x) x := by
  classical
  -- Infinite-past σ-algebra.
  set m_inf : MeasurableSpace (∀ _ : ℤ, α) :=
    ⨆ n : ℕ, (pastFiltration (α := α)) n with hm_inf_def
  have hm_inf_le : m_inf ≤ MeasurableSpace.pi :=
    iSup_le (fun n => (pastFiltration (α := α)).le n)
  -- For each `a`, the "bad" set `E_a := {coord0 = a} ∩ {condProbInfty a ≤ 0}` has μZ-measure 0.
  have h_bad_zero : ∀ a : α,
      (μZ μ p) ((coord0 ⁻¹' {a}) ∩ {x | condProbInfty μ p a x ≤ 0}) = 0 := by
    intro a
    set E : Set (∀ _ : ℤ, α) := {x | condProbInfty μ p a x ≤ 0} with hE_def
    set indf : (∀ _ : ℤ, α) → ℝ :=
      (coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)) with hindf_def
    have h_sm : StronglyMeasurable[m_inf] (condProbInfty μ p a) :=
      stronglyMeasurable_condProbInfty μ p a
    have hE_m : MeasurableSet[m_inf] E :=
      h_sm.measurableSet_le stronglyMeasurable_const
    have hE_pi : @MeasurableSet _ MeasurableSpace.pi E := hm_inf_le _ hE_m
    have h_coord_pi : @MeasurableSet _ MeasurableSpace.pi (coord0 ⁻¹' {a}) :=
      measurableSet_coord0_eq a
    have h_int_indf : Integrable indf (μZ μ p) := integrable_indicator_coord0_eq μ p a
    -- Step 1: ∫_E indf dμZ = ∫_E condProbInfty a dμZ.
    have h_setInt_E :
        ∫ x in E, indf x ∂(μZ μ p) = ∫ x in E, condProbInfty μ p a x ∂(μZ μ p) := by
      have h1 : ∫ x in E, indf x ∂(μZ μ p)
          = ∫ x in E, ((μZ μ p)[indf | m_inf]) x ∂(μZ μ p) :=
        (setIntegral_condExp hm_inf_le h_int_indf hE_m).symm
      have h2 : ∫ x in E, ((μZ μ p)[indf | m_inf]) x ∂(μZ μ p)
          = ∫ x in E, condProbInfty μ p a x ∂(μZ μ p) := by
        refine setIntegral_congr_ae (hm_inf_le _ hE_m) ?_
        filter_upwards [condProbInfty_eq_condExp_tail μ p a] with x hx _
        exact hx.symm
      exact h1.trans h2
    -- Step 2: LHS = μZ ({coord0=a} ∩ E) (as real). Use integral_indicator.
    have h_lhs : ∫ x in E, indf x ∂(μZ μ p)
        = (μZ μ p).real ((coord0 ⁻¹' {a}) ∩ E) := by
      rw [hindf_def, integral_indicator h_coord_pi, integral_const, smul_eq_mul, mul_one,
        Measure.restrict_restrict h_coord_pi, Measure.real, Measure.real]
      simp only [Measure.restrict_apply MeasurableSet.univ, Set.univ_inter]
    -- Step 3: RHS ≤ 0 since condProbInfty a ≤ 0 on E.
    have h_rhs_le_zero : ∫ x in E, condProbInfty μ p a x ∂(μZ μ p) ≤ 0 := by
      refine MeasureTheory.setIntegral_nonpos hE_pi (fun x hx => hx)
    -- Step 4: RHS ≥ 0 since condProbInfty a ≥ 0 a.s.
    have h_rhs_nonneg : 0 ≤ ∫ x in E, condProbInfty μ p a x ∂(μZ μ p) := by
      refine MeasureTheory.integral_nonneg_of_ae ?_
      filter_upwards [ae_restrict_of_ae (ae_zero_le_condProbInfty μ p a)] with x hx
      exact hx
    -- Step 5: RHS = 0, hence LHS = 0, hence μZ ({coord0=a} ∩ E).real = 0.
    have h_rhs_zero : ∫ x in E, condProbInfty μ p a x ∂(μZ μ p) = 0 :=
      le_antisymm h_rhs_le_zero h_rhs_nonneg
    have h_lhs_zero : (μZ μ p).real ((coord0 ⁻¹' {a}) ∩ E) = 0 := by
      rw [← h_lhs, h_setInt_E, h_rhs_zero]
    -- Conclude `μZ (E_a) = 0` (ENNReal).
    have h_lt_top : (μZ μ p) ((coord0 ⁻¹' {a}) ∩ E) < ⊤ :=
      measure_lt_top _ _
    rw [Measure.real, ENNReal.toReal_eq_zero_iff] at h_lhs_zero
    exact h_lhs_zero.resolve_right h_lt_top.ne
  -- Now combine: μZ {x | condProbInfty (coord0 x) x ≤ 0} ≤ ∑_a μZ E_a = 0.
  rw [ae_iff]
  have h_set_eq : {x : (∀ _ : ℤ, α) | ¬ 0 < condProbInfty μ p (coord0 x) x}
      = ⋃ a : α, (coord0 ⁻¹' {a}) ∩ {x | condProbInfty μ p a x ≤ 0} := by
    ext x
    simp only [Set.mem_setOf_eq, not_lt, Set.mem_iUnion, Set.mem_inter_iff,
      Set.mem_preimage, Set.mem_singleton_iff]
    refine ⟨fun hx => ⟨coord0 x, rfl, hx⟩, ?_⟩
    rintro ⟨a, ⟨ha, hle⟩⟩
    rw [show coord0 x = a from ha]
    exact hle
  rw [h_set_eq]
  refine measure_iUnion_null_iff.mpr fun a => ?_
  exact h_bad_zero a

omit [DecidableEq α] [Nonempty α] in
/-- **Forward Lévy upward convergence**: per-step conditional log-likelihood on
longer-and-longer finite past converges to `pmfLogCondInfty`. Application of
`MeasureTheory.tendsto_ae_condExp` (one application per `a : α`, combined
by continuity of `-log` and the inner-sum identity
`∑ a, indicator(coord0=a) * f a = f (coord0 x)`).

**Caveat**: convergence holds on the AE set where
`condProbInfty (coord0 x) x > 0` (provided by `ae_condProbInfty_coord0_pos`);
on the null set where the conditional probability of the realized coord0
value is `0`, `Real.log` is discontinuous, and we report
`pmfLogCondPast/pmfLogCondInfty` as `0` by convention (`Real.log 0 = 0`). -/
theorem pmfLogCondPast_tendsto_pmfLogCondInfty :
    ∀ᵐ x ∂(μZ μ p),
      Tendsto (fun k => pmfLogCondPast μ p k x) atTop
        (𝓝 (pmfLogCondInfty μ p x)) := by
  classical
  -- Combine the `α`-many a.s. convergences `condProbPast a k x → condProbInfty a x`.
  have h_all : ∀ᵐ x ∂(μZ μ p), ∀ a : α,
      Tendsto (fun k : ℕ => condProbPast μ p a k x) atTop
        (𝓝 (condProbInfty μ p a x)) := by
    rw [ae_all_iff]
    exact fun a => condProbPast_tendsto_condProbInfty μ p a
  -- AE positivity of the realized conditional probability `condProbInfty (coord0 x) x`.
  have h_pos := ae_condProbInfty_coord0_pos μ p
  filter_upwards [h_all, h_pos] with x hx hxpos
  -- The realized atom.
  set a₀ : α := coord0 x with ha₀
  -- pmfLogCondPast and pmfLogCondInfty simplify pointwise via `pmfLogCondPast_inner_eq_self`.
  have h_simp_past : ∀ k, pmfLogCondPast μ p k x = -Real.log (condProbPast μ p a₀ k x) := by
    intro k
    unfold pmfLogCondPast
    rw [pmfLogCondPast_inner_eq_self (fun a => condProbPast μ p a k x) x]
  have h_simp_infty :
      pmfLogCondInfty μ p x = -Real.log (condProbInfty μ p a₀ x) := by
    unfold pmfLogCondInfty
    rw [pmfLogCondPast_inner_eq_self (fun a => condProbInfty μ p a x) x]
  rw [h_simp_infty]
  simp_rw [h_simp_past]
  -- Goal: `(fun k => -log (condProbPast a₀ k x)) → -log (condProbInfty a₀ x)`.
  have hlimit : Tendsto (fun k : ℕ => condProbPast μ p a₀ k x) atTop
      (𝓝 (condProbInfty μ p a₀ x)) := hx a₀
  -- `Real.log` is continuous at any positive point.
  have hcont : ContinuousAt Real.log (condProbInfty μ p a₀ x) :=
    Real.continuousAt_log (ne_of_gt hxpos)
  exact (hcont.tendsto.comp hlimit).neg

omit [DecidableEq α] [Nonempty α] in
/-- **Pull-out identity for `pmfLogCondPast`**: integrating
`1_{coord_0=a} * (-log condProbPast a k)` equals integrating
`negMulLog(condProbPast a k)`.

Proof: `(-log condProbPast a k)` is `pastSigma k`-measurable; the indicator
`1_{coord_0=a}` is integrable. By the tower property
(`integral_condExp`) and the pull-out property
(`condExp_mul_of_aestronglyMeasurable_left`), pulling the `m`-measurable
factor out of the conditional expectation gives the result. -/
private lemma integral_indicator_mul_negLog_condProbPast (k : ℕ) (a : α) :
    ∫ x, (coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbPast μ p a k x)) ∂(μZ μ p)
      = ∫ x, Real.negMulLog (condProbPast μ p a k x) ∂(μZ μ p) := by
  classical
  set ind : (∀ _ : ℤ, α) → ℝ :=
    (coord0 ⁻¹' {a}).indicator (fun _ => (1 : ℝ)) with hind_def
  set g : (∀ _ : ℤ, α) → ℝ := condProbPast μ p a k with hg_def
  set m : MeasurableSpace (∀ _ : ℤ, α) := (pastFiltration (α := α)) k with hm_def
  have hm_le : m ≤ MeasurableSpace.pi := (pastFiltration (α := α)).le k
  have h_int_ind : Integrable ind (μZ μ p) := integrable_indicator_coord0_eq μ p a
  have h_int_prod : Integrable (fun x => ind x * (-Real.log (g x))) (μZ μ p) := by
    refine integrable_indicator_mul_negLog_of_condExp μ p m hm_le a g ?_ ?_ ?_ ?_
    · exact stronglyMeasurable_condProbPast μ p a k
    · exact Filter.EventuallyEq.refl _ _
    · exact ae_zero_le_condProbPast μ p a k
    · exact ae_condProbPast_le_one μ p a k
  -- `(-log g)` is `m`-measurable.
  have h_g_meas_m : Measurable[m] g := (stronglyMeasurable_condProbPast μ p a k).measurable
  have h_neglog_g_meas_m : Measurable[m] (fun x => -Real.log (g x)) :=
    (Real.measurable_log.comp h_g_meas_m).neg
  have h_neglog_g_asm : AEStronglyMeasurable[m] (fun x => -Real.log (g x)) (μZ μ p) :=
    h_neglog_g_meas_m.stronglyMeasurable.aestronglyMeasurable
  -- Pull-out: μZ[(-log g) * ind | m] =ᵐ (-log g) * μZ[ind | m] = (-log g) * g.
  have h_pullout :
      (μZ μ p)[fun x => (-Real.log (g x)) * ind x | m]
        =ᵐ[μZ μ p] fun x => (-Real.log (g x)) * g x := by
    have h_prod' : Integrable (fun x => (-Real.log (g x)) * ind x) (μZ μ p) := by
      refine h_int_prod.congr ?_
      filter_upwards with x using by ring
    have h_pull :
        (μZ μ p)[fun x => (-Real.log (g x)) * ind x | m]
          =ᵐ[μZ μ p] fun x => (-Real.log (g x)) * (μZ μ p)[ind | m] x :=
      condExp_mul_of_aestronglyMeasurable_left h_neglog_g_asm h_prod' h_int_ind
    refine h_pull.trans ?_
    -- (μZ μ p)[ind | m] = g (by definition of g = condProbPast a k = μZ[ind | m]).
    filter_upwards with x
    rfl
  -- Apply `integral_condExp` to relate `∫ (-log g) * ind` and `∫ μZ[(-log g) * ind | m]`.
  have h1 : ∫ x, ind x * (-Real.log (g x)) ∂(μZ μ p)
      = ∫ x, (-Real.log (g x)) * ind x ∂(μZ μ p) := by
    refine integral_congr_ae ?_
    filter_upwards with x using by ring
  have h2 : ∫ x, (-Real.log (g x)) * ind x ∂(μZ μ p)
      = ∫ x, ((μZ μ p)[fun x => (-Real.log (g x)) * ind x | m]) x ∂(μZ μ p) :=
    (integral_condExp hm_le).symm
  have h3 : ∫ x, ((μZ μ p)[fun x => (-Real.log (g x)) * ind x | m]) x ∂(μZ μ p)
      = ∫ x, (-Real.log (g x)) * g x ∂(μZ μ p) :=
    integral_congr_ae h_pullout
  have h4 : ∫ x, (-Real.log (g x)) * g x ∂(μZ μ p)
      = ∫ x, Real.negMulLog (g x) ∂(μZ μ p) := by
    refine integral_congr_ae ?_
    filter_upwards with x
    rw [Real.negMulLog]; ring
  rw [h1, h2, h3, h4]

omit [DecidableEq α] [Nonempty α] in
/-- The integral of `pmfLogCondPast k` decomposes as a finite sum of `negMulLog`
integrals of the per-atom conditional probabilities. -/
private lemma integral_pmfLogCondPast_eq_sum (k : ℕ) :
    ∫ x, pmfLogCondPast μ p k x ∂(μZ μ p)
      = ∑ a, ∫ x, Real.negMulLog (condProbPast μ p a k x) ∂(μZ μ p) := by
  classical
  -- Expand pmfLogCondPast pointwise as a finite sum.
  have h_eq : pmfLogCondPast μ p k = fun x =>
      ∑ a, Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbPast μ p a k x)) := by
    funext x
    exact pmfLogCondPast_eq_sum_indicator_neg_log μ p k x
  rw [h_eq]
  -- Each summand is integrable.
  have h_int_a : ∀ a : α, Integrable
      (fun x => Set.indicator (coord0 ⁻¹' {a}) (fun _ => (1 : ℝ)) x
        * (-Real.log (condProbPast μ p a k x))) (μZ μ p) := by
    intro a
    refine integrable_indicator_mul_negLog_of_condExp μ p
      ((pastFiltration (α := α)) k) ((pastFiltration (α := α)).le _) a
      (condProbPast μ p a k) (stronglyMeasurable_condProbPast μ p a k)
      ?_ (ae_zero_le_condProbPast μ p a k) (ae_condProbPast_le_one μ p a k)
    exact Filter.EventuallyEq.refl _ _
  rw [integral_finsetSum _ (fun a _ => h_int_a a)]
  refine Finset.sum_congr rfl ?_
  intro a _
  exact integral_indicator_mul_negLog_condProbPast μ p k a

/-- **Per-step integral identity**: integrating `pmfLogCondPast k` against `μZ`
gives `conditionalEntropyTail μ p k`.

The proof structure:
1. Decompose `∫ pmfLogCondPast k dμZ` into a finite sum of
   `∫ negMulLog(condProbPast a k) dμZ` (via `integral_pmfLogCondPast_eq_sum`).
2. Identify each `condProbPast a k` with the `condDistrib`-form regular
   conditional probability (via `condDistrib_ae_eq_condExp` after identifying
   `pastSigma k` with the comap of an appropriate projection).
3. Transport the resulting integral along the joint pushforward to the
   `(blockRV k, obs k)` side via Phase B's `shiftedMarginal` identity.
4. Recognize the result as `condEntropy μ (p.obs k) (p.blockRV k)
   = conditionalEntropyTail μ p k`.

**Deferred** — step 2 (`condProbPast` vs `condDistrib` identification) and
step 3 (joint-law transport) are ~250-400 LOC of bridging infrastructure;
budgeted as a follow-up. The forward-filtration redesign is mathematically
complete; what remains is purely a glue lemma between the `μZ`-side
condExp-defined past entropy and the `μ`-side condDistrib-defined past
entropy, both well-defined on their respective sides. -/
private lemma integral_pmfLogCondPast_eq_conditionalEntropyTail (k : ℕ) :
    ∫ x, pmfLogCondPast μ p k x ∂(μZ μ p) = conditionalEntropyTail μ p k := by
  sorry

/-- **The SMB integral identity** `∫ pmfLogCondInfty dμZ = entropyRate μ p`.

Combines:
* `integral_pmfLogCondPast_eq_conditionalEntropyTail` — the per-step identity;
* DCT (forward Lévy a.s. limit + `[0, log(card α)]` uniform bound on
  `pmfLogCondPast`) — passing the integral to the limit;
* `entropyRate_eq_lim_condEntropy` — `conditionalEntropyTail μ p k → entropyRate`. -/
theorem integral_pmfLogCondInfty_eq_entropyRate :
    ∫ x, pmfLogCondInfty μ p x ∂(μZ μ p) = entropyRate μ p := by
  classical
  -- (1) Per-step identity for each `k`: `∫ pmfLogCondPast k = conditionalEntropyTail k`.
  have h_step : ∀ k : ℕ,
      ∫ x, pmfLogCondPast μ p k x ∂(μZ μ p) = conditionalEntropyTail μ p k :=
    fun k => integral_pmfLogCondPast_eq_conditionalEntropyTail μ p k
  -- (2) Forward Lévy: `pmfLogCondPast k → pmfLogCondInfty` a.s.
  have h_ae_lim := pmfLogCondPast_tendsto_pmfLogCondInfty μ p
  -- (3) Uniform bound on `‖pmfLogCondPast k‖` for DCT.
  -- `pmfLogCondPast k x = -log(condProbPast (coord0 x) k x)` (modulo null set).
  -- Bound: `0 ≤ pmfLogCondPast k x ≤ -log(condProbInfty (coord0 x) x)` — not uniform
  -- in `k` in a strong sense. Use `∫ |pmfLogCondPast k| = ∫ pmfLogCondPast k ≤ log(card α)`
  -- (Jensen / Gibbs) for a uniform integrability argument via `MartingaleTheorem.tendsto_integral`.
  -- (Cleaner path: each `pmfLogCondPast k` is in [0, ∞), and the family is uniformly
  -- bounded in L¹ by `log(card α)`; UI + a.s. convergence + Scheffe gives L¹ convergence,
  -- hence integral convergence.)
  --
  -- DEFERRED: requires per-step uniform L¹ bound `∫ pmfLogCondPast k ≤ log(card α)`
  -- (which follows from positivity of negMulLog + ∑_a g_a = 1 + Jensen on -log),
  -- plus a uniform-integrability or domination argument. Concretely, this is
  -- ~80-150 LOC of integration estimates around the conditional Gibbs inequality.
  -- Combined with `h_step` and `entropyRate_eq_lim_condEntropy`, the result follows
  -- by `tendsto_nhds_unique`.
  sorry

end Backward

end InformationTheory.Shannon.TwoSided
